### ISSUE TITLE
Async frame work needs feature to check if all workloads of a certain type have finished.

### ISSUE THREAD

**Issue by MichaelHuth** [AllenInstitute/MIES#101]
Currently the async frame work checks only on ASYNC_Stop if all work loads have finished and were read out.

However if different work load types are sent it would be good to have the option to check if a certain type of workloads completely finished. So one could wait for e.g. the TP processing without stopping the frame work.

The extension would be to implement counting of work loads per type, similar as it is done globally already. If the counted read out equal the number of pushed workloads it is considered finished as in this moment are no workloads of that type in limbo.

**Comment by t-b** [comment]
Encountered in our test suite as `CheckThatTPsCanBeFound` is flaky due to this bug. Sometimes a testpulse is still lingering in the async framework and thus the test fail.

**Comment by MichaelHuth** [comment]
Note for debugging this in IP8: When editing source code IP enters uncompiled state where we have installed a hook. This hook stops the async framework which finishes all jobs. So on uncompile all lingering content is read out, which changes the state of data in the experiment. WHen debugging one has to be aware of that.

**Comment by MichaelHuth** [comment]
@t-b I found something that might be problematic and is related:

You have a single DA_Ephys panel locked and acquire TP -> directly close the panel while TP is running -> Now edit a procedure file to enter uncompiled state

What happens is: The ASYNC framework tries to finish lingering TP results. TPStorage tries to get the current GUIState wave of the already closed panel (line 416). Since the panel was already cleaned up access fails in line 476 MIES_DAEphys_GuiState.ipf.

However if a user does not go to uncompiled mode and reopens the same device with different settings then TPStorage will try to read from a 'wrong' panel next time ASYNC ReadOut is called.

**Comment by t-b** [comment]
@MichaelHuth Can you provide a test case for the issue?

**Comment by MichaelHuth** [comment]
Here is a test case:
https://github.com/AllenInstitute/MIES/pull/343

I tried first the direct way with a modified dummy panel -> recreation macro generation and "COMPILEPROCEDURES " call, but it seems that on 'Uncompile' the RTE vanishes.

**Comment by MichaelHuth** [comment]
Suggestion how to resolve that:

Implement in ASYNC frame work a Text wave that holds unique string tags and a second numeric wave with two columns. The text wave and numeric wave have the same column size.

Whenever a workload is created it has to bring a tag (unique string). 

The text wave stores the tags. If a tag is not present in the text wave we add it and also increase the numeric wave and initilize this row with zero.

Depending on the tag: The first column of the numeric wave counts up whenever a workload is pushed and the second column counts up if a workload was read out.

Additional functions:

- ASYNC_IsPending(string tag) returns 1 if the number in the first column is unequal from the number in the second column at row of the tag.

- ASYNC_RemoveTag(string tag) removes the row with a tag in both waves.

e.g. for TP the tags should consist of "TP" and the originating unique DAEphys panel.
