### ISSUE TITLE
Process all available TP with ITC hardware

### ISSUE THREAD

**Issue by MichaelHuth** [AllenInstitute/MIES#102]
Currently for ITC hardware only the last available TP in the background task is further processed.

If the task is late it happens that in the sampled data more than one TP is available. This can be used to process all available (yet unprocessed) TPs.

**Comment by t-b** [comment]
Let's tackle that after https://github.com/AllenInstitute/MIES/issues/49.

**Comment by timjarsky** [comment]
Closing, no use case for this feature at this time. May reopen if automation with ACQ4 requires TP data from every TP.

**Comment by t-b** [comment]
Michael is currently working on https://github.com/AllenInstitute/MIES/issues/336. And we found out again that in TP acquistion we only evaluate the last TP (for ITC, Sutter) but all for NI. We already do evaluate all TPs with "TP during DAQ".

> May reopen if automation with ACQ4 requires TP data from every TP.

Should that now be fixed?

**Comment by t-b** [comment]
@timjarsky See https://github.com/AllenInstitute/MIES/issues/102#issuecomment-2830750047.
