### ISSUE TITLE
After changing DA/ADC channel in DA_Ephys HW tab, can not start TP/DAQ with error 'The unit for ADCchannel x is empty."

### ISSUE THREAD

**Issue by MichaelHuth** [AllenInstitute/MIES#103]
Also happens with error "The unit for DACchannel x is empty."

Current work around is to click "Auto Fill".

**Comment by t-b** [comment]
That is actually not a bug but how you have to configure MIES at the moment. Setup the headstage<->Amplifier connection in the hardware tab, use `Auto Fill` to get the settings and then start DAQ.

**Comment by t-b** [comment]
This should work automatically if we can do it.

**Comment by t-b** [comment]
Fixed in PR 1064.
