### ISSUE TITLE
GuiPopupMenuExt fails with lots of USER_ submenu entries

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#1036]
File: Chat-IRES-Cre-neo;Ai14-582721.05.04.01.nwb on the Allen Institute FTP Account.

The old problem with too long popmenus is back, see 
![Unbenannt](https://user-images.githubusercontent.com/1185677/129929903-c63d4cd7-b04a-4e09-992f-219409d73788.png).

@MichaelHuth Any ideas?

**Comment by timjarsky** [comment]
@t-b @MichaelHuth can we query the available vertical space on the monitor and set a fixed maximum for any popup menu based on the available space?

**Comment by t-b** [comment]
@timjarsky That will work but will also be a lot of effort. The problem here might just be a hardcoded limit of submenus. These are after all ~420 LBN entries to show in that list.

**Comment by timjarsky** [comment]
@t-b my first thought was a hardcoded limit but I didn't think it would be well received. Would it also be possible to group the items in the list by their subname. For example, all the USER_Rheo entries would be in a single list?

**Comment by t-b** [comment]
> @t-b my first thought was a hardcoded limit but I didn't think it would be well received.

We wanted to avoid a hardcoded limit initially, but this is how submenues work, so we had to use one.

> Would it also be possible to group the items in the list by their subname. For example, all the USER_Rheo entries would be in a single list?

Yes we can do that, USER LBN entries from PSQ analysis functions are common, so this makes sense.

**Comment by MichaelHuth** [comment]
For the general problem I think there is no good general solution.

I closest thing would be to add another grouping method for entries or entries grouped by a specific function for LBN entries only.

Also extending the number of submenues is not too hard, but at some point a question of GUI performance, since Igor calls the custom dynamic menu functions rather often.
