### ISSUE TITLE
Analysis functions: Store chunk start/end/name as user epochs

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#1040]
Pre pulse baseline chunks
- First starts after the onset delay (auto + user) and ends 500ms after
- Continue until you reach the pulse onset. Incomplete chunks are ignored.

Pulse

- Ignore the pulse (it's length is either predetermined and fixed or stored in the LBN)

Post pulse baseline chunks

- Ignore the next 500ms chunk
- Continue with 500ms chunks until the stimset ends. Incomplete chunks are ignored.

The user epochs should be added to the epochs wave.

- [x] Add EP_XXX function for adding user epochs that any user (public) can call
- [x] Adapt documentation in `epoch_information.rst`
- [x] Store chunks as user epochs
- [x] Add tests for user epochs
- [x] Check for correct chunk positions in PSQ_XXX tests

Starting functions:
- PSQ_EvaluateBaselineProperties
- PSQ_EvaluateBaselineChunks
- EP_AddUserEpoch
- Tests: `runwithOpts(testcase = "PS_DS_Sub1")`

If a sweep is aborted through an event, then there may be epochs beyond sweep end. The epochs from beyond the sweep end are discarded after acquisition. Thus, adding all chunks as user epochs is ok, as possible invalid epochs get discarded later.

**Comment by t-b** [comment]
@MichaelHuth I've unassigned you as I think it makes more sense for you to dive deeper into Sweepformula.

**Comment by MichaelHuth** [comment]
Add user epoch in PSQ_EvaluateBaselineChunks
