### ISSUE TITLE
Sweepformula: Allow to use epoch info for ranges in the sweeps command

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#1041]
New function `epoch(DAC, name, [type])`. The optional `type` argument has the following allowed values:
- `range`: same as ommited, 1D array with 2 elements with start/stop positions in DAC x-units
- `name`: returns the name of the epoch
- `treelevel`: tree level (numeric)

Example commit introducing `area`: 8b9d5444 (SweepFormula: Add area operation, 2020-06-11)

**Comment by t-b** [comment]
Missing `/Z`:
```
			WAVE channelNumberIndex = FindIndizes(traces, colLabel = "channelNumber", var = channels[j][%channelNumber])
				WAVE channelTypeIndex = FindIndizes(traces, colLabel = "channelType", str = StringFromList(channelType, XOP_CHANNEL_NAMES))
```

**Comment by t-b** [comment]
I just chatted with @timjarsky and we realized that the name of the epoch is currently a bit ill-defined. First it is not-unique (multiple baselines) and second it can be very long due our additional tags. So we thought about adding a new `ShortName=XXX` entry to the epochs. This would be preferred (if present) over the full long name.

The naming scheme of the short names is as follows (explanation in parantheses):
```
TP_B0 (Testpulse baseline 0)
TP
TP_P (Testpulse pulse)
TP_B1
B0 (baseline 0)
ST (stimset)
E1_PT_P0_P (epoch 1, pulse train, pulse 0, pulse)
E1_PT_P0_B (epoch 1, pulse train, pulse 0, pulse)
...
```
The main goal of the short names are that these are unique and short and (somehow) user friendly.

@MichaelHuth We can chat about this on friday.

**Comment by MichaelHuth** [comment]
After discussion with Thomas:

Change API to:  `epochs(array sweeps, array channels, string shortName, [type])`

**Comment by MichaelHuth** [comment]
Epoch short name convention:

```
Before TP:

B0_OD // onset Delay user
B0_DD // distributed daq
B0_TD // termination delay
B0_DO // distributed daq opt
B0_TR // trailing baseline from distributed daq

TP:

TP 		// full TP
TP_P // Testpulse Pulse
TP_B0 // Testpulse baseline Front
TP_B1 // Testpulse baseline back

Stimset:

ST // Stimset
Ex // Epoch
Ex_PT // PulseTrain (not used)
Ex_PT_Px // PulseTrain Single Pulse
Ex_PT_Px_BT // PulseTrain Single Pulse baseline before left or rightmost pulse
Ex_PT_Px_P // PulseTrain Single Pulse Pulse Active
Ex_PT_Px_B // PulseTrain Single Pulse Pulse Inactive
Ex_PT_BT // PulseTrain baseline trail if zero pulses
ST_B // for multiple sweeps where each sweep has a different length in stimset they have the same length
		 // Stimsets that are extended have a baseline added

```

**Comment by MichaelHuth** [comment]
@t-b The first version is working. We should chat once more about the short name convention before I look through the tests and the docu.
