### ISSUE TITLE
SweepFormula: Comment sign `#` does not work reliable

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#1054]
Failing:
```
# abcd vs 1
# test
abcd vs 2
```

We have specified in the documentation:

> A comment character # causes the skip state which does not write to the buffer until a line ending character is encountered.

**Comment by MichaelHuth** [comment]
This works as documented:

The first " vs " splits the input code into the formula for y and x.
Formula for y: # abcd
Formula for x: 1\r# test\rabcd vs 2

When the rule for the comment in formulas is applied the result is:
null vs "1abcd vs 2"
