### ISSUE TITLE
SetControlInEvent: Support multiple databrowsers locked to the same device

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#1057]

**Comment by timjarsky** [comment]
@t-b I put this issue on the todo because I thought it might be related to the issue where analysis functions update the sweep formula on all locked data browsers, instead of just one DB. If that's not right, then we can remove this from the to-do list and create a separate issue.

**Comment by t-b** [comment]
Nope you are totally right. This is very related.
