### ISSUE TITLE
Make MSQ_RMS_LONG_THRESHOLD  and MSQ_RMS_SHORT_THRESHOLD  configurable for patch seq functions

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#1072]
- [x] Add new optional analysis parameter `SamplingFrequency` defaulting to 50kHz. We then check in `POST_SWEEP_EVENT` that we acquired data with this frequency. Failing to do so is a QC failure.
- [x] Change the noise constants into analysis param; const double MSQ_RMS_SHORT_THRESHOLD = 0.07¶
const double MSQ_RMS_LONG_THRESHOLD = 0.5, optional with current value as default. Store used value in LBN.

**Comment by timjarsky** [comment]
@t-b change the noise constants into analysis param; const double MSQ_RMS_SHORT_THRESHOLD = 0.07¶
const double MSQ_RMS_LONG_THRESHOLD = 0.5

Yes, optional with the existing values as default.

I don't want to make the target v constant user accessible at this time.

**Comment by t-b** [comment]
We also want to store the value in the LBN.
