### ISSUE TITLE
AnalysisBrowser: Make it more usable when working with data from multiple folders

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#1099]
The analysis browser currently looks like https://alleninstitute.github.io/MIES/analysisbrowser.html. The idea behind how it is used is that one selects a directory and the can open multiple files from that directory.

But when you need to load files from vastly different folders this currently does not work nicely:
- Once the analysis browser rescans a directory all the open sweepbrowsers loose their data/LBNs/etc without the user being aware of that
- One can only open one analysis browser at a time

The best workaround for NWB files is to Drag n' Drop them into IP as that works without having to select different directories.

Solutions:
- Add listbox with addition/removal for handling multiple source paths.
- Allow open button to refer to files and folders
- Advertise the Drag n' Drop feature in the analysis browser

**Comment by timjarsky** [comment]
Would be nice if drag-and-drop worked with folders. Multiple d-a-d would be additive. 

- [ ] ask wavemetrics to have a hook for folders.

**Comment by t-b** [comment]
> ask wavemetrics to have a hook for folders

Created an issue (4373) with them.
