### ISSUE TITLE
Negative TP resistance values

### ISSUE THREAD

**Issue by timjarsky** [AllenInstitute/MIES#110]
TP analysis can return negative resistance values

![image](https://user-images.githubusercontent.com/5693697/50179778-c690db00-02bc-11e9-9907-9c3c7ec01da2.png)

**Comment by t-b** [comment]
@timjarsky Can you upload a sample pxp with TPs stored?

**Comment by timjarsky** [comment]
@t-b negative values are a result of the data so this isn't a high priority item should we use abs for resistance values?

**Comment by t-b** [comment]
@timjarsky I'm not a big fan of `abs`-ing results so that they are positive. If you can live with the current results I would keep it as it is.

**Comment by t-b** [comment]
Closing for now.
