### ISSUE TITLE
IVSCC: Enhance interaction with WSE

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#1101]
WSE is used by IVSCC to control MIES and ACQ4 during an experiment.

We want to further automate the experiments and found the following topics at our meeting on 9/29/21 12am PST:
- More publisher messages:
   - [x] clamp mode switch
   - [x] successful TP tuning (auto TP), implemented in https://github.com/AllenInstitute/MIES/pull/1016
   - [x] bridge balance auto (capture bridge balance and cap comp sweep)
   - [x] break in
- auto switch to CC (after image acquisition)
- [x] IVS_ExportAllData should return the value from NWB_ExportAllData.

Hold off on the next one (Chat with Tim before doing):
- Write analysis function to publish message on each event. Use parameters to selectively enable/disable events. Will be used with other analysis functions together, chained via code.

**Comment by aleonlein** [comment]
@t-b What is the command to check the TP Tuning box? I have tried a variety of things and could not get the box checked

**Comment by aleonlein** [comment]
@t-b Ah, I must have forgotten the integer. I will try again when the rig is available. Thank you!
