### ISSUE TITLE
Help with using MIES

### ISSUE THREAD

**Issue by jessewhite2007** [AllenInstitute/MIES#1104]
Hello, I'm new to coding and am going to be using MIES for electrophysiology experiments. Is there a manual or "how to" for using MIES for whole cell patch clamp? I can't figure out simple things like how to write my own protocols. Thanks

**Comment by timjarsky** [comment]
@jessewhite2007 it is possible to get a relatively recent version of the IVSCC production stimulus sets from within MIES; 
![image](https://user-images.githubusercontent.com/5693697/137235909-0032367f-f88a-4048-9da7-203001a3323e.png)
