### ISSUE TITLE
NWB export failing/creating too small files

### ISSUE THREAD

**Issue by sfowen** [AllenInstitute/MIES#1134]
Description:
- What was MIES doing at the time of the unexpected behavior?
Attempting to export an NWB file

- Did user input immediately precede the unexpected behavior?
Yes

- What did you expect to happen?
We tried to export a .pxp file as an .nwb file using the manual Mies Panels ->NeuroData Without Borders -> Export All Data to NWB function. MIES successfully generated an NWB file, but it was essentially empty. Exported .nwb file size is only 23 kb.

Igor Pro Experiment files can be attached as zip file if needed.
Attached files include the original pxp file, the .nwb file that was automatically generated during recording, and the failed attempt to generate a -compressed.nwb file by manual export.

The following contains installation information (keep unchanged):

```
MIES version: Release_2.3_20210908-177-g22c735d78
Date and time of last commit: 2021-11-03T13:23:27+01:00
Submodule status:
 3c125f148c12e579a52c8b730d54dac5ffca2322 Packages/IPNWB (heads/main)
 56f1da31d786a593892280c2d2b2b1190def0fb5 Packages/doc/doxygen-filter-ipf (heads/main)
 e79dec5762733aefd3af3a36dda73d040ae2ce62 Packages/unit-testing (e79dec5)
```

```
Igor Pro version: OS:Windows 10 Pro;OSVERSION:6.3.19043;LOCALE:US;IGORFILEVERSION:8.0.5.1;
```

```
Installation self-test results:
Checking system properties:
Igor 64bit: 8.05, 37456
Windows 10: True
ASLR: True (Very Bad)

Checking known defines:
DEBUGGING_ENABLED: No
EVIL_KITTEN_EATING_MODE: No
BACKGROUND_TASK_DEBUGGING: No
THREADING_DISABLED: No

Checking base installation:
Mies version info: Valid "Release_2.3_20210908-177-g22c735d78..." (Nice!)
ITC XOP: Found version 1.0.2.0 (Nice!)
JSON XOP: Found version 1.0.0.1 (Nice!)
VDT2 XOP: Found version 2.2.1.0 (Nice!)
HDF5 XOP: Found version 2.0.2.0 (Nice!)
Axon Telegraph XOP: Found version 3.0.0.0 (Nice!)
Multi Clamp Commander XOP: Found version 2.0.0.0 (Nice!)
ZeroMQ XOP: Found version 1.0.0.1 (Nice!)
JSON XOP: Present in the right version (version-753-g902d43f) (Nice!)
Results: 9 checks, 1 number of errors

Checking extended installation:
NI-DAQ MX XOP: Found version 1.1.5.0 and hash is ok (Nice!)
Results: 1 checks, 0 number of errors
```

**Comment by t-b** [comment]
Files on Scotts' FTP account are LP210721B_09A_03.pxp and LP210721A_11A_03.pxp and are located in the folder issue1134.
