### ISSUE TITLE
SweepFormula: Allow user to plot multiple y against a single x - `with` plotting

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#1141]
The recent investigation and tightening of the `,` behaviour was triggered by users wanting to plot two y datasets against one x dataset.

A first guess how to achieve that results in

```
[1, 2], [3, 4]

vs

[5, 6]
```

But unfortunately that gives

![image](https://user-images.githubusercontent.com/1185677/141105398-ecd0649e-aff3-4b9c-8802-50de13496faf.png)

This is due to the fact the y array is in fact a 2D array now with the layout

```
1	2
3	4
```

and x is

```
5
6
```

and we plot row wise y against x.

I haven't thought it through complete but I guess we can't just change the approach and plot each y row against the x **column**.

If that hunch is correct we have to basically come up with another way for the user to make that work.

Idea:

```
[0, 1,2, 3]

with

[5, 6,7, 8]

with

[13, 14, 15, 16]

vs

[9, 10, 11, 12]

# the user expects here
# 3 traces: Y0, Y1, Y2 vs X0 in one graph
```

The new plotter command `with`  avoids us having to touch the formula parser. And this should also work with preserving channel information via #1131.

**Comment by MichaelHuth** [comment]
I think the approach is a feasible option. We can collect the formulas this way and "send" the pairs to the executor/plotter.
