### ISSUE TITLE
Epoch info is off-by-one for level 3 pulse and baseline start/end times

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#1147]
Investigate if this is something we can fix easily or if it depends on real vs minimum sampling interval etc. As this information is gathered in the wavebuilder it might also be a problem there.

Example file on FTP: `2021-10-22 Spike Control Failures/2021_10_20_111205-compressed_resave.nwb`

**Comment by timjarsky** [comment]
Investigate to determine the cause and confirm off-by-one is restricted to level 3

**Comment by MichaelHuth** [comment]
- Check in WB how edges are created in discrete stimset data from edge time
- How does decimation shifts (trunc or round)
- How is epoch time calculcated compared to WB edge time
- Can we reliably calculate the sample before / after the edge in DAQDataWave?

Possibilities:
- Change epoch time creation to be at correct sample points

- Allow to calculate epochs for old non-epoch data in the future
- Revise creation of stimset such that WB stimset has the same sample rate as the target DAQDataWave, remove decimation

**Comment by timjarsky** [comment]
"

  *   Revise creation of stimset such that WB stimset has the same sample rate as the target DAQDataWave, remove decimation

— it's not possible to know the sample rate at the time a stimset is made in the WB. E.g., users can turn off headstage during a RA cycle. One way this could work is if the WB made the stimset at all supported sample rates however this feels like a BIG change in how MIES works.

On Jan 23, 2024 9:24 AM, Michael Huth ***@***.***> wrote:

  *   Check in WB how edges are created in discrete stimset data from edge time
  *   How does decimation shifts (trunc or round)
  *   How is epoch time calculcated compared to WB edge time
  *   Can we reliably calculate the sample before / after the edge in DAQDataWave?

Possibilities:

  *   Change epoch time creation to be at correct sample points

  *   Allow to calculate epochs for old non-epoch data in the future

  *   Revise creation of stimset such that WB stimset has the same sample rate as the target DAQDataWave, remove decimation

**Comment by t-b** [comment]
>> Revise creation of stimset such that WB stimset has the same sample rate as the target DAQDataWave, remove decimation

> it's not possible to know the sample rate at the time a stimset is made in the WB. E.g., users can turn off headstage during a RA cycle. One way this could work is if the WB made the stimset at all supported sample rates however this feels like a BIG change in how MIES works.

The point was in the possibilities section, so we don't plan to do that. The way this would work is that we would request a simset to be created with a given sampling rate. And yes this would be a BIG change, and also not something which would help with existing data.

**Comment by MichaelHuth** [comment]
1. by definition: duration of pulses and other non-baseline features in wave builder are including the left and right edge points, e.g. duration 2: ..., 0, 1, 1, 1, 0, ... -> check in wavebuilder if that is correctly implemented for all non-baseline features
2. we want to define that for epochs the start time/point is included in the epoch range and the end time/point is not included in the epoch range. This let us keep the non-gap logic where the start of the next epoch equals the end of the previous.
3. change epoch creation such that the times match sample points on the sweep wave grid.
4. EP_FetchEpochs add time correction for old data such that 2. and 3. is fulfilled.
5. SFH_GetSweepsFromFormula adapt to treat the range end as not inclusive ( - DimDelta(sweepWave,ROWS))
6. adapt epochs operation to return inclusive (start) / exclusive (end) ranges
7. add trunc/round to index determination at decimation to equal current behavior.
