### ISSUE TITLE
Add support for zeroing individual traces in PA plot

### ISSUE THREAD

**Issue by timjarsky** [AllenInstitute/MIES#115]
We presently support trace zeroing on a per sweep basis but often slow deviations from zero over time result in the loss of effective zeroing in the pulse plot. To overcome this issue, let's add a zero option (user triggered) to the individual traces in the PA plot.

**Comment by t-b** [comment]
See function `Function ZeroWave(wv)`.

**Comment by t-b** [comment]
Fixed via PR 1109.
