### ISSUE TITLE
Analysis Function: Access resistance check

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#1228]

**Comment by timjarsky** [comment]
**WIP**

Name: AccessResistance
ShortName: Ra (preferred casing)

Objective: Capture a voltage clamp sweep with 3 test pulses, in addition to the inserted TP.

Measure the peak resistance
Measure the steady-state resistance
the ratio of peak to steady-state < analysis param peakToSteadyState

One passing sweep.

MID_SWEEP_EVENT:

1 baseline selection user epoch:

0: Short and long RMS and leak current < analysis param leakCurrent




PRE_SET_EVENT:

No autobias, no holding potential
Bridge balance and capacitance compensation should be on
Only one active headstage
Current clamp
No TTL
No oodDAQ/dDAQ
Add baseline selection epochs:

epoch 0: baseline 0

epoch 1: something else

epoch 2: baseline 1

Check that amplitude of epochs are zero

POST_SWEEP_EVENT:

sweep QC: baseline QC and sampling interval QC and spike QC (passing is no spikes)
POST_SET_EVENT:

If set QC passes: Set target V of autobias to that measured value, turn on autobias
Publish: set QC and measured voltage
POST_DAQ_EVENT:

Set next starting and ending stimset if set QC passes and both are given. Turn on indexing if ending stimset is given.
Analysis parameters:

NextStimSetName:string (optional)
NextIndexingEndStimSetName:string (optional)
Two for absolute and relative average voltage difference like for DAScale
BaselineRMSShortThreshold:variable
BaselineRMSLongThreshold:variable
[SamplingFrequency:variable],[SamplingMultiplier:variable]
NumberOfFailedSweeps:variable
BaselineChunkLength:variable
UserOffsetTargetVAutobias:variable
FailedLevel:variable (for spike check)

**Comment by t-b** [comment]
@timjarsky 

Questions:
- Is POST_DAQ_EVENT correct?
- In which position in list at the top of https://alleninstitute.github.io/MIES/file/_m_i_e_s___analysis_functions___patch_seq_8ipf.html is that analysis function being run?

**Comment by timjarsky** [comment]
@t-b yes, POST_DAQ_EVENT is correct. It comes after PSQ_SealEvaluation and will ultimately come before True resting membrane potential.

**Comment by t-b** [comment]
And BL QC is in MID_SWEEP_EVENT because we want to abort early on failure, right?

**Comment by timjarsky** [comment]
@t-b correct, although I did have to think about it. I'm choosing standardization (across analysis functions) rather than specialization for minor benefit.

**Comment by t-b** [comment]
@timjarsky The pipetteInBath analysis function which uses the same stimset layout, has a `NumberOfTestpulses` analysis parameter. This sounds like this analysis function here should have that as well or?
