### ISSUE TITLE
SweepFormula: Add new TP mode

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#1247]
- Allow user to choose between single (`exp_XOffset`) and double exponential. See `TP_AutoFitBaseline` for how it calls CurveFit.
- Extend existing TP operation
- Works on a single TP at a time
- Fit range: Only the trailing baseline. If the next epoch after the TP has amplitude zero enlarge the fit range by at most the trailing baseline stolen from the next epoch, cropped to the next epoch length of course.
- returns `tau [ms]` slow (aka large) by default, allow user to return the other one as well
- Allow returning amplitudes (using y units of the data) as well
- Same approach for IC/VC
- Visualize fit if debugging is enabled for MIES_SweepFormula.ipf

Use one of the IVSCC files as reference, e.g. Rbp4-Cre_KL100;Ai14-543835.09.09.01.pxp.

**Comment by t-b** [comment]
Chat with Tim to clarify objectives and more fine-grained specs.

**Comment by t-b** [comment]
I've chatted with Tim about the question how to integrate the new mode.

And we think

```
tp(fit(...), [array selectData[, array ignoreTPs]])
``

is the way to go. In this case we will also have the operations base(), ss(), inst(). The help for those operations should be part of `tp` and the topics should only link there. The current numeric constants and strings for `mode` must also be removed so that we don't create a compatibility mess.

**Comment by MichaelHuth** [comment]
@timjarsky Some questions came up regarding the fitting:

- What is exactly meant by "the next epoch after the TP"? There are several candidates here:
    - the epoch that follows TP_B1 (aka trailing baseline) on the same tree level or if not present on a lower tree level
    -   the epoch that follows TP (aka test pulse) on the same tree level or if not present on a lower tree level

- to determine if TP_B1 is shortened, is it correct to use TP_B0 as reference interval?

- if TP_B1 is shortened and I extend the range within the following epoch then it is not relevant if the following epoch has a non-zero amplitude within the range?

- Should the x0 constant for the exp_XOffset and dblexp_XOffset kept at the default value (left edge of fit range)

- When dblexp_XOffset if fitted and amplitude should be returned, which amplitude should it be? (e.g. the higher amplitude of both?)

- TP_AutoFitBaseline has a criteria where the residuals are evaluated and a fit quality threshold is applied. Should such criteria be also applied here? (the same threshold?)

**Comment by timjarsky** [comment]
> @timjarsky Some questions came up regarding the fitting:
> 
> * What is exactly meant by "the next epoch after the TP"? There are several candidates here:
>   
>   * the epoch that follows TP_B1 (aka trailing baseline) on the same tree level or if not present on a lower tree level
>   * the epoch that follows TP (aka test pulse) on the same tree level or if not present on a lower tree level

The latter. TP_B1 may, in some cases, not be long enough to capture the decay of the exponential. The goal is to use as much data as is suitable and available to capture the decay. So, I want to include the epoch that follows the TP (TP_B0, TP_P, and TP_B1) if the amplitude = 0.

> * to determine if TP_B1 is shortened, is it correct to use TP_B0 as reference interval?

Interesting question, do we allow for TP_B0 and TP_B1 to be different durations?

> * if TP_B1 is shortened and I extend the range within the following epoch then it is not relevant if the following epoch has a non-zero amplitude within the range?

Yes, the following epoch must have amplitude = 0 to be included.

> * Should the x0 constant for the exp_XOffset and dblexp_XOffset kept at the default value (left edge of fit range)

Yes, I think that makes sense. Do you see any benefit for doing something else?

> * When dblexp_XOffset if fitted and amplitude should be returned, which amplitude should it be? (e.g. the higher amplitude of both?)

Good question. I think there are times when the user will want to see both and other times when the user will want to pick.

> * TP_AutoFitBaseline has a criteria where the residuals are evaluated and a fit quality threshold is applied. Should such criteria be also applied here? (the same threshold?)

That's a good idea, but I'm not sure how to select the threshold. Do you have any suggestions?

Thanks!

**Comment by t-b** [comment]
> do we allow for TP_B0 and TP_B1 to be different durations?

No. Pre and post pulse baselines are always the same for TP.

**Comment by timjarsky** [comment]
@MichaelHuth here is a sample trace and fit where the baseline was extended to include the neighboring amplitude = 0 epoch

![image](https://user-images.githubusercontent.com/5693697/200643189-e642f06d-931d-428a-b06a-a84f84cd7939.png)

In the above example the neighboring epoch is 500 ms. We may want to limit the length of the data we add. For example, if the next epoch was 10 sec, we definitely would not want to use all of it.

**Comment by t-b** [comment]
@timjarsky 
> We may want to limit the length of the data we add. For example, if the next epoch was 10 sec, we definitely would not want to use all of it.

Harcoded 500ms? Or optional parameter with 500ms default?

**Comment by timjarsky** [comment]
@t-b Let's go with optional and a 250ms default.
