### ISSUE TITLE
PulseAveraging: Indiviual traces and average traces are offsetted

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#128]
Probably introduced in the deconvolution support.

Good:
![pulseaverage](https://user-images.githubusercontent.com/1185677/52976507-19c10000-33ca-11e9-9bf6-afa1d8abc01c.png)

Bad:
![pulseaveragewithindividualtraces](https://user-images.githubusercontent.com/1185677/52976508-19c10000-33ca-11e9-8acf-0414e660cb33.png)

Found in version

```
Release_1.7_20180802-533-g38794095
Date and time of last commit: 2019-01-25T12:12:12-08:00
Submodule status: 
160000 579ef3a0b80da22b5b5dfb512792ea27985b49d6 0    Packages/IPNWB
160000 fc912398402a9a6dcfa1b129e2fb224294635e38 0    Packages/ITCXOP2
160000 27e19b944c6edec48afc1a18fdedd0a9b3a41328 0    Packages/ZeroMQ
160000 4a762588f5b627aa3b0e7410d887c19ea817d60f 0    Packages/doc/doxygen-filter-ipf
160000 3d5ee58e144d87cb89168dc1534204c22deeb7ba 0    Packages/unit-testin
```

and in file 2019_02_13_131055.nwb (available on the FTP).

**Comment by t-b** [comment]
Bug report from @scseeman.

Comment:

> and it's only when you try to go back to previous sweeps, it plots properly (w/ or w/o deconvolved) on the most recent sweep

**Comment by ukos-git** [comment]
The problem is with cached average waves without crc calculation. The destination average waves did not get overwritten with the cached waves. With CRC wave name suffix this has not been a problem since every wavename is unique and there is no need to overwrite.

**Comment by t-b** [comment]
Fixed in PR 1095.
