### ISSUE TITLE
Multi device with NI hardware keeps being disabled

### ISSUE THREAD

**Issue by timheistek** [AllenInstitute/MIES#1292]
Description:
After upgrading MIES to newest version I get errors when running PSQ_DAscale function. I'm recording using a NI PXI-6259 digitizer and model cell connected to the headstage. MIES aborts after the first sweep and subsequent pressing of acquire data button gives errors

Igor Pro Experiment files can be attached as zip file if needed.

The following contains installation information (keep unchanged):
```
MIES version: Release_2.4_20211216-284-g22a10414
Date and time of last commit: 2022-02-25T09:08:15+01:00
Submodule status:
 f3493461480eaafa97939940693ed693860048a6 Packages/IPNWB (heads/main)
 56f1da31d786a593892280c2d2b2b1190def0fb5 Packages/doc/doxygen-filter-ipf (heads/main)
 5359bdbaad31451d6ebb9c88cca09d48357a41bb Packages/unit-testing (heads/main)
```

```
Igor Pro version: OS:Windows 10 Pro;OSVERSION:6.3.19043;LOCALE:US;IGORFILEVERSION:8.0.5.1;
```

```
Installation self-test results:
Checking system properties:
Igor 64bit: 8.05, 37456
Windows 10: True
ASLR: True (Very Bad)

Checking known defines:
DEBUGGING_ENABLED: No
EVIL_KITTEN_EATING_MODE: No
BACKGROUND_TASK_DEBUGGING: No
THREADING_DISABLED: No

Checking base installation:
Mies version info: Valid "Release_2.4_20211216-284-g22a10414..." (Nice!)
ITC XOP: Found version 1.0.2.0 (Nice!)
JSON XOP: Found version 1.0.0.1 (Nice!)
VDT2 XOP: Found version 2.2.1.0 (Nice!)
HDF5 XOP: Found version 2.0.2.0 (Nice!)
Axon Telegraph XOP: Found version 3.0.0.0 (Nice!)
Multi Clamp Commander XOP: Found version 2.0.0.0 (Nice!)
ZeroMQ XOP: Found version 1.0.0.1 (Nice!)
JSON XOP: Present in the right version (version-753-g902d43f) (Nice!)
Results: 9 checks, 1 number of errors

Checking extended installation:
NI-DAQ MX XOP: Found version 1.1.5.0 and hash is ok (Nice!)
Results: 1 checks, 0 number of errors
```

**Comment by t-b** [comment]
@timheistek Thanks for the report. Can you post the error message?
I suspect this is due to the SamplingFrequency check.

**Comment by timheistek** [comment]
The protocol stops with the message "failure as we ran out of sweeps". After that I get the following error:
 
 !!! Assertion FAILED !!!
  Message: "The control check_Settings_MD in the panel PXI1Slot4 is disabled. The control state cannot be changed when disabled."
  Please provide the following information if you contact the MIES developers:
  ################################
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Stacktrace:
DAP_ButtonProc_TPDAQ(...)#L4280 [MIES_DAEphys.ipf]
DAP_CheckSettings(...)#L2213 [MIES_DAEphys.ipf]
AS_HandlePossibleTransition(...)#L93 [MIES_AcquisitionStateHandling.ipf]
AFM_CallAnalysisFunctions(...)#L135 [MIES_AnalysisFunctionManagement.ipf]
PSQ_DAScale(...)#L1733 [MIES_AnalysisFunctions_PatchSeq.ipf]
PGC_SetAndActivateControl(...)#L192 [MIES_ProgrammaticGUIControl.ipf]
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Time: 2022-03-01T14:45:58+01:00
  Locked device: [PXI1Slot4]
  Current sweep: [2]
  DAQ: [DAQ_NOT_RUNNING]
  Testpulse: [TEST_PULSE_NOT_RUNNING]
  Experiment: MIES_2.4error (Packed)
  Igor Pro version: 8.0.5.1 (37456)
  MIES version:
  Release_2.4_20211216-284-g22a10414
Date and time of last commit: 2022-02-25T09:08:15+01:00
Submodule status:
 f3493461480eaafa97939940693ed693860048a6 Packages/IPNWB (heads/main)
 56f1da31d786a593892280c2d2b2b1190def0fb5 Packages/doc/doxygen-filter-ipf (heads/main)
 5359bdbaad31451d6ebb9c88cca09d48357a41bb Packages/unit-testing (heads/main)
  ################################
  The analysis function PSQ_DAScale aborted with error "", this is dangerous and must *not* happen!
  PXI1Slot4: Pre DAQ analysis function requested an abort

**Comment by timheistek** [comment]
After the fix I don't get any error messages. However recording still stops after the first sweep with 'failure as we ran out of sweeps. The sampling frequency didn't match the "samplingfrequency" analysis parameter'. Also when turning on the testpulse afterwards the autobias function brings the holding current and voltage to really high values similar as the issue with the PSQ rheobase function.

**Comment by t-b** [comment]
> The sampling frequency didn't match the "samplingfrequency" analysis parameter'.

You have to set the analysis parameter "SamplingFrequency" in the WaveBuilder to the expected value. The stored values are for NI hardware.

Recipe:
- Open Wavebuilder
- Load stimset
- Click "Open parameters panel"
- Select `SamplingFrequency` in the lower subwindow
- Set the expected sampling frequency in kHz
- Click "Add"
- Click "Save set"

Does that work?

> Also when turning on the testpulse afterwards the autobias function brings the holding current and voltage to really high values similar as the issue with the PSQ rheobase function.

This is probably solved in #1301. But I need to finish that PR first.

**Comment by timheistek** [comment]
Thanks, this solves the issue with the sample frequency and PSQ_DAScale function woks properly. There is still the issue with the PSQ rheobase function.

**Comment by t-b** [comment]
@timheistek Thanks for testing. I found something already and ping you once I have finalized the fix.
