### ISSUE TITLE
Analysis function: TrueRestingMembranePotential

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#1296]
Name: TrueRestingMembranePotential 
ShortName: Vm (preferred casing, all uper case is fine as well)

Objective: Capture a current clamp sweep where the stimulus is completey zero except the inserted TP and about a second long.

Measure mean potential of stimset (without inserted TP), document in LBN,

One passing sweeps.

MID_SWEEP_EVENT:

2 baseline selection user epochs:
- 0: Short and long RMS, record average voltage of baseline region
- 1: record average voltage of baseline region

baseline QC consists of short and long RMS, and that both average voltages are within the given boundaries. Document both average voltages and difference.

PRE_SET_EVENT:
- No autobias, no holding potential
- Bridge balance and capacitance compensation should be on
- Only one active headstage
- Current clamp
- No TTL
- No oodDAQ/dDAQ

Add baseline selection epochs:
- epoch 0: baseline 0
- epoch 1: something else
- epoch 2: baseline 1

- Check that amplitude of epochs are zero

POST_SWEEP_EVENT:
- sweep QC: baseline QC and sampling interval QC and spike QC (passing is no spikes)

Check for spikes (everywhere) and add LBN entries.
If we have spikes:
- Exclude spiking region from measured mean potential of stimset
- Turn on autobias
- Set target V of autobias to measured mean potential + user offset

POST_SET_EVENT:
- If set QC passes: Set target V of autobias to that measured value, turn on autobias
- Publish: set QC and measured voltage

POST_DAQ_EVENT:
- Set next starting and ending stimset if set QC passes and both are given. Turn on indexing if ending stimset is given.

Analysis parameters:
- NextStimSetName:string (optional)
- NextIndexingEndStimSetName:string (optional)
- Two for absolute and relative average voltage difference like for DAScale
- BaselineRMSShortThreshold:variable
- BaselineRMSLongThreshold:variable
- [SamplingFrequency:variable],[SamplingMultiplier:variable]
- NumberOfFailedSweeps:variable
- BaselineChunkLength:variable
- UserOffsetTargetVAutobias:variable
- FailedLevel:variable (for spike check)

**Comment by t-b** [comment]
Questions:
- Are we caring about the difference of both baseline epochs average value? Or the difference to a third reference value?
- What does "Two for absolute and relative average voltage difference like for DAScale" mean?

**Comment by t-b** [comment]
Questions:
```
Check for spikes (everywhere) and add LBN entries.
If we have spikes:
```

Does having spikes imply that we stop the sweep early and do the autobias stuff in POST_SWEEP_EVENT before trying again?

**Comment by timjarsky** [comment]
@t-b For this analysis function if spikes are detected, collect the entire sweep. Adjust autobias after sweep is complete. 

Yes, make the time buffer around spikes an analysis param.

Do not jump to end with spikes.
