### ISSUE TITLE
USER_Pipette in Bath pipette resistance incorrect units

### ISSUE THREAD

**Issue by ru57y34nn** [AllenInstitute/MIES#1315]
MIES version: Release_2.4_20211216-327-g616735c6

The "USER_Pipette in Bath pipette resistance" appears to be in units of milliohms rather than ohms. I tested this with a model cell in the "Bath" configuration which simulates a 10 MOhm pipette in the bath solution and when I ran the "EXTPINBATH180424_DA_0" sweep I noticed that the value being returned for "USER_Pipette in Bath pipette resistance" was about 10,000,000,000 Ohms, which would be 10 GOhms. While I still had the model cell in the same "Bath" configuration I also ran the EXTPCllATT180424_DA_0 sweep which uses "USER_Seal evaluation seal resistance max" and that value was returning a correct value of about 10,000,000 Ohms or about 10 MOhms

This image shows the published output of both the "USER_Seal evaluation seal resistance max" (top circle) and the "USER_Pipette in Bath pipette resistance" (bottom circle) and although they should both be around 10,000,000 Ohms (10 MOhms), the "USER_Pipette in Bath pipette resistance" is 10,000,000,000 Ohms (10 GOhms), and they should both be returning roughly the same value.
![labnotebook_inbath_resistances_igorrouter_LI](https://user-images.githubusercontent.com/26012971/159595408-b436cb6a-5b30-4216-a796-e78fb512e199.jpg)

This image shows the lab notebook entry for the "USER_Pipette in Bath pipette resistance". I placed a cursor over the last data point (top circle) and the resistance value is 1.0537 x 10 ^10 (10.5 billion Ohms, or about 10.5 GOhms)
![labnotebook_inbath_resistances_LI](https://user-images.githubusercontent.com/26012971/159595846-28b796aa-4215-47ac-8e8e-2ea0e47e51d0.jpg)

I also have the pxp file that I was using for testing that I will upload to the FTP server (2022_03_22_pipette_resistance_units.pxp)

Please let me know if you have any questions or need any additional information about the issue.

**Comment by t-b** [comment]
Thanks for the report, I'll look into it.
