### ISSUE TITLE
Make Analysis functions configurable to respect Bath Temperature min/max range

### ISSUE THREAD

**Issue by ru57y34nn** [AllenInstitute/MIES#1327]
We are using the Asynchronous channels to record our set and bath temperatures and to trigger the alarm when the bath temperature is out of range (see image below), but we would like to add additional parameters to the analysis functions so that they can be configured to respect the min and max bath temperature and to fail sweeps where the bath temperature is outside of the specified min and max. 
![MIES_Async_Temps](https://user-images.githubusercontent.com/26012971/162089878-257196d7-3643-4cf8-9e9f-a31f3221d8cd.PNG)

There should be a parameter to turn this feature on or off as well as a parameter that specifies which Async channel(s) are being used for temperature monitoring. The following image is an example that I mocked up to illustrate what that might look like in the parameters panel for the PSQ_DAScale analysis function.
![MIES_parameters_panel](https://user-images.githubusercontent.com/26012971/162091593-34b11405-b0e6-46b6-832e-ded93df1f46d.PNG)

Please let me know if you have any questions about this request, thanks!

**Comment by t-b** [comment]
Sounds doable.

Some questions:
- Should that be supported for all analysis functions? We have
```
/// - PSQ_PipetteInBath
/// - PSQ_DaScale
/// - PSQ_SquarePulse
/// - PSQ_Rheobase
/// - PSQ_Ramp
/// - PSQ_Chirp
/// - PSQ_SealEvaluation
```

for IVSCC.
- Should the parameters be optional or required? If optional what is the default for `EnforceTemp`? Probably `false`?
- If multiple AD channels are given for querying the temperatures, should I `or` the result of all of them or `and` it? I.e. have all to pass or only one?
- Any requirement when during the analysis function run I should check that? See also https://alleninstitute.github.io/MIES/file/_m_i_e_s___analysis_functions_8ipf.html for the available states. If you only need it once and therefore assume that it is constant for the run of the analysis function I would suggest `POST_SWEEP_EVENT`.

**Comment by t-b** [comment]
@timjarsky 
- Is that release 2.5 material?
- Should that work together with "Auto repeat last sweep until alarm state is cleared" checked?

**Comment by timjarsky** [comment]
@t-b it would be great to get it into 2.5, but it depends on how long it will take. I'm leaning towards sticking with our original plan as I expect another release soon.

I think it should work with "Auto-repeat last sweep until alarm state is cleared" out of the box; the analysis function checks the alarm state in pre or post sweep. check = reads the lab notebook. [do we write the asyn alarm into the notebook?]

yes, support all PSQ analysis functions. 

yes, all have to pass.

**Comment by t-b** [comment]
- Do in POST_SWEEP_EVENT
- analysis parameters are required
- Check that alarm is enabled
- Drop EnforceTemp as we always want to check
- Use more generic name for analysis parameter
- store alarm state in ED_createAsyncWaveNoteTags
- stop (jumpt to end of DAQ) on async QC failure
-  "Auto-repeat last sweep until alarm state is cleared" must be unchecked (can that every work with analysis functions?)

**Comment by timjarsky** [comment]
@t-b I want to modify the analysis function specs I provided previously. Instead of failing the stimset when the temp is out of range, fail the sweep. The stimset will only fail if the number of failed sweeps is exceeded. I hope I got this change in specs before you started the relevant work.

**Comment by t-b** [comment]
IN addition:
- Publish stopping/starting TP and DAQ unconditionally, ignore TP during ITI and don't send a message.
