### ISSUE TITLE
MCC configuration issue requires Windows user wiping

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#1357]
From https://aiephys.slack.com/archives/G01CZ45S95X/p1651614478318899:

> attached is an image of an error that we occasionally encounter when configuring MIES. The only way that we have found to fix this issue so far is to wipe the Windows user account settings and then when they login and start up MIES the next time the issue goes away.  I uploaded a file that contains this message to your FTP and it is called mies_gain_config_issue_2022_05_03_140008. Just wanted to see if you could take a look and see if there is anything that you can find on your end that might solve this. Let me know if you have any questions or if I should open a MIES issue for this, thanks.

![grafik](https://user-images.githubusercontent.com/1185677/167029649-539489c7-0770-4879-ac72-2b74958eac59.png)

**Comment by ru57y34nn** [comment]
@t-b we have found that resetting the MultiClamp Commander to default settings fixes this issue. Sorry we hadn't figured out this solution earlier, but you should be able to close this issue now as this is no longer an issue for us and is related to the MCC and not MIES or Windows. Thanks

**Comment by t-b** [comment]
- [ ] We will prevent DAQ with a gain of zero, and hint the user that the MCC application might need some special treatment.
