### ISSUE TITLE
Dashboard bug?!

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#1421]
![grafik](https://user-images.githubusercontent.com/1185677/175778750-24f579db-6e6b-4e47-9c97-3200b2cfc992.png)

From https://aiephys.slack.com/archives/G01CZ45S95X/p1656019962804809:

> I have two pxp files from yesterday that show the same issue, I will upload them to your FTP server (2022_06_22_104125.pxp, and 2022_06_22_123943). The first thing we noticed was that MIES was just running a single sweep per stimset and then moving to the next stimset and leaving the Result in the dashboard as "Sweep not yet finished". In the attached image you can see the Lab Notebook Entries at the bottom of the data browser show stimsets X1-X6 just running single sweeps and then moving to the next stimset while the results in the dashboard are all "Sweep not yet finished". Stopping and restarting acquisition seemed to get the stimulus sets running properly, but then I noticed that the number of sweeps in the Lab Notebook Entries did not match the number of sweeps indicated in the DataBrowser window (DataBrowser showing 77 sweeps and Lab Notebook Entries showing 48), as well, the names of the stimsets indicated for each sweep in the Lab Notebook Entries do not match the actual stimsets, and in the case of sweep 4 (shown here in the DataBrowser) I don't even recognize which stimset that is, it's not any of the ones that we have loaded, but in the Lab Notebook Entries it says "X5SP_Search_DA_0, which is not correct. Unfortunately we are still running MIES Release_2.5_20220415-136-g1f30f36dd on the rigs and won't be able to update to the more up-to-date MIES 2.5 until next week, so just let me know if this bug has already been fixed in that release.

**Comment by t-b** [comment]
@ru57y34nn

After some travelling I finally found time to look into that:

> The first thing we noticed was that MIES was just running a single sweep per stimset and then moving to the next stimset and leaving the Result in the dashboard as "Sweep not yet finished"

It is difficult now to find out why that happened. It looks like quite some assertions were triggered. And an assertion being triggered means an unrecoverable error happened. As you say retrying fixed it, this is weider.

> I noticed that the number of sweeps in the Lab Notebook Entries did not match the number of sweeps indicated in the DataBrowser window (DataBrowser showing 77 sweeps and Lab Notebook Entries showing 48),

This is an update issue of textual labnotebook entries and now tracked in https://github.com/AllenInstitute/MIES/issues/1425.

> the names of the stimsets indicated for each sweep in the Lab Notebook Entries do not match the actual stimsets, and in the case of sweep 4 (shown here in the DataBrowser) I don't even recognize which stimset that is, it's not any of the ones that we have loaded, but in the Lab Notebook Entries it says "X5SP_Search_DA_0, which is not correct. 

Looking at sweep 4 from 2022_06_22_104125.pxp I would say the reasons this looks odd are:
- 45% baseline which makes the TP very long
- A negative DAScale which flips the stimset

Does that make sense? If you enable "Visualize epochs" you should also see where the stimset starts and end.

**Comment by ru57y34nn** [comment]
@t-b we ran into another instance of this issue. I will upload the relevant experiment file for your reference (QN22.26.028.14.05.01.pxp). The primary issue here again is that MIES is just running a single sweep per stimset and leaving the result in the dashboard as "sweep not yet finished". After stopping and restarting acquisition a few times MIES finally started running the full stimsets.

To address your last question from the previous example:
> Looking at sweep 4 from 2022_06_22_104125.pxp I would say the reasons this looks odd are:

    45% baseline which makes the TP very long
    A negative DAScale which flips the stimset

Does that make sense? If you enable "Visualize epochs" you should also see where the stimset starts and end.

Sweep 4 is labeled as "X5SP_Search" which shouldn't even have a test pulse epoch (this has occurred again in the current example as well), and I don't understand why the DAScale would be negative as we don't set this, we just index through the stimsets and MIES should be determining the DAScale, but it should never set a negative DAScale for "X5SP_Search"

Let me know if you have additional questions, thanks

**Comment by t-b** [comment]
So this looks really odd.

@ru57y34nn Is that reproducible on your end? If yes can you redo it with debugging enabled?

For enabling debugging:
- Open the debug panel from `MIES Panels->Advanced->Panels->Open debug panel`
- Enable debugging on the top left checkbox
- Select the files "MIES_AnalysisFunctions_PatchSeq.ipf " and  "MIES_RepeatedAcquisition.ipf"
- Start acquisition

Then upload the file and I can have a look.

Some investigation notes:

Starting with Sweep 4 indexing is turned on. It is off before.

The **X1PS_SubThres_DA_0** stimset, which uses PSQ_DAScale in "Sub" mode, only
acquires 1 sweep. This sweep has failed sweep QC LBN entry. It does **not**
have a Set QC entry which means that POST_SET_EVENT was somehow not called for
PSQ_DaScale.

Question:
- Why does the stimset not proceed but skip to the next stimset?

The next stimset **X2LP_Search_DA_0** starts, but it's PRE_SET_EVENT is not
executed, after that the POST_SWEEP_EVENT complains with "unknown stepsize".
And after this point things go really south.

**Comment by t-b** [comment]
If you think this is easier/quicker resolved in a live debugging session, we can do that as well.

**Comment by t-b** [comment]
@ru57y34nn I think I can reproduce. So you don't need to take action for now.

**Comment by t-b** [comment]
@ru57y34nn I've fixed a minor dashboard bug in https://github.com/AllenInstitute/MIES/pull/1454.

Unfortunately I was wrong in https://github.com/AllenInstitute/MIES/issues/1421#issuecomment-1208261089 and I can reproduce the issue.

**Comment by t-b** [comment]
The bug is real, but very rare according to what Tim told me. So I'm closing for now.
