### ISSUE TITLE
Experiment config no longer functions in master

### ISSUE THREAD

**Issue by timjarsky** [AllenInstitute/MIES#143]
Experiment config fails at end; "  (ITC1600_Dev_2) Please activate at least one headstage"

AD and DA channels are checked but HS channels are unchecked after configuration. TP fails to initialize because there are no active headstages.

**Comment by t-b** [comment]
@timjarsky Thanks. This should be fixed in PR 1069.

**Comment by t-b** [comment]
Thanks for reopening. I'll add a test case for the configuration so that we can be sure that it works.

**Comment by t-b** [comment]
Test PR was added.
