### ISSUE TITLE
Checks before DAQ without amplifier

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#1441]
@timjarsky  So I did some digging as you said that the Hardware->"DAC Channel and Device Assocations"  works equally well without amplifier.

And I found fae2379a (DAP_CheckHeadStage: Add checks for DA/AD gain and unit, 2016-05-11) which only does the equality checks if we have an amplifier connected.

So I would now change that we don't require an amplifier for these checks?

**Comment by timjarsky** [comment]
@t-b yes, that makes sense
