### ISSUE TITLE
PSQ_AccessResistanceSmoke : Returned access resistance looks odd

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#1444]
From https://aiephys.slack.com/archives/G01CZ45S95X/p1659473221870449:

> I was checking the output of our break in sweep (EXTPBREAKN180424) which uses the PSQ_AccessResistanceSmoke analysis function and it appears that there is something wrong with the value for the access resistance that is being returned. In the attached image I have circled in red the access resistance value that shows up in the MIES test pulse window (6.6 MOhms) and the value that is being returned from PSQ_AccessResistanceSmoke (9667673.716012085 Ohms or 9.7 MOhms),I will also upload the pxp file to your FTP (2022_08_02_104637.pxp) for your reference. I am not sure why these values would be different but can you take a look when you get a chance? Also, if you prefer I can open an issue on GitHub for this, just let me know, thanks.

![grafik](https://user-images.githubusercontent.com/1185677/182597525-5e39658a-a185-419f-a80d-5fb264374b90.png)

**Comment by t-b** [comment]
Found again:

> I have uploaded QN22.26.030.14.07B.03.pxp to your FTP, which is an experiment that was ran with MIES-Release_2.6_20220606-34-g9d4f798a. The attached image was captured by the rig operator at the time and we can see that the Access resistance value displayed next to the test pulse says 18 MOhms but the value received by the workflow is over 20 MOhms, which is also the value shown for each sweep in the labnotebook entries. They tried running the BreakIn sweep twice, each time running 3 attempts and they all failed due to Access Resistance exceeding 20 MOhms, but all the while the value displayed next to the test pulse was stable at 18 MOhms. Thanks for looking into this again and let me know if you need any additional information.

![grafik](https://user-images.githubusercontent.com/1185677/186903935-2c11bbfd-e746-43aa-af94-97b118a4bd29.png)

**Comment by timjarsky** [comment]
@t-b my guess is that the TP inst in SF is using the peak value, not the peak minus baseline.
