### ISSUE TITLE
USER_Seal evaluation Set QC failing regardless of seal resistance value

### ISSUE THREAD

**Issue by ru57y34nn** [AllenInstitute/MIES#1458]
During pre-production testing with MIES Release_2.6_20220606-29-g8713b668 I have been consistently getting the result 0.0 returned from USER_Seal evaluation Set QC regardless of the value returned from USER_Seal evaluation seal resistance max (whether it is > 1 GOhm or < 1 GOhm). I tested this with a model cell in both high and low resistance configurations and am getting the same failing result from USER_Seal evaluation Set QC in both cases. The stimset wave name that has these analysis parameters associated with it is called EXTPCllATT180424_DA_0.

I also tested this with a previous version of MIES 2.5 and can confirm that it is returning the correct QC value based on the max resistance (> 1 GOhm returns 1.0 (passing) and < 1 GOhm returns 0.0 (failing)).

I have an example pxp file from my testing session with MIES 2.6 which is too large to upload here so I will upload it to your FTP; filename: 2022_08_09_140612.pxp

**Comment by t-b** [comment]
Thanks for the report and the example file.

I've plotted some more labnotebook entries

![image](https://user-images.githubusercontent.com/1185677/183903182-8fb001d9-fc4e-4b2d-aa89-a76ac6fe53a1.png)

and as "BL QC" is always 0/false for PSQ_SealEvaluation, the sweep QC is false and set QC is false as well. Does that make sense?

PS: If you hover with the mouse of the Result column in the Dashboard you should see a detailed failure message for each sweep.
PPS: There is an undocumented function to plot *all* labnotebook values of a analysis function, e.g. `LBV_PlotAllAnalysisFunctionLBNKeys("DB_ITC18USB_DeV_0", PSQ_SEAL_EVALUATION)` does plot all from PSQ_SealEvaluation. I can add that to the GUI if you think this is useful.

**Comment by ru57y34nn** [comment]
Thanks for the info Thomas, I see now that the BaselineRMSShortThreshold is the reason for the failure. I thought I had adjusted the Baseline RMS short and long thresholds but I guess I forgot to save them. I'll go ahead and close this issue as all I need to do is adjust the RMS thresholds, thanks.
