### ISSUE TITLE
Make stopping/restarting the testpulse faster

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#146]
There are few cases where we need to stop the TP, do something and then want to restart it.
Currently this involves the full check and labnotebook storage cycle.
Skipping both should make it much faster to stop and restart TP.

**Comment by t-b** [comment]
> when you are looking into the amp call speedup (Red.: this issue) would you also poke around and see what's happening when zero and select all amp is checked?

**Comment by t-b** [comment]
@timjarsky What do you mean be "zero" in this context? I did poke into IZero and found a bug, but that is probably not what you asked for or?

**Comment by timjarsky** [comment]
@t-b zero = Auto Pipette Offset. We do a lot of clamp mode switching here and I'm concerned we may be over documenting the state of the amp.

**Comment by t-b** [comment]
@timjarsky Thanks for the explanation. With the new fast mode we are not documenting the amp state anymore, but wrt to send to amp I found another way to speed it up. See the PR for details.
