### ISSUE TITLE
60 hz quantification

### ISSUE THREAD

**Issue by timjarsky** [AllenInstitute/MIES#1484]
Create a formula to quantify 60hz noise in data. Probably something like FFT to generate power spectrum, return amp @ 60hz expressed relative to baseline noise. Unit could be dB or %.

**Comment by timjarsky** [comment]
I'm uncertain how best to determine the baseline noise region in the power spectrum.

**Comment by t-b** [comment]
Use cases:
- Look at power spectrum
- Analyze features from power spectrum, look at multiple sweeps and compare the noise levels (the multiple sweeps should not be averaged)

Sample data: Any current clamp/voltage clamp sweep with baseline

FFT should use padding for speed reasons.

Start with plain power spectrum and see if that is enough already.

Operation:
- `powerspectrum(data(...))`
- choosable y units: %, db, real units via inverse fft (??!)

**Comment by t-b** [comment]
- Reuse `DoFFT`
