### ISSUE TITLE
Add generic solution for plotting millions of points quickly

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#150]
- Need to resample data when the original data changes (Dependencies and WaveModCount?)
- Resample options, the same than for oscilloscope
- Users should be able to add this method to any MIES graph, when we should add some popupmenu/button, replace the waves etc.
- Calling resample only on demand to keep it quick?

**Comment by timjarsky** [comment]
@t-b Before we get too far along with this PR, I think we should chat with WM. For now, I think we should downsample data for scope viewing (using the max/min method).

**Comment by t-b** [comment]
Look into example code from Adam.

**Comment by t-b** [comment]
Closing for now as too much effort.
