### ISSUE TITLE
Intermediate plotting option

### ISSUE THREAD

**Issue by timjarsky** [AllenInstitute/MIES#1507]

**Comment by timjarsky** [comment]
A new general feature for sweep formula.

A formula or flag (I'm not sure what makes the most sense) for a user formula that creates plots for all formula inside the user formula

E.g.,
```
incrementalplot(
max(
data(
E0,
select(channels(AD0),sweeps(),all, ic)
)
)
)
```
would be equivalent to:
```
data(
E0,
select(channels(AD0),sweeps(),all, ic)
)

and

max(
data(
E0,
select(channels(AD0),sweeps(),all, ic)
)
)
```

The flag version might look like:

```
max(
data(
E0,
select(channels(AD0),sweeps(),all, ic)
)
)/increment_plot
```

**Comment by timjarsky** [comment]
One more possibility is to include a checkbox in the SF formula window to plot intermediates. The downside of this approach is that it wouldn't be formula specific, however, in most cases, it would be the most efficient way to plot intermediates for the user.

**Comment by MichaelHuth** [comment]
I think an approach for that would be to gather the data after each operation call at the end of SF_FormulaExecutor in a wave ref wave. The Plotter has to get this wave then and change it such that each element is added as another subwindow, except the last one.

**Comment by t-b** [comment]
An operation should be able to also add by itself more intermediate steps. This would for example allow the user to see the data and fit results for powerspectrum and TP with exponential fits (#1247)

**Comment by timjarsky** [comment]
Closing. Not a high priority.
