### ISSUE TITLE
SF: Support meta data from operation to use custom marker symbol in plotter

### ISSUE THREAD

**Issue by MichaelHuth** [AllenInstitute/MIES#1508]
For some single data point results from operations like powerspectrum we could use an additional information transported through a meta data field that allows the plotter to change the marker shape in the plot.
For example if a the powerspectrum determines a ratio and the fit failed.

**Comment by t-b** [comment]
This should tie in properly with #1525 when/if tackled.

**Comment by t-b** [comment]
We now have `SF_META_MOD_MARKER` for exactly that.
