### ISSUE TITLE
Retrieve data browser from SF plot

### ISSUE THREAD

**Issue by timjarsky** [AllenInstitute/MIES#1526]
With multiple data browsers open, it can be challenging to keep track of which data browser is linked with the sweep formula plot window.

Options: 
1) add a button to the SF plot to bring the DB to the front
2) link SF plot to DB window - this would need to be tied to buttons that allow the user to shrink the various panels of the DB

**Comment by t-b** [comment]
Does the "To Front" button in the SF tab not help?

Regarding 1:
- While it is possible to add buttons to graphs, we rarely do that.

Regarding 2:
- One can close all external subwindows of the databrowser, just press "x" at the top right corners and the used screen space gets much smaller.
- If you mean by "link" to have the SF window as external subwindow, I don't think this will look good.

Would having a better title of the SF window help? Or a context menu for the SF window?

**Comment by timjarsky** [comment]
>Does the "To Front" button in the SF tab not help?

No, this is a SF plot window to DB linking issue, not a DB to SF plot window linking issue.

"One can close all external subwindows of the databrowser, just press "x" at the top right corners and the used screen space gets much smaller."

There isn't a way that I know of to restore the subwindow are pressing "x". Somewhat related, after closing the lab notebook subwindow, there is no way to see what file/device the DB is displaying.

Naming would help, but the user still needs to sift through the list of DBs to find the one with the correct name.
