### ISSUE TITLE
Add new suprathreshold mode to PSQ_DAScale; spike frequency monitor [Adaptive Threshold]

### ISSUE THREAD

**Issue by timjarsky** [AllenInstitute/MIES#1532]
The existing suprathreshold mode gives fixed, user-defined, current injection values above the previously determined rheobase (PSQ_Rheobase). I want to add a suprathreshold mode that monitors spike frequency and continues to increase the injected current until the spike frequency delta falls below a user-defined parameter. 

Typically, cell spiking responses rise with current injection, but eventually increasing the amount of injected current doesn't change the spike frequency. The goal is to have the analysis function stop injecting current at or near this threshold. 

Example I-F plot showing the plateau in spike frequency with increasing current injection (The experimental conditions are not important here).
<img width="436" alt="image" src="https://user-images.githubusercontent.com/5693697/198842293-1d93fb7d-132e-4d72-b175-81eb8e937ae8.png">

**Comment by timjarsky** [comment]
Goal:
- Don't push the cell to too high currents
- Save time by not acquiring too much data

- Measure the slope for small (<100nA) currents
- Only acquire data until  the slope is X percent smaller

Algorithm A:

New mode "SigmoidFitSupraThreshold" derived from the old suprathreshold

- Acquire data with user-defined currents
- Fit with sigmoid, estimate maximum current
- Calculate new current with Z
- Once with have X results of the maximum current estimation which are Y close together we are done

Reject outcomes that have results outside the boundary conditions (max frequency 1000Hz, ...)

New  analysis parameter:
- X
- Y
- Z: JUmp factor, based on the difference between the last true frequency and predicted maximum frequency.

Only do B if A does not work that well.

Algorithm B:
- Fit the first three points with a line to get the initial slope. These are user-defined as done now.
- Acquire more points
- Always take the last three points and compare them with the maximum slope encountered
- Stop once the current slope is X percent smaller than the initial slope

New analysis parameter:
- SlopePercentage
- NumPointsForLinefit

Keep suprathreshold mode, but create a new mode "AdaptiveSupraThreshold" from it

- [ ] TJ provides real data

**Comment by timjarsky** [comment]
Challenging partial F-I curves the analysis function will need to manage:
Linear:
![image](https://user-images.githubusercontent.com/5693697/199114054-ce307f63-9a73-49ba-bd90-4c6b5c3ab758.png)

negative/flat
![image](https://user-images.githubusercontent.com/5693697/199114209-262e1f1d-6e97-4b74-a921-4c290f97ebd6.png)

**Comment by timjarsky** [comment]
- When building the stim set in the wave builder, we may want to shorten the length of the pulse to speed up acquisition and minimize the chance of injecting too much current. Short pulses with a lot of spikes could be used to assess AHP.

**Comment by t-b** [comment]
AHP is ???

**Comment by timjarsky** [comment]
@t-b AHP: afterhyperpolarization. We may add a SF to quantify it.

**Comment by timjarsky** [comment]
@t-b f,m,s = fast, medium, slow
![image](https://user-images.githubusercontent.com/5693697/199128005-3ff6202e-ecba-41bf-a7d8-57f28d20bbc8.png)

**Comment by t-b** [comment]
Q: Assume we have still measurements to do from overshoot correction in earlier sweeps, but would now have a fI-slope small enough relative to the maximum slope so that the set would pass. Should we now finish early or finish the list of overshoot correction DAScale values?
