### ISSUE TITLE
Wavebuilder Sin Chirp Infinite Loop

### ISSUE THREAD

**Issue by timjarsky** [AllenInstitute/MIES#1536]
When incrementing the End Freq (using control SetVar_WaveBuilder_P24) of a chirp sin wave in the WB, MIES gets caught in an infinite loop. 
![image](https://user-images.githubusercontent.com/5693697/199060102-5bea33a1-33b1-4ce8-8e5a-c5a9a18c8f77.png)

```
  BUG WB_TrigCalculateInflectionPoints(...)#L1408: xzero must be finite
```

**Comment by t-b** [comment]
Thanks for the report. I've got a solution which seems to work. Now I just need to know why that works...
