### ISSUE TITLE
Suspicous test assertions

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#1539]
$ git grep --show-function "\bWARN("

```diff
Packages/tests/Basic/UTF_AsynFrameworkTest.ipf=static Function TASYNC_RunOrderless()
Packages/tests/Basic/UTF_AsynFrameworkTest.ipf:              WARN(1)
Packages/tests/Basic/UTF_AsynFrameworkTest.ipf=static Function TASYNC_OrderlessDirectStop()
Packages/tests/Basic/UTF_AsynFrameworkTest.ipf:              WARN(1)
```

WARN(1) does not make sense as this is bascially the same as PASS().

**Comment by MichaelHuth** [comment]
The idea was to check if the orderless execution returns an unordered result. However there is still a slim chance that the results are returned "in order" even when the requested order is "orderless".

**Comment by t-b** [comment]
@MichaelHuth That makes sense, but in this case you would wanted to use `WARN(0)` or?
