### ISSUE TITLE
Overlay sweeps offset setting disrupts PA plot organization

### ISSUE THREAD

**Issue by timjarsky** [AllenInstitute/MIES#155]
Using the offset and step feature of OVS disrupts the organization of the PA plot (spikes are no longer on the diagonal). 

![image](https://user-images.githubusercontent.com/5693697/56444758-e9ed8600-62ae-11e9-8505-549bafcd1912.png)

**Comment by t-b** [comment]
Thanks, this is tracked as part of PR #1110 (Mk/pulse averaging/time alignment).
