### ISSUE TITLE
Headstage removal of the last headstage with OVS results in buggy vertical axis layout

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#156]

**Comment by t-b** [comment]
This will also be solved as part of the Databrowser speedup.

**Comment by timjarsky** [comment]
@t-b it's great to see this issue resolved. Thank you!

**Comment by t-b** [comment]
@timjarsky Sure! I did not really had resolving this issue as goal but if I can solve it on the way for free, why not.
