### ISSUE TITLE
Move from bamboo to github actions

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#1563]
- [x] Install runners on ITC/NI hardware machines and the VM (TB)
- [x] Ask Tim for admin access to ITC machine for runner installation (admin powershell)
- [x] Label them correctly (TB)
- [x] Ask central IT to add a new github runner (docker is sufficient, concurrency 5) to their openstack instance
- [x] Try it out
- [x] Copy IP binary folder to something versioned (`r39935`) on all three instances
- [x] ~~Think about how we want to organize our docker images used in CI. Separate repo and push to ghcr.io? Right now we are always building them from scratch which is a bit wasteful.~~
- [x] FTP account for storage of artefacts (TB)
- [x] GH action runners fail with hardware tests (TB)

Add runners with labels, see [here](https://docs.github.com/en/actions/hosting-your-own-runners/using-labels-with-self-hosted-runners):
- [x] self-hosted, Windows, IgorPro, NI
- [x] self-hosted, Windows, Certificate
- [x] self-hosted, Windows, IgorPro, ITC
- [x] self-hosted, Windows, IgorPro
- [x] self-hosted, Linux, Docker

Jobs:
- [x] A: Build CI installer (Windows)
- [x] B: Build installer and release package and sign it (Windows, Certificate)
- [x] C: Linting (Linux, Docker)
- [x] CC: Build documentation (Linux, Docker)
- [x] D: Compilation test installer with hardware XOPs (IgorPro)
- [x] E: Compilation test installer without hardware XOPs (IgorPro)
- [x] F: Compilation test repository (IgorPro)
- [x] G: Testing Basics.pxp (IgorPro)
- [x] H: Testing PAPlot.pxp (IgorPro)
- [x] I: Hardware Testing: HardwareBasics.pxp (IgorPro, ITC)
- [x] J: Hardware Testing: HardwareBasics-NI.pxp (IgorPro, NI)
- [x] K: Hardware Testing: HardwareAnalysisFunctions.pxp (IgorPro, ITC)
- [x] L: Hardware Testing: HardwareAnalysisFunctions-NI.pxp (IgorPro, NI)
- [x] M: Validate NWBv2 files (Linux, Docker)
- [x] (Validate JUNIT XML files is being dropped)
- [x] O: Deploy documentation, installer and release package, main branch only (Linux, Docker)
- [x] P: Deploy installer and release package, latest release branch only (Linux, Docker)
- [x] Q: FTP Artifact upload

Job dependencies (draft):
- O/P needs M
- M needs I/J/K/L
- I/J/K/L needs D/E/F
- G/H needs D/E/F
- D/E/F needs A/B/C

Misc:
- Only official actions from github, see https://github.com/actions, are allowed to be used!
- Archive all artifacts to FTP, by branch name and commit
- It would be nice if we could have executing tests in IP as reusable workflow
- The jobs can be matrixed if useful and sensible
- No need to add github actions to the release/2.6 branch. Only prepare for next release.

Artefacts:
- A: CI installer
- B: Installer and release package
- CC: Documentation (compressed zip file)
- D-L: JUNIT, Igor Pro logfile, Cobertura(main branch only)
- I/K: NWBv2 files 

Current secrets:
- [x] EV certificate PIN
- [x] ~~SSH private key for gh-pages deploy and tagging latest main~~
- [x] ~~github API token for start/finished messages by @mies-bot~~
- [x] ~~release artifact upload~~
- [x] FTP credentials

IP versions:
We should also keep old IP versions on the CI machine. The CI setup should then reference the IP version/revision in the CI setup. This would allow us to run old versions from a year/two ago again on the CI machines.

Once this works:
- [x] Turn off bamboo plans (TB)
- [x] Stop bamboo agents on machines (TB)
- [x] Remove `.credentials` folders
- [x] Remove ssh deploy key from MIES repo
- [x] Remove API token for mies-bot user
- [x] Remove bamboo in code
```
git grep -iI bamboo ':/**/*.ipf'
../UTF_HardwareHelperFunctions.ipf:  expensive = GetEnvironmentVariableAsBoolean("BAMBOO_EXPENSIVE_CHECKS")
../UTF_HelperFunctions.ipf:  instru = GetEnvironmentVariableAsBoolean("BAMBOO_INSTRUMENT_TESTS")
../UTF_HelperFunctions.ipf:  return !cmpstr(GetEnvironmentVariable("bamboo_repository_git_branch"), "main")
../UTF_HelperFunctions.ipf:  return !IsEmpty(GetEnvironmentVariable("bamboo_repository_git_branch"))
```
- [x] Update CI documentation 
- [x] Turn off linux mint box (TB)
- [x] Tell Brian we don't need bamboo anymore (TB)

**Comment by t-b** [comment]
Bamboo will be out of service starting from 2/24/2024.

**Comment by t-b** [comment]
@timjarsky At https://github.com/byte-physics/x-to-nwb/actions/runs/4725634812?pr=10 you can see a failing github actions job. The artifacts, a JUNIT XML file, is there, but as it is zipped it is not that helpful. The job output itself is accessible though.
igortest now also includes a summary of failed tests at the end, so we should be good in figuring out why things failed.

**Comment by t-b** [comment]
Added a couple of more linux runners. We now have in total 5.

**Comment by t-b** [comment]
The disc location of the currently required IP9 version is: `C:\Program Files\WaveMetrics\Igor Pro 9 Folder\IgorBinaries_x64_r39935`. It probably makes sense to teach `tools/get-igor-path.sh` to accept a revision as well. As the goal is that we can run different PRs which test against different IP versions.

**Comment by Garados007** [comment]
@t-b There are some issues using scripts on windows runners:

[![grafik](https://user-images.githubusercontent.com/12125053/233410332-dac34a9b-60fe-42d3-8278-d3eb34fea580.png)](https://github.com/AllenInstitute/MIES/actions/runs/4755925778/jobs/8450756970) \
https://github.com/AllenInstitute/MIES/actions/runs/4755925778/jobs/8450756970

It seems like PowerShell needs to be configured to allow scripts. (Right now I am only echo-ing the script calls because I only want to check the basic setup and configurations)

**Comment by t-b** [comment]
@Garados007 Can you try to use bash as shell? See https://github.com/actions/runner/issues/1328#issuecomment-1067963331.

**Comment by Garados007** [comment]
Thanks. That worked.

**Comment by Garados007** [comment]
@t-b I need your help again with something. It's about the stored secrets for code signing:

[![grafik](https://user-images.githubusercontent.com/12125053/233790927-05b05c3e-7029-43a9-8867-773d53adf237.png)](https://github.com/AllenInstitute/MIES/actions/runs/4773162721/jobs/8486076783) \
https://github.com/AllenInstitute/MIES/actions/runs/4773162721/jobs/8486076783

I think the best solution would be to use [Github Secrets](https://docs.github.com/en/actions/security-guides/encrypted-secrets) but I have no access to it.

**Comment by Garados007** [comment]
There is also no git installed on your Linux runners:

![grafik](https://user-images.githubusercontent.com/12125053/233792013-57958e59-f89f-4920-8218-b94f4113e76b.png)

I can fix it temporally by adding `apt install git` as a step before checkout. But doing this for all Linux jobs doesn't seem to be the right way.

**Comment by t-b** [comment]
> There is also no git installed on your Linux runners:

I've installed git and ripgrep.

apt doesn't work because it is fedora (not something I set).

**Comment by t-b** [comment]
> I think the best solution would be to use [Github Secrets](https://docs.github.com/en/actions/security-guides/encrypted-secrets) but I have no access to it.

Stored as secret in GHA_MIES_CERTIFICATE_PIN.

**Comment by t-b** [comment]
I've seen that the linting job suceeds although ripgrep is not installed (https://github.com/AllenInstitute/MIES/actions/runs/4773927620/jobs/8487289707?pr=1656) I've created https://github.com/AllenInstitute/MIES/pull/1693 to bail out in that case. The linting job should also be run on *nix, that now has git and rg.

**Comment by t-b** [comment]
Regarding docker images, I thought that we can just reference `Dockerfile` files as described at https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#example-using-a-dockerfile-in-your-repository.

**Comment by Garados007** [comment]
> Regarding docker images, I thought that we can just reference Dockerfile files as described at https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#example-using-a-dockerfile-in-your-repository.

With this someone can create custom actions. But an action can only be used as a reusable piece of code for a single step inside a job of a workflow. My comment was about running all steps of a job inside the same docker container to create a predefined and common environment which isn't that easy to achieve.

But I am also okay installing the necessary tools on the host and will tell you if something is missing. This simplifies my part of this issue a lot.

**Comment by t-b** [comment]
> The issue is [...] uploading an image to Github is only available for actions that are triggered by a release

I'm not sure this is true. Looking at an example in the wild https://github.com/nlohmann/json-ci/blob/main/.github/workflows/publish_docker.yml shows that they use ghcr.io, but build and push on every PR. I don't suggest we do that here now as well, but just to be sure we are understanding it both in the same way.

**Comment by t-b** [comment]
Installed software on the linux runners:
- git, ripgrep, docker

Installed at:

```
[thomas.braun@aibs-ephys-ghrunner-1 local1]$ ls -1 -d actions-runner-*
actions-runner-1
actions-runner-2
actions-runner-3
actions-runner-4
actions-runner-5
[thomas.braun@aibs-ephys-ghrunner-1 local1]$ pwd

/local1
```

Started with the script -> [start-ghrunner.sh.txt](https://github.com/AllenInstitute/MIES/files/11356957/start-ghrunner.sh.txt)

**Comment by t-b** [comment]
> Can I get xmllint on the Windows runner? This can help to validate the produced JUnit files from the Igor test runs.

For what do you need that? The xml linting job is no more right? And if you do need it I can install it on *nix.

**Comment by Garados007** [comment]
> For what do you need that? The xml linting job is no more right?

I wanted to check if the produced JUnit files from the Igor experiment runs itself are correct XML. But this has been done in igortest itself so there is no real need for it. And calling them on *nix systems makes the setup more complex and I want to prevent that.

**Comment by Garados007** [comment]
I have eliminated most of the problems with the CI that prevented the pipeline from succeeding. But there are some issues that prevent the NI tests to succeed (see [test run](https://github.com/AllenInstitute/MIES/actions/runs/4895033524/jobs/8740099562)):

- `Basic.pxp` has some flaky tests which succeed in some iterations and fail in some iterations. You can checkout the three retries of the test run above. It seems that the issue is somewhere in ZeroMQ.
- The test case `SetControlsTesting#SC_SetControls1:NI` in `HardwareAnalysisFunctions-NI.pxp` fails every time with the following message:
    ```
    0 == 2: is false. Assertion "REQUIRE_EQUAL_VAR(DimSize(ampMCC, ROWS), 2)" failed in SetControlsTesting#SC_SetControls1?EnsureMCCIsOpen (UTF_HardwareHelperFunctions.ipf, line 45?1097)
    ```

I don't know if this only happens with the Github Actions runner or if it also exists with Bamboo. But I will remove the JUnit check for the time being to let the pipeline succeed.

**Comment by t-b** [comment]
Dooh! I think I missed a crucial fact. We are still using bamboo to run the CI tests on the other PRs and that does collide with the test runs here.

Both reported issues (zeromq and mcc amp) point also in that direction.

How should we proceed? Would it work for you if I disabled our bamboo plan later on and kept it disabled until monday night? Alternatives?

**Comment by Garados007** [comment]
Oh that's interesting. Didn't know that Bamboo is playing in the background. I think it's good if you pause Bamboo until Monday, as I intent to work on this issue over this weekend.

The alternative would be that I comment the conflicting steps but this won't show me if there are some problems with my current setup.

**Comment by t-b** [comment]
> Oh that's interesting. Didn't know that Bamboo is playing in the background. I think it's good if you pause Bamboo until Monday, as I intent to work on this issue over this weekend.

Good. The bamboo plans are now paused. And I check with remote desktop that IP is closed.

**Comment by t-b** [comment]
We don't yet have a runner for the ITC tag. I forgot to ask Tim to grant me admin access on the windows box to do that.

**Comment by t-b** [comment]
I suspect that the NI hardware tests fail due to some windows popup regarding the firewall. We need to coordinate a rerun so that I can verify that on rdp.

**Comment by Garados007** [comment]
I have a problem migrating a step in `bamboo-plan-build-release-latest.yml`:

https://github.com/AllenInstitute/MIES/blob/0cbfcbbfda6060c89304e3dd7722654329ac1e6a/bamboo-plan-build-release-latest.yml#L229-L230

Neither `run_unit_tests.sh` nor `RunAllTests.pxp` can be found in the repository. I suggest `run_unit_tests.sh` can be replaced with `tools/autorun-test.sh` but what should I use for `RunAllTests.pxp`? `Packages/tests/Basic/Basic.pxp`?

**Comment by t-b** [comment]
> I suggest run_unit_tests.sh can be replaced with tools/autorun-test.sh

Jeep.

> Packages/tests/Basic/Basic.pxp?

Yes! RunAllTests.pxp was the old name.

**Comment by t-b** [comment]
- I've reinstalled the windows runners. They now don't run as a system service anymore but as the regular user. This makes IP showup again during execution.
- I've installed a runner on the ITC box
- I've pushed FTP credentials to our private orga repo

**Comment by t-b** [comment]
I've added the following secrets:
- GHA_MIES_FTP_ARTEFACT_STORAGE_USER
- GHA_MIES_FTP_ARTEFACT_STORAGE_PWD

and the following variable:
- GHA_MIES_FTP_ARTEFACT_STORAGE_DNS

**Comment by Garados007** [comment]
@t-b 
> I've reinstalled the windows runners. They now don't run as a system service anymore but as the regular user. This makes IP showup again during execution.

I think that broke the runners. Github Actions can no longer checkout the git repositories. https://github.com/AllenInstitute/MIES/actions/runs/4934490515/jobs/8819593705

**Comment by Garados007** [comment]
@t-b I am finished with my tasks and only need to test it. Unfortunately, the CI doesn't work as git cannot run on the windows runners. These are the missing tasks:

- [ ] test PR pipeline to check if it succeeds. To do this we need:
    - [ ] to disable bamboo temporary
    - [ ] fix Windows runner
- [ ] test if main/release pipeline works
- [ ] remove bamboo configuration commit e1393ba14 (bamboo-plain*.yml: Add YAML versions of our current bamboo plans, 2023-03-21)

We can call next week to tackle these steps.

**Comment by t-b** [comment]
I've stopped bamboo, restarted the pipeline and fixed the linting CI step. Let's see what https://github.com/AllenInstitute/MIES/actions/runs/4984059485 gives.

**Comment by t-b** [comment]
> remove bamboo configuration commit https://github.com/AllenInstitute/MIES/commit/e1393ba142ed95313305595eb97c55c43feddc8e (bamboo-plain*.yml: Add YAML versions of our current bamboo plans, 2023-03-21) and rebase

Thinking about this again, please just `git revert` the commit. So that we have the bamboo config in the history.

**Comment by t-b** [comment]
Can you trial documentation publishing and release asset uploading before we merge it to main? You can use any tag which starts with "test*" for that. There is none right now.

`tools/publish-docs-on-github.sh` does not work right now as the current script expects quite some setup on the CI machine. The approach is also not the best one probably. Same goes for `tools/upload-github-release-asset.sh`.

**Comment by t-b** [comment]
Regarding the duplicated `CI_IGOR_REVISION`. Can we only define it in `test-igor-workflow.yml`?

**Comment by t-b** [comment]
And as mentioned yesterday: https://github.com/AllenInstitute/MIES/pull/1656/checks should have non-elided job names on the left.

**Comment by t-b** [comment]
And please package all nwb files in `Packages/tests/HardwareBasic` with tar+gzip for obvious disk space saving reasons.

**Comment by t-b** [comment]
Same non-eliding approach goes for the job names in https://github.com/AllenInstitute/MIES/pull/1656. It would also be less verbose if we could go from `Build Pull Request / 📦 FTP Upload Artifacts (pull_request)` to `📦 FTP Upload Artifacts` in general.

**Comment by t-b** [comment]
Sorry for the feedback dDOS but can we:
- At e.g. https://byte-physics.de/public-downloads/aistorage/transfer/pr/feature/1656-move-to-github-actions/be0c33f1cdb40061eefd0f1194a807e7d1420984/ only have one level of subfolders. So a folder with the artefact name and in there all files without subfolders? This is currently a click-orgy.
- Replace any `/` with "_" in the branch name so that we can remove one folder level?

**Comment by t-b** [comment]
> That's impossible.

Gnaah. Okay let's keep it like it is.

> This would change
> 
> [byte-physics.de/public-downloads/aistorage/transfer/pr/feature/1656-move-to-github-actions/d2062343a4e21c88bf37a85c08603c8ffef3f30f/1/test-itc-assets/Packages/tests/HardwareAnalysisFunctions/JU_HardwareAnalysisFunctions_2023-05-17_08-00-11.xml](https://byte-physics.de/public-downloads/aistorage/transfer/pr/feature/1656-move-to-github-actions/d2062343a4e21c88bf37a85c08603c8ffef3f30f/1/test-itc-assets/Packages/tests/HardwareAnalysisFunctions/JU_HardwareAnalysisFunctions_2023-05-17_08-00-11.xml)
> 
> into
> 
> [byte-physics.de/public-downloads/aistorage/transfer/pr/feature_1656-move-to-github-actions/d2062343a4e21c88bf37a85c08603c8ffef3f30f/1/test-itc-assets/JU_HardwareAnalysisFunctions_2023-05-17_08-00-11.xml](https://byte-physics.de/public-downloads/aistorage/transfer/pr/feature_1656-move-to-github-actions/d2062343a4e21c88bf37a85c08603c8ffef3f30f/1/test-itc-assets/JU_HardwareAnalysisFunctions_2023-05-17_08-00-11.xml)
> 
> Am I right?

Yes!

**Comment by Garados007** [comment]
I got the full PR Pipeline (excluding the one ITC pxp) running: [Github Actions](https://github.com/AllenInstitute/MIES/actions/runs/5023108853), [FTP Artifacts](https://byte-physics.de/public-downloads/aistorage/transfer/pr/feature_1656-move-to-github-actions/2b5c3a03a9e332a1191f63844d869467d6dee415/1/)

For the next step I will disable the PR pipeline and continue to work on the release pipeline.

**Comment by t-b** [comment]
Very nice!

**Comment by Garados007** [comment]
The crucial steps for the [release CI](https://github.com/AllenInstitute/MIES/actions/runs/5026223532) are also working (check the logs for some details). I will keep the current state of the PR for the time being and perform a cleanup and rebase tomorrow.

**Comment by t-b** [comment]
> I will keep the current state of the PR for the time being and perform a cleanup and rebase tomorrow.

I just had a look with Tim and it looks great! No change requests as well ;)

Please assign me once the PR is ready for review.

**Comment by Garados007** [comment]
I've done the last steps:
- rebase and reordered commits to have a clean history
- cleanup debug commits and lines
- delete test release and tag
- re-enabled the PR CI

I started a final CI run with the failing ITC test re-enabled. Either it's working now or not. If you want you can remove 91f47df5f (Disable failing ITC requirement, 2023-05-19) and f18b6e12f (This reverts commit 91f47df5f (Disable failing ITC requirement, 2023-05-19)., 2023-05-20) or the last of them from the commit history - depending on the CI result. If you haven't started reviewing until tomorrow I will do this by myself.

After all. Have fun reviewing 😃

**Comment by Garados007** [comment]
Update: The ITC tests are working now. I removed 91f47df5f (Disable failing ITC requirement, 2023-05-19) and f18b6e12f (This reverts commit 91f47df5f (Disable failing ITC requirement, 2023-05-19)., 2023-05-20). I also made the nwb artifact download optional (it seems like ITC isn't creating this kind of files).

**Comment by t-b** [comment]
LGTM! Very nicely done!

**Comment by t-b** [comment]
Reopening as I have to do something more here.

**Comment by t-b** [comment]
Finished!
