### ISSUE TITLE
oodDAQ optimization

### ISSUE THREAD

**Issue by MichaelHuth** [AllenInstitute/MIES#159]
Hello,

I had some thoughts on speeding up the  oodDAQ optimization.

How about the following approach for an offset optimization for sweep B relative to sweep A:

Generate a table of time ranges that are not baseline on the sweeps. For a simple Sweep with 8 rectangular pulses there would be 8 ranges.

Expand the ranges by the pre and post times. Optional: reduce ranges to non overlapping ones.
To prevent rounding issues the minimum pre and post times should be one sample intervall.

Set the offset for sweep B such that the first range starts after the first range of sweep A.

Loop over the remaining ranges of sweep A and check for overlap with ranges of sweep B. If there is an overlap then save the overlapping time.

If there was an overlap, increase the offset of sweep B by the maximum of the overlapping times saved and redo the loop.

If there was no overlap, one is done.

**Comment by MichaelHuth** [comment]
@t-b moved from personal comm to issue for discussion

**Comment by t-b** [comment]
Functions to optimize: `OOD_CalculateOffsets` and `OOD_Optimizer`.

**Comment by t-b** [comment]
Closed via #204.
