### ISSUE TITLE
Using epochs who's edges are partially outside the acquired data doesn't work.

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#1595]
FTP: 2022-03-08%20PSC%20example%20data/2022_03_08_140256.pxp
Sweep 0
SF:

```
data(
"Stimset",
select(channels(AD),sweeps())
)
```

gives

```
Specified ending range not inside sweep 0.
```

This is because the stimset epoch is a bit larger than the acquired data. I don't know why it the case here, but it can always be the case with premature stopping a sweep and using a MIES version prior to 8c6e5da6 (EP_WriteEpochInfoIntoSweepSettings: Handle unacquired data, 2021-07-13).

Instead of complaining should we maybe clip the range? Only for epoch names or in general?

EDIT: Some more info for this case:

![image](https://user-images.githubusercontent.com/1185677/209996302-b8915b43-ff51-496a-9ce5-dd12e817f4e7.png)

So the stimset epoch ends at 12041.67969, but the stimset ends at 12041.64, the sampling interval is 0.04. So in this case the stimset decimation, DAQ with fixed frequency 25kHz, resulted in the deviation. For this case the solution could be to clip the epoch. Or adapt the epoch ranges to sample points on storing.

**Comment by MichaelHuth** [comment]
I already thought this might come up as we have in SF a strict check that the evaluated range from the epochs is within the sweep.

I would say we clip it only for epochs and skip if the result has no data.

@timjarsky What would make sense here?

**Comment by t-b** [comment]
@timjarsky Plesae also assign an appropriate project swim lane (todo/staging) if you think this should be done.

**Comment by timjarsky** [comment]
> I already thought this might come up as we have in SF a strict check that the evaluated range from the epochs is within the sweep.
> 
> I would say we clip it only for epochs and skip if the result has no data.
> 
> @timjarsky What would make sense here?
@t-b @MichaelHuth 
I'm not sure if "clip-and-keep" is the right approach. For example, if DAQ was stopped early, I don't think we'd want to include the epoch with truncated data. So, it may be better to skip the epoch in that sweep. Does that make sense?

**Comment by t-b** [comment]
Solution: Ignore differences of less than the sampling interval and just clip the epoch in SF.

**Comment by t-b** [comment]
release/2.3 was the last release without https://github.com/AllenInstitute/MIES/commit/8c6e5da688b426dfb61848ada78482750ca9a31c (EP_WriteEpochInfoIntoSweepSettings: Handle unacquired data, 2021-07-13).

**Comment by MichaelHuth** [comment]
The example experiment is dated earlier:
```
Release_2.2_20210503-8-g8c62a4d5
Date and time of last commit: 2021-05-04T19:00:09+02:00
Submodule status: 
160000 3ca8f77c798c04e432907c95e7a177bc2905bec3 0	Packages/IPNWB
160000 5ffbdab2c5d42b54f86054c9bcd0cea6e5f07829 0	Packages/doc/doxygen-filter-ipf
160000 42276ed677273c02bc7b457324081dd463bb0d6b 0	Packages/unit-testing
```

**Comment by MichaelHuth** [comment]
Test with current MIES version (data from old left, current right) works:

![image](https://github.com/AllenInstitute/MIES/assets/29093275/c35c5d0c-b10e-44db-b7a2-688a4a54c928)
