### ISSUE TITLE
EnsureLargeEnoughWave: Rename minimumWaveSize argument

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#1597]
The naming is confusing, see https://github.com/AllenInstitute/MIES/pull/1582#issuecomment-1353326425.

**Comment by MichaelHuth** [comment]
I'd estimate from a quick view that in about 50% of the calls in the MIES code minimumSize is not used as intended.

**Comment by t-b** [comment]
The bug results in only wasted space right?

**Comment by MichaelHuth** [comment]
Yes, the effect is, that it increases the size (typically) one index too early.

**Comment by MichaelHuth** [comment]
rename to: indexShouldExist
