### ISSUE TITLE
SweepFormula: Divide does not work with multiple datasets

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#1618]
_Originally posted by @timjarsky in https://github.com/AllenInstitute/MIES/issues/1617#issuecomment-1379797344_
      

```
tp(tpfit(doubleexp, tausmall, 500), select(channels(AD0), sweeps(), all))

/

tp(tpfit(doubleexp, tau, 500), select(channels(AD0), sweeps(), all))
```

currently results in a "Expected only a single dataSet" error.

The stacktrace is:

```
SF_button_sweepFormula_display
SF_FormulaPlotter
SF_GatherFormulaResults
SF_ExecuteFormula
SF_FormulaExecutor
SF_OperationDiv
SF_GetArgumentTop
SF_FormulaExecutor
SFH_GetArgumentSingle
SFH_ASSERT
```

This issue is probably present in all functions using SF_GetArgumentTop `+`/`-`/...

I can think of two solutions:
- Lift that limitation
- Make `tp` and others return a single dataset

**Comment by timjarsky** [comment]
@t-b the latter option seems like it would be the most flexible or easy to integrate with future developments. For example, if we wanted to fit the result.

**Comment by timjarsky** [comment]
@t-b option two would also work with SF operation -avg -mean in a way that would be helpful
