### ISSUE TITLE
Wrong calculation in SweepFormula apfrequency operation method FULL 

### ISSUE THREAD

**Issue by MichaelHuth** [AllenInstitute/MIES#1625]
The method FULL calculates the number of found peaks divided by the length of the sweep.
Currently the calculation uses the length of the sweep wave, but that is not necessarily the length of the sweep.
The sweep itself can be shorter if the acquisition was stopped before. Here the actual length of the acquired data must be used.

**Comment by t-b** [comment]
Code:

```igorpro
static Function/WAVE ES_GetStimsetRange(string graph, WAVE selectData)

	variable sweepNo, channel, chanType, DAChannel

	sweepNo  = selectData[0][%SWEEP]
	channel  = selectData[0][%CHANNELNUMBER]
	chanType = selectData[0][%CHANNELTYPE]

	// stimset epoch "ST" does not include any onset or termination delay but only the stimset epochs
	// and it also works with ddDAQ/oodDAQ
	DAChannel = SFH_GetDAChannel(graph, sweepNo, chanType, channel)
	WAVE range = SFH_GetRangeFromEpoch(graph, "ST", sweepNo, DAChannel)

	if(SFH_IsEmptyRange(range))
		// data prior to 13b3499d (Add short names for Epochs stored in epoch name, 2021-09-06)
		// try the long name instead
		WAVE range = SFH_GetRangeFromEpoch(graph, "Stimset;", sweepNo, DAChannel)
		if(SFH_IsEmptyRange(range))
			// data prior to a2172f03 (Added generations of epoch information wave, 2019-05-22)
			// remove total onset delay and termination delay iff we have neither dDAQ nor oodDAQ enabled
			SFH_ASSERT(0, "Fallback not implemented")
		endif
	endif

	return range
End
```

**Comment by t-b** [comment]
@timjarsky As we plan to use `apfrequency` for the new suprathreshold variant in #1535 I would like to tackle this issue first.

**Comment by timjarsky** [comment]
@t-b that sounds good, but can you verify that @MichaelHuth means that the length of the epoch is used to calculate the frequency and not the sweep?

**Comment by t-b** [comment]
I've chatted with Tim about this issue and the agreement is that we don't want to use a different range compared to what the user provided. I'll be adding some clarifications to the documentation in #1892.
