### ISSUE TITLE
Make SweepFormula graph panels closing without dialog?

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#1657]
At least for me this would be more convenient. We already do that with the data/sweep browser.
@timjarsky What do you think?

**Comment by timjarsky** [comment]
Great idea, @t-b.

**Comment by t-b** [comment]
> @t-b, while working on this, would it also be possible to avoid the save dialog when loading a .pxp into an empty .pxp?

Yes I can do that, but as that is another area I've created #1658.
