### ISSUE TITLE
Avoid save dialog on loading an experiment

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#1658]
>would it also be possible to avoid the save dialog when loading a .pxp into an empty .pxp?

_Originally posted by @timjarsky in https://github.com/AllenInstitute/MIES/issues/1657#issuecomment-1478111774_

**Comment by t-b** [comment]
@MichaelHuth I've assigned you to that issue, as I'm still busy with PSX for now. Thanks.

**Comment by MichaelHuth** [comment]
Created bug report for WM.
