### ISSUE TITLE
Windows 10 issues with ITC18USB

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#166]
On Windows 10 the hardware tests with ITC18USB do not pass at all.

Command:

```
runtest("UTF_Basichardwaretests.ipf", testcase="MD0_RA0_I0_L0_BKG_0")
```

Output:
```
  Start of test "Unnamed"
  Entering test suite "UTF_BasicHardwareTests.ipf"
  Entering test case "BasicHardwareTests#MD0_RA0_I0_L0_BKG_0:ITC"
  Available number of specified ITC devices = 1
  ITC Device opened, returned deviceID is 0.
  DLL Error.
	Error in call to ITC_Start.
	Reported error: Memory Error (0x80421000)
  The ITC XOP returned the following errors: ITCError=0x80421000, ITCXOPError=0
  Memory Error (0x80421000);Place: User Layer; Connection: User Layer; Error Type: Allocation; Sequence Number: 0x2; Device Type: ITCxx; OS: Any; Application: Regular; Local Sequence Number: 0x0
  Some hints you might want to try!
  - Is the correct ITC device type selected?
  - Is your ITC Device connected to a power socket?
  - Is your ITC Device connected to your computer?
  - Have you tried unlocking/locking the device already?
  - Reseating all connections between the DAC and the computer has also helped in the past.
  !!! Assertion FAILED !!!
  Message: "DAC error"
  Uncaught runtime error 262150:"ITCStartAcq2;Problem with ITC DLL." in test case "BasicHardwareTests#MD0_RA0_I0_L0_BKG_0", procedure file "UTF_BasicHardwareTests.ipf"
Encountered "Abort" in test case "BasicHardwareTests#MD0_RA0_I0_L0_BKG_0", procedure file "UTF_BasicHardwareTests.ipf"
```

This is 100% reproducible on IP7 and IP8. And if everything is started with admin rights this happens as well.

After this bugs out, doing a manual unlock/lock cycle and then starting DAQ works.

But doing the same programmatically with 

```
Function Dostuff()

	string device = "ITC18USB_Dev_0"
	string unlockedPanelTitle = "DA_Ephys"

	PGC_SetAndActivateControl(device, "button_SettingsPlus_unLockDevic", switchtab=1)
	PGC_SetAndActivateControl(unlockedPanelTitle, "button_SettingsPlus_LockDevice", switchtab=1)
	PGC_SetAndActivateControl(device, "DataAcquireButton", switchtab=1)
End 
```

bugs out again.

Next things to try:
- [ ] Come up with a self contained test case which does not use MIES and try with IP6 on Windows 10
- [ ] Look with the debugger into the XOP
- [ ] Chat with WM again about debugger breakpoint thingie

**Comment by t-b** [comment]
And

```
Function Dostuff()

	string device = "ITC18USB_Dev_0"
	string unlockedPanelTitle = "DA_Ephys"

	PGC_SetAndActivateControl(device, "ADC", val = 6)
	PGC_SetAndActivateControl(device, "button_SettingsPlus_unLockDevic")

	PGC_SetAndActivateControl(unlockedPanelTitle, "button_SettingsPlus_LockDevice")

	PGC_SetAndActivateControl(device, "ADC", val = 0)
	PGC_SetAndActivateControl(device, "DataAcquireButton")
End
```

bugs out as well.

**Comment by t-b** [comment]
Doing the locking step manually and the rest via PGC does *not* bug out.

**Comment by t-b** [comment]
```Function Dostuff()
	
	first()
	second()
	third()
End

Function First()

	string device = "ITC18USB_Dev_0"
	string unlockedPanelTitle = "DA_Ephys"

	PGC_SetAndActivateControl(device, "button_SettingsPlus_unLockDevic")
//	Execute/P/Q "Second()"
End

Function Second()

	string device = "ITC18USB_Dev_0"
	string unlockedPanelTitle = "DA_Ephys"

	PGC_SetAndActivateControl(unlockedPanelTitle, "button_SettingsPlus_LockDevice")
//	Execute/P/Q "Third()"
End

Function Third()

	string device = "ITC18USB_Dev_0"
	string unlockedPanelTitle = "DA_Ephys"

	PGC_SetAndActivateControl(device, "DataAcquireButton")
End
```

Maybe this is more a windows 10 thing and not a itc thing.

**Comment by t-b** [comment]
That problem is not present for ITC1600 hardware.

**Comment by t-b** [comment]
Emailed WM due to 

```
  BUG: An error occurred in MWStoreSelRec. If possible, tell WaveMetrics what you did to trigger this.
  Stack Trace:
  	Stack trace is not available
```

which hints to an IP bug.

**Comment by t-b** [comment]
ITCDemo and ITCControl applications work.

**Comment by t-b** [comment]
Using https://github.com/AllenInstitute/ITCXOP2/pull/5 the ITC XOP tests run without error on Windows 7 and Windows 10.

**Comment by t-b** [comment]
What works:

Settings a breakpoint at the beginning of

```
Function DAP_LockDevice(panelTitle)
	string panelTitle
...
````

and then going in this function line by line. Just choosing `Go` does result in the usual error.

**Comment by t-b** [comment]
Self contained example (adapted from the ITCXOP2 tests):
[QuickTest.zip](https://github.com/AllenInstitute/MIES/files/3517120/QuickTest.zip)

Fails on IP8 64bit and *works* on IP7 32bit. I'm now running the test suite on IP8 32bit.

**Comment by t-b** [comment]
@timjarsky After chatting with @MichaelHuth today we found a hack for being able to get 64bit working. You have to disable ASLR (https://de.wikipedia.org/wiki/Address_Space_Layout_Randomization) for Igor Pro and then it works. I'm just running the test suite to be sure.

**Comment by timjarsky** [comment]
> @timjarsky After chatting with @MichaelHuth today we found a hack for being able to get 64bit working. You have to disable ASLR (https://de.wikipedia.org/wiki/Address_Space_Layout_Randomization) for Igor Pro and then it works. I'm just running the test suite to be sure.

@t-b it is helpful that ASLR can be disabled on a per-program basis. This also sounds like information HEKA could use to debug.

**Comment by t-b** [comment]
@timjarsky Yes, once we figured out how to conveniently disable that I'll write an email to heka.

**Comment by t-b** [comment]
@timjarsky Tests passed!

**Comment by t-b** [comment]
From my testing on the Windows 10 CI box I would say ITC1600 does has some issues too. The ASLR fix should help as well.

**Comment by timjarsky** [comment]
> From my testing on the Windows 10 CI box I would say ITC1600 does has some issues too. The ASLR fix should help as well.

That's too bad. Let me know if the ITC1600 tests pass ASLR disabled.

**Comment by t-b** [comment]
@timjarsky I can't apply the ASLR fix as I don't have admin access on the windows 10 CI box.
