### ISSUE TITLE
Multiclamp Commander not seen by Igor Pro in Win11

### ISSUE THREAD

**Issue by MichaelHuth** [AllenInstitute/MIES#1675]
Since a few weeks I see the issue that often (but not always) MIES does not recognize an open Multiclamp Commander.
The behavior of MIES is as if there was no MCC running. There is no specific error issued.

Igor Pro 9
Win 11 Build 22621

**Comment by t-b** [comment]
I can't reproduce that here with "OS:Microsoft Windows 11 Pro (23H2)". Please reopen if the issue appears again.
