### ISSUE TITLE
Configuration: Ignore SetVar_Sweep control on save and load

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#1698]
@timjarsky Do you agree that it does not make sense to store and save that control to the JSON configuration?

**Comment by timjarsky** [comment]
@t-b, can you drop a pic of the control or tell me what GUI it belongs to?

**Comment by t-b** [comment]
DAEphys panel, the SetVariable to show the next sweep which is now display only as we removed sweep rollback.

**Comment by timjarsky** [comment]
@t-b I agree, it doesn't make sense to configure that control. The same goes for any other control that is display only.
