### ISSUE TITLE
63fadb84-f59d-46a2-b8d7-e3f65d508b04

### ISSUE THREAD

**Issue by ramr24** [AllenInstitute/MIES#1709]
Successfully uploaded the MIES, ZeroMQ-XOP and ITCXOP2 logfiles. Please mention your ticket "63fadb84-f59d-46a2-b8d7-e3f65d508b04" if you are contacting support.

Ram uploaded issue from rig 4.

**Comment by t-b** [comment]
Thanks! I'm closing this issue as #1708 already tracks it.
