### ISSUE TITLE
NWB file saving errors

### ISSUE THREAD

**Issue by meanhwan** [AllenInstitute/MIES#1749]
![nwb_saving_error](https://github.com/AllenInstitute/MIES/assets/24505242/f25b46eb-54db-40bb-8b2c-635558558b28)

After I updated the Igor version yesterday, it seems to have a problem to save nwb file (fine to save pxp file). But maybe this problem is caused by new protocol and data acquisition I started from yesterday. PXP file size is about 3 Gigabytes, so I will share this pxp file separately. Thanks!

-----
  ################################
  !!! Assertion FAILED !!!
  Message: "Buggy timestamp handling"
  Please provide the following information if you contact the MIES developers:
  ################################
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Stacktrace:
NWB_ExportWithDialog(...)#L834 [MIES_NeuroDataWithoutBorders.ipf]
NWB_ExportAllData(...)#L577 [MIES_NeuroDataWithoutBorders.ipf]
NWB_GetFileForExport(...)#L205 [MIES_NeuroDataWithoutBorders.ipf]
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Time: 2023-05-25T12:46:34-07:00
  Locked device: [ITC1600_Dev_0]
  Current sweep: [110]
  DAQ: [DAQ_NOT_RUNNING]
  Testpulse: [TEST_PULSE_BG_MULTI_DEVICE]
  Experiment: 2023_05_25_120109 (Packed)
  Igor Pro version: 9.0.2.4 (39951)
  MIES version:
  Release_2.6_20220606-40-g5858c9ed5
Date and time of last commit: 2022-09-15T12:56:17+02:00
Submodule status:
 f3493461480eaafa97939940693ed693860048a6 Packages/IPNWB (f349346)
 56f1da31d786a593892280c2d2b2b1190def0fb5 Packages/doc/doxygen-filter-ipf (heads/main)
 a8d4707e7c72555baefbb9a4d52de920e1d8ebb9 Packages/unit-testing (a8d4707)
  ################################

**Comment by t-b** [comment]
We fixed an issue in december last year, fabdddc1 (NWB_GetFileForExport: Compare session start times with tolerance, 2022-12-04), which fixes the NWB export with newer Igor Pro versions.

I could replicate the error you are seeing as well.

So you either:
- Go back to your old IP version and keep your current MIES version
- or get the latest MIES version from https://github.com/AllenInstitute/MIES/releases/tag/latest and you use that with your current Igor Pro version

**Comment by t-b** [comment]
Please report back if it then works for you.

**Comment by t-b** [comment]
Closing due to no feedback.
