### ISSUE TITLE
Look into how TP settings are fetched for unassociated channels

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#1802]
> @MichaelHuth, sorry for this late question, but how are the TP properties (e.g., amplitude) on unassociated DA channels set?

_Originally posted by @timjarsky in https://github.com/AllenInstitute/MIES/issues/1772#issuecomment-1622399039_

**Comment by t-b** [comment]
From @MichaelHuth:

> For inserting the TP in unassociated DA channels the same code as for associated DA channels is run. Thus, the same settings apply for unassociated DA channels. The checkbox to switch the inserted TP off for unassociated DA replaces the time interval where for associated DA channels the TP is inserted with constant baseline amplitude.

**Comment by t-b** [comment]
> Thus, the same settings apply for unassociated DA channels. 

The TP settings are per headstage so I guess Tim's question was how we figure out a TP amplitude for an unassociated headstage if we have only headstage dependent settins.

**Comment by MichaelHuth** [comment]
In MIES_DataConfigurator.ipf#L1408 we set a constant for TP amplitude of unassociated DA channels. This constant is 0.0 at the moment.

Options:
1. setting per DA channel (used when specific channel is unassociated)
2. one setting for all DA channels (used for unassociated DA)

**Comment by timjarsky** [comment]
@t-b @MichaelHuth I prefer to simplify and not allow TP insertion on unassociated DA channels. I'm not sure there is a use case for inserting a TP on unassociated channels. It would also remove/not-add a checkbox in the settings panel.

**Comment by t-b** [comment]
So remove the checkbox and the labnotebook entry again, never insert TP into unassoc but keep the new epoch added instead of the TP epoch.
