### ISSUE TITLE
AdaptDependentControls works only with DAEphys panel

### ISSUE THREAD

**Issue by MichaelHuth** [AllenInstitute/MIES#1806]
Example:

`AdaptDependentControls(bsPanel, "check_BrowserSettings_VisEpochs", CHECKBOX_SELECTED, CHECKBOX_UNSELECTED, DEP_CTRLS_SAME)`

Problem is, if defaultMainState != newMainState the function tries to retrieve the old state and calls DAG_GetNumericalValue which only works for the DAEPhys panel. For other panels the window name is interpreted as device name which fails ultimately in createDFWithAllParents where "mainWin#Subwin" is not a valid object name.

**Comment by t-b** [comment]
```diff

diff --git a/Packages/MIES/MIES_GuiUtilities.ipf b/Packages/MIES/MIES_GuiUtilities.ipf
index 12bdc4d22f..20c906d9fe 100644
--- a/Packages/MIES/MIES_GuiUtilities.ipf
+++ b/Packages/MIES/MIES_GuiUtilities.ipf
@@ -2242,6 +2242,10 @@ Function AdaptDependentControls(string win, string controls, variable defaultMai
             // invalidate old state
             SetControlUserData(win, ctrl, "oldState", "")

+            if(IsNaN(oldState))
+                continue
+            endif
+
             // set old state
             PGC_SetAndActivateControl(win, ctrl, val = oldState)
         endfor
```

Rename defaultMainState: If it is the same as the new state, it restores the dependent control states. Otherwise if it is different it saves the state of the dependent controls.

Revise documentation.
