### ISSUE TITLE
DAEphys with no amplifier issues

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#1811]
Users without a Molecular Devices 700B amplifier currently might encounter some obstacles with MIES (version: c9e43a9d (Merge pull request #1797 from AllenInstitute/feature/1797-prepare_TTL_epochs, 2023-07-10)).

DAP_CheckSettings:
In DAP_CheckHeastage we require a connected amplifier for the unit comparison check with the DA tab, see https://github.com/AllenInstitute/MIES/blob/c9e43a9d350f9a669159fb36ab5dd8943cb913e6/Packages/MIES/MIES_DAEphys.ipf#L2545. This should be more strict as we want to have matching settings even without an amplifier. We would need to check all settings without an amp as well.

Configuration:
We require a connected amplifier to store the headstage association to the DA/AD channels for the clamp modes. But that is kind of artificial as you can also imagine just having the following snippet stored

```json
            "0": {
                "Amplifier": {
                    "Channel": null,
                    "IC": {
                        "AD": 0,
                        "DA": 0
                    },
                    "Serial": null,
                    "Title": "0,1",
                    "VC": {
                        "AD": 0,
                        "DA": 0
                    }
                },

```

when no amplifier is selected. Related issue is that `"Title"` should not be stored without amplifier.

Now in a world where configuration supports to store and load the headstage association without amplifier and where DAP_CheckSettings checks that the gain/units from the associations tab are the same than the gain/unit entries in the DA/AD tabs there is one hurdle left.

And that is that we don't store the gain/units from the associations tab in the config. This is because with an amplifier these settings are part of the hardware setup, and thus should not be saved. But without an amplifier it would be convenient to store them.

We could just extend the associations entries a la

```json
"0": {
    "Amplifier": {
        "Channel": null,
        "IC": {
            "AD": 0,
            "DA": 0,
            "AD gain": 1,
            "AD unit" : "X",
            "DA gain": 2,
            "DA unit" : "XX"
        },
        "Serial": null,
        "VC": {
            "AD": 0,
            "DA": 0,
            "AD gain": 1,
            "AD unit" : "X",
            "DA gain": 2,
            "DA unit" : "XX"
        }
    }
}
```

when no amplifier is selected.

**Comment by t-b** [comment]
Enlarge Gain set variables to show all significant digits with the default of the 700B amplifier (0.0005)

**Comment by MichaelHuth** [comment]
DAP_CheckSettings: For associated channels/headstage some checks are only done if an amplifier is connected. Decouple this.

Units are synchronized to MIES from the amplifier or alternatively entered by the user. Check if units are the same for both cases.

Configuration:
- save DA/AD channel numbers and units for all active headstages independent of amplifier
- on restore units/gain are retrieved from possible connected amplifier by pressing "button_Hardware_AutoGainAndUnit", if no amplifier is connected restore units/gain in windows normally
