### ISSUE TITLE
SweepFormula: labnotebook should support TTL channels

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#1816]
- [x] Needs #1815
- [x] Clarify with Tim if we want to do it

**Comment by t-b** [comment]
@MichaelHuth IIRC we said that this already works. Can you confirm that?

**Comment by MichaelHuth** [comment]
labnotebook uses the channel type as is. So it already supported TTL channels before, e.g.
```
labnotebook(
"TTL Channels",
select(channels(TTL1),sweeps(),all)
)
```
One problem is https://github.com/AllenInstitute/MIES/issues/1788 (where the fix is pending) for formulas like:
```
labnotebook(
"TTL Channels",
select(channels(TTL),sweeps(),all)
)
```
This is only an issue with textual entries.

**Comment by t-b** [comment]
Works already.
