### ISSUE TITLE
SweepFormula: Support TTL channels

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#1817]
`select`/`data`/`epochs`  should also support data from TTL channels.

**Comment by timjarsky** [comment]
@t-b twist: the primary use case for TTL epochs is to use them to extract AD channel data.

**Comment by t-b** [comment]
> @t-b twist: the primary use case for TTL epochs is to use them to extract AD channel data.

If that twist always applies it is easy to implement.

**Comment by timjarsky** [comment]
@t-b it does always apply. So, do TTL epochs need a channel prefix so something like `data(TTL0_E0, select(channels(AD0), sweeps())` will work?

**Comment by t-b** [comment]
Using the patch proposed by Michael

```diff
diff --git a/Packages/MIES/MIES_SweepFormula.ipf b/Packages/MIES/MIES_SweepFormula.ipf
index 23d0503f17..b088b0c7ed 100644
--- a/Packages/MIES/MIES_SweepFormula.ipf
+++ b/Packages/MIES/MIES_SweepFormula.ipf
@@ -2104,7 +2104,7 @@ static Function/WAVE SF_GetActiveChannelNumbersForSweeps(string graph, WAVE/Z ch
             channelNumber = channels[j][%channelNumber]

             if(IsNaN(channelType))
-                settingList = "ADC;DAC;"
+                settingList = "ADC;DAC;TTL;"
             else
                 switch(channelType)
                     case XOP_CHANNEL_TYPE_DAC:
@@ -2113,6 +2113,9 @@ static Function/WAVE SF_GetActiveChannelNumbersForSweeps(string graph, WAVE/Z ch
                     case XOP_CHANNEL_TYPE_ADC:
                         settingList = "ADC;"
                         break
+                    case XOP_CHANNEL_TYPE_TTL:
+                        settingList = "TTL;"
+                        break
                     default:
                         sprintf msg, "Unhandled channel type %g in channels() at position %d", channelType, j
                         SFH_ASSERT(0, msg)
@@ -2131,6 +2134,10 @@ static Function/WAVE SF_GetActiveChannelNumbersForSweeps(string graph, WAVE/Z ch
                         channelType = XOP_CHANNEL_TYPE_ADC
                         maxChannels = NUM_AD_CHANNELS
                         break
+                    case "TTL":
+                        channelType = XOP_CHANNEL_TYPE_TTL
+                        maxChannels = NUM_DA_TTL_CHANNELS
+                        break
                     default:
                         SFH_ASSERT(0, "Unexpected setting entry for channel type resolution.")
                         break
```

with TTL_2023_07_12_154006.zip from the issue1817 folder on the FTP.

When using the SF formula

```
TTL=select(channels(TTL0),sweeps())
r=epochs(E0, $TTL)

$r
```

I get two ranges. The reason is that the select expression results in two matches as for TTL0 we have the same hardware channel. Maybe the returned channel numbers for select should be GUI channel numbers?

**Comment by t-b** [comment]
SF_OperationEpochsImpl should also prefer EP_FetchEpochs

**Comment by t-b** [comment]
Chat with Michael:
- Add gui channel number in TUD for DB/SB, see CreateTiledChanneLgraph
- Adapt axis naming for TTL in databrowser/sweepbrowser, show GUI channel (TTL2) instead of combination of hardware channel and TTL bit TTL0_2 for ITC
- BSP_AddTracesForEpoch, use new TUD gui channel numbers
- SF_GetActiveChannelNumbersForSweeps
  - Define that select returns GUI channel numbers, adapt documentation
  - Use GUI channel numbers for all channel types
  - All case:
    - Support TTL with ITC hardware
    - Fix support for unassoc DA/AD
    - Ignore clamp mode selection by user for TTL/unassoc
- Adapt data extraction in SFH_GetSweepsForFormula, GetDAQDataSingleColumnWave
  - TTL/ITC: Calculate HW channel/TTLBits from GUI channel, see TestEpochsGeneric()
- Add wrapper for GetDAQDataSingleColumnWave which accepts numerical/textual LBNs

```igorpro
Function/WAVE GetDAQDataSingleColumnWaveNG(WAVE numericalValues, WAVE/T textualValues, DFREF sweepDFR, variable channelType, variable GUIchannelNumber)
End
```

. This calls GetDAQDataSingleColumnWave always with `splitTTLBits = 1`.
- SF_OperationEpochsImpl should prefer EP_FetchEpochs
