### ISSUE TITLE
Allow multi data input for range argument of data operation

### ISSUE THREAD

**Issue by MichaelHuth** [AllenInstitute/MIES#1819]
Currently data accepts only a single dataset entry for the range argument.
However, epochs can return a multi data range output.

The data operation can be extended to accept multi data range inputs.
Then loop over all ranges for each sweep including data sets with epoch wildcards like:
DS 0: "E*"
DS 1: "ST*"

~~It makes no sense to extend the range operation for multi data output.~~

**Comment by timjarsky** [comment]
Use case:

multiple sweeps displayed, now we want to offset each epoch a bit
```
data(epoch(E1) + [0, 100])
```

but that gives the error "Expected a single dataset" from SFH_EvaluateRange. As we support gathering multiple ranges of data via epoch wildcards I see no reason to not support that.

**Comment by MichaelHuth** [comment]
SFH_EvaluateRange should always return a wave ref wave with datasets, also convert 1D text wave from epoch names to datasets with single text elements.

SFH_GetSweepsForFormula accepts only wave ref waves for range argument.

Adapt SFH_GetFullRange(), SFH_IsFullRange, SFH_GetEmptyRange also to return single datasets.

data should accept for numerical range input: single numerical range or multiple with the same number as sweeps.

**Comment by MichaelHuth** [comment]
Ok, I have a solution that supports these range specifications for data (leave one trange line uncommented for testing):

```
sel = select(channels(DA), sweeps(),all)
trange = epochs(ST,$sel) + [[1, 2, 3],[-1, -2, -3]] # does not work
#trange = epochs(ST,$sel) + [1, -2]
#trange = epochs(ST,$sel)
#trange = [[0, 800],[600, 1000]]
#trange = cursors(A,B)
#trange = ST
dat = data($trange, $sel)

$dat

```

Description for `trange = [0, 800]`  and `trange = [[0, 800],[600, 1000]]`: The first specification is a classic `[start, end]` specification. The second specifies two ranges in the form` [[start1, start2],[end1, end2]]` . Because input arguments from the SF notebook are always single datasets, the ranges are applied to all sweeps from $sel. The pattern can be continued with 
` [[start1, start2, start3],[end1, end2, end3]]` and so on.

Description for `trange = epochs(ST,$sel) + [[1, 2, 3],[-1, -2, -3]]`: This does not work because with e.g. 3 sweeps, epochs returns 3 datasets. The term after the plus however, is a single dataset specifying 3 ranges. The plus operation can not add 3 and 1 dataset unless the content of the 1 dataset part matches in dimensions to the content of the 3 dataset part, like for `trange = epochs(ST,$sel) + [1, -2]`.

This means, that with the change a calculation can be applied to all epochs datasets. For the case of plus it would add the same constants to all ranges from epochs.

Now if different constants are needed, then we would need an operation that converts a single dataset input to multiple datasets. e.g. `trange = epochs(ST,$sel) + todatasets([[1, 2, 3],[-1, -2, -3]])` where todatasets would convert the [2,3] array to 3 datasets with a [2] aray each. For 3 sweeps epochs would return 3 datasets as well, thus plus would work.

- [ ] Tests and adapt Tests
