### ISSUE TITLE
Initial NWB export takes forever when having a large ZeroMQ logfile

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#1867]
We have a report that configuring the DaEphys panel takes a couple of minutes with the new MIES version (2.7).

I made a shot in the dark and renamed the 2.4GB zeromq logfile. And now the issue is gone.

Maybe we should archive the unintereseting parts of the logfile in NWB_AppendLogFileToString?

@MichaelHuth Would that make sense? If yes can you take a stab at this?

**Comment by t-b** [comment]
Asked reporter about sample logfile.

**Comment by t-b** [comment]
@MichaelHuth The FTP has in the folder `issue-1867` a sample logfile (zipped).

**Comment by t-b** [comment]
@MichaelHuth Did you look into the posted log file?

**Comment by MichaelHuth** [comment]
Yes. The average size increase is 2.7 MB/day.

**Comment by t-b** [comment]
Thanks!
