### ISSUE TITLE
Amplitude for InsertedTP not zeroed in case scalingZero && (indexingLocked || !indexing) && setCycleCount > 0

### ISSUE THREAD

**Issue by MichaelHuth** [AllenInstitute/MIES#187]
https://github.com/AllenInstitute/MIES/blob/bd0a498e3196a3d56e0c5ced11f7bc5a8c91d719/Packages/MIES/MIES_DataConfiguratorITC.ipf#L821-L823

If InsertedTP happens for this case then the amplitude is not zeroed as it is in the other cases with `testPulseAmplitude[activeColumn] = 0.0`. This results in a zeroed stimset but still active TP.

@timjarsky Is it possible to have inserted TP enabled for this case? If yes then we also need to add 
`testPulseAmplitude[activeColumn] = 0.0`.

**Comment by t-b** [comment]
@MichaelHuth Current behaviour is correct according to https://github.com/AllenInstitute/MIES/pull/180#issuecomment-498749165.
