### ISSUE TITLE
jq error from pre-push hook

### ISSUE THREAD

**Issue by MichaelHuth** [AllenInstitute/MIES#1871]
I have seen the following error when pushing a new branch:

```
$ git push --set-upstream origin bugfix/1870-mh_long_new_export_due_to_logfile
jq: error (at <stdin>:1): Cannot index string with string "number"
error: failed to push some refs to 'https://github.com/AllenInstitute/MIES.git'

```

Also:
check-code.sh is called in the pre-push hook, though it would make sense to check only the already committed code here. Instead it checks the current files.

**Comment by t-b** [comment]
Intermittent error it seems.

**Comment by t-b** [comment]
Please reopen if the problem persists.
