### ISSUE TITLE
NWB export has data loss

### ISSUE THREAD

**Issue by cristinarada** [AllenInstitute/MIES#1876]
Description:
Description:
- What was MIES doing at the time of the unexpected behavior?
MIES is not exporting the experiment in nwb correctly in some cases. For some experiments, the export size is correct, but for others (as in the case of QN23.26.012.4A.07.01 attached here) the export to nwb fails, and data is missing.
- Did user input immediately precede the unexpected behavior?

- What did you expect to happen?
I expected all the experiments to be exported and saved correctly. All the experiments were recorded and saved on the same machine and with the same Igor version.
[MIES request.zip](https://github.com/AllenInstitute/MIES/files/12528630/MIES.request.zip)

Igor Pro Experiment files can be attached as zip file if needed.

The following contains installation information (keep unchanged):
```
MIES version: Release_2.6_20220606
Date and time of last commit: 2022-06-06T22:02:48+02:00
Submodule status:
 f3493461480eaafa97939940693ed693860048a6 Packages/IPNWB (heads/main)
 56f1da31d786a593892280c2d2b2b1190def0fb5 Packages/doc/doxygen-filter-ipf (heads/main)
 a8d4707e7c72555baefbb9a4d52de920e1d8ebb9 Packages/unit-testing (a8d4707)
```

```
Igor Pro version: OS:Microsoft Windows 10 Enterprise (22H2);OSVERSION:10.0.19045.3208;LOCALE:US;IGORFILEVERSION:9.0.2.2;
```

```
Installation self-test results:
Checking system properties:
Igor 64bit: 9.02, 39935
Windows 10: True
ASLR: True (Very Bad)

Checking known defines:
DEBUGGING_ENABLED: No
EVIL_KITTEN_EATING_MODE: No
BACKGROUND_TASK_DEBUGGING: No
THREADING_DISABLED: No

Checking base installation:
Mies version info: Valid "Release_2.6_20220606..." (Nice!)
ITC XOP: Found version 1.0.2.0 (Nice!)
JSON XOP: Found version 1.0.0.1 (Nice!)
VDT2 XOP: Found version 3.0.0.0 (Nice!)
Axon Telegraph XOP: Found version 3.0.0.0 (Nice!)
Multi Clamp Commander XOP: Found version 2.0.0.0 (Nice!)
ZeroMQ XOP: Found version 1.0.0.1 (Nice!)
JSON XOP: Present in the right version (version-753-g902d43f) (Nice!)
Results: 8 checks, 1 number of errors

Checking extended installation:
NI-DAQ MX XOP: The file NIDAQmx64.xop could not be found (Very Bad)
Results: 1 checks, 1 number of errors
```

**Comment by cristinarada** [comment]
Hi Thomas,

Thank you for getting back to me quickly.
I proceeded to install the MIES version 2.7 as recommended and tomorrow I
should be doing experiments so I'll try it out to see if the compressed
file conversion works now.
I'll be in touch shortly, thank you!

**Comment by cristinarada** [comment]
@t-b I had the chance to try exporting 3 nwb files and all the exports were successful! Thank you!!

**Comment by t-b** [comment]
Good, so I'll close this issue.
