### ISSUE TITLE
Invalid Igor test pxp files from MIES/tools/unit-testing/

### ISSUE THREAD

**Issue by MichaelHuth** [AllenInstitute/MIES#188]
When trying to load any of the recent experiment file from /tools/unit-testing/ I get:

![image](https://user-images.githubusercontent.com/29093275/58881939-8511b200-86db-11e9-8bca-d6af0330276e.png)

Tried with nightly IP8 and IP7.

**Comment by t-b** [comment]
@MichaelHuth Have you called `tools/initial-repo-config.sh` once as outlined in the docs ?

**Comment by MichaelHuth** [comment]
@t-b I cloned it fresh without moving the .git folder into the previous repo and it works now.
