### ISSUE TITLE
RTE ShowTraceInfoTags, DoIgorMenu/OVRD returning S_value as null string

### ISSUE THREAD

**Issue by MichaelHuth** [AllenInstitute/MIES#1886]
I have just seen this issue:

![image](https://github.com/AllenInstitute/MIES/assets/29093275/389ec988-29d2-4cc8-988c-cb48ed2aa864)

Igor Pro 9 Build 56437

**Comment by t-b** [comment]
Please investigate. Thanks.

**Comment by MichaelHuth** [comment]
Status: Waiting for next nightly, to verify changed behavior. Needs a BUG output if S_Value returns "". If we can trigger that then, we need to think about how to get the function to work reliably again. :-/
