### ISSUE TITLE
Ping website on MIES device locking to count users

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#197]
- [x] Add new setting "User Ping" to package settings defaults to `on`
- [x] Add toggable menu entry to turn it permanently off
- [x] Add JSON config setting to turn on/off
- [x] Only do at most once a day, don't do in CI
- [x] Upload info on device lock via GenerateJSONTemplateForUpload/AddPayloadEntries/UploadJSONPayload.
- [ ] Clarify if doing it in the startup hook would be better, as we would then also count users which would not have hardware

Uploaded info in addition to the defaults:
- available hardware types
- Full IP version
- MIES version

**Comment by t-b** [comment]
- [ ] Look into technical options to find out the location of each user

**Comment by timjarsky** [comment]
@ t-b tracking users who don't use hardware is a good idea, but it also makes sense to track users who have hardware. I'm unsure how to do this in a way that doesn't result in two pings.

**Comment by t-b** [comment]
@timjarsky The current implementation pings on every IP startup. I think we can handle the additional load.
