### ISSUE TITLE
WB_StimsetChildren needs to search in EPOCH_TYPE_COMBINE (not EPOCH_TYPE_CUSTOM)

### ISSUE THREAD

**Issue by MichaelHuth** [AllenInstitute/MIES#2044]
Currently it can not find referenced stimsets from formulas.

**Comment by MichaelHuth** [comment]
@t-b Is it a github bug that the merge of #2055 did not close this issue automatically?

**Comment by t-b** [comment]
#2055 did not merge against main therefore the issue was not closed automatically by github.
