### ISSUE TITLE
TP during DAQ behavior when active headstages have TestPulse stimset selected

### ISSUE THREAD

**Issue by timjarsky** [AllenInstitute/MIES#205]
@t-b IVSCC users uncovered some weird behavior when mistakenly selecting the new default TestPulse stimset with one headstage active. 

Should MIES prevent DAQ or Just run the TP?

I think I favor the former.

**Comment by t-b** [comment]
@timjarsky We have specified that if only "TP during DAQ" channels are enabled we run for the following amount of seconds:

https://github.com/AllenInstitute/MIES/blob/3b8ea4c6fabd474312f16ff428a1f89b53ec622f/Packages/MIES/MIES_Constants.ipf#L94-L100

We can of course change that.

**Comment by t-b** [comment]
Works as intended.
