### ISSUE TITLE
Initial seal pressure isn't being updated

### ISSUE THREAD

**Issue by timjarsky** [AllenInstitute/MIES#208]
Hitting the seal button does not update the seal pressure in the val display [1]. Moving the slider after initializing seal induces the correct behavior.

[1] 
![image](https://user-images.githubusercontent.com/5693697/59538824-e988fa00-8eaf-11e9-90d0-87a34bc7eb6d.png)

**Comment by t-b** [comment]
Not a bug, the control of the "User" tab in the pressure widget was checked for Seal.
