### ISSUE TITLE
Network connection to byte-physics.de seem to be blocked from the CI machines

### ISSUE THREAD

**Issue by MichaelHuth** [AllenInstitute/MIES#2085]
- format utility ipt can not be retrieved, code formatting step can not be executed
- Historic data tests can not be executed as the relevant testing experiments can not be retrieved

The actual reason is currently unclear, but it seems to be some issue on CI site as from my developer computer the network connection works just fine.

It would also be good to get some hints, how to prevent such blocking in the future.

**Comment by t-b** [comment]
@timjarsky Could you check your IT guys if they have blocked `byte-physics.de`? With the new IP formatting CI job we are downloading ipt.exe from our server, which could look odd for an antivirus tool.

**Comment by t-b** [comment]
This seems to fixed again. For the record failing jobs were https://github.com/AllenInstitute/MIES/actions/runs/8660204778/job/23747647811?pr=2082 and https://github.com/AllenInstitute/MIES/actions/runs/8664937116/job/23763694979?pr=2041.
