### ISSUE TITLE
Add Menu Entry to toggle wave caching on/off

### ISSUE THREAD

**Issue by MichaelHuth** [AllenInstitute/MIES#2090]
Add a togglable menu entry to globally disable wave caching when enabled.

This helps testing in development where otherwise one would need to clear the cache on every attempt.

**Comment by t-b** [comment]
I'm not a fan of having more menu entries. We could add a define like DEBUGGING_ENABLED though with functions to enable/disable it. Feel free to tackle this.

**Comment by t-b** [comment]
Let's add this define.
