### ISSUE TITLE
NI hardware: Is it possible to control differennt channels independently?

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#2118]
We would for example like to stop DAQ on one headstage but continue on another. @MichaelHuth Can you have a look if the NIDAQ XOP allows that?

**Comment by MichaelHuth** [comment]
The NIDAQ XOP allows only stopping per device not per channel.

Leaving what the XOP exposes aside:
Looking at the NI hardware itself, some solution like that could be possible, depending on what NI hardware is used. The way would be to configure channels to separate clock sources/timers that can be stopped independently. These sources would need a single trigger for start. When configured the setup can not be changed dynamically and it needs to be known beforehand what channels should be stopped independently. Also there are about 8 times more channels than timers on e.g. PCIe-6343. Thus, the 32 channels could only have 4 independent clock sources.

**Comment by t-b** [comment]
@MichaelHuth Thanks!

**Comment by timjarsky** [comment]
Not possible. Closing
