### ISSUE TITLE
Add DA_Ephys checkbox to write data into separate NWB file

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#2127]
- Add setvariable string with pattern name, `%exp-%hw-%electrode`, (%exp: experiment name, %hw: hardware serial, %electrode: electrode name) current default being `%exp`
- Add NWB function to regenerate NWB file name
- Add GUI group for NWB settings

**Comment by t-b** [comment]
New solution: Always use one NWB file per device, see https://github.com/AllenInstitute/MIES/issues/978#issuecomment-2261163347.

**Comment by MichaelHuth** [comment]
For all data: NWB_ExportAllData

Per sweep: SWS_SaveAcquiredData through NWB_AppendSweepDuringDAQ
