### ISSUE TITLE
Adaptive supra bugs out

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#2129]
Link: https://aiephys.slack.com/archives/C06P3MYEV6H/p1716920346361379

- [x] Tim will upload the file

**Comment by t-b** [comment]
From QN24.26.009.20.07A.03.nwb:

```
  !!! Assertion FAILED !!!
  Message: "Non matching wave sizes"
  Please provide the following information if you contact the MIES developers:
  ################################
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Stacktrace:
  DQM_FIFOMonitor(...)#L159 [MIES_DataAcquisition_Multi.ipf]
DQM_StopDataAcq(...)#L347 [MIES_DataAcquisition_Multi.ipf]
SWS_SaveAcquiredData(...)#L69 [MIES_SweepSaving.ipf]
AS_HandlePossibleTransition(...)#L109 [MIES_AcquisitionStateHandling.ipf]
AFM_CallAnalysisFunctions(...)#L168 [MIES_AnalysisFunctionManagement.ipf]
PSQ_DAScale(...)#L3537 [MIES_AnalysisFunctions_PatchSeq.ipf]
PSQ_DS_EvaluateAdaptiveThresholdSweep(...)#L2408 [MIES_AnalysisFunctions_PatchSeq.ipf]
PSQ_DS_GatherFutureDAScalesAndFrequency(...)#L2605 [MIES_AnalysisFunctions_PatchSeq.ipf]
PSQ_DS_GatherOvershootCorrection(...)#L2215 [MIES_AnalysisFunctions_PatchSeq.ipf]
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Time: 2024-05-28T14:18:34-07:00
  Locked device: [ITC18USB_Dev_0]
  Current sweep: [40]
  DAQ: [DAQ_BG_MULTI_DEVICE]
  Testpulse: [TEST_PULSE_NOT_RUNNING]
  Experiment: 2024_05_28_140535 (Packed)
  Igor Pro version: 9.0.6.1 (56565)
  MIES version:
  Release_2.7_20230809-747-g0051442b3
Date and time of last commit: 2024-05-23T19:58:12+00:00
Submodule status:
 bcbf5729ee85da80ea0f14dd5a42b55ed8fda47e Packages/IPNWB (remotes/origin/HEAD)
 d229d451f35e88b8c38edb8c26533acfbc3fd10f Packages/doc/doxygen-filter-ipf (heads/main)
 d557db885f2077bb1998cf9ef938477881c44775 Packages/igortest (v1.10-11-gd557db8)
  ################################
```

In b5300a305 (PSQ_DS_GatherAndWriteFrequencyToLabnotebook: Don't calculate apfrequency with failing baseline QC, 2024-05-02) we skipped calculating the ap frequency if the baseline QC is failing.

But this hurts us later in PSQ_DS_GatherOvershootCorrection as we then realize that we have a different number of dascale values compared to the apfrequency values.

**Comment by timjarsky** [comment]
@t-b, should we only record DA scale values when passing QC?

**Comment by t-b** [comment]
> @t-b, should we only record DA scale values when sweeps pass QC?

We always gather the DA scale value in the labnotebook. This is independent of the analysis functions. I guess the needed change is to gather APFreq and DAscale value only for passing sweeps.

**Comment by t-b** [comment]
Observations:
- DAQ was stopped manually after sweep 40, ~4s after the first assertion.

**Comment by t-b** [comment]
The first analysis was wrong. The issue was that the currently displayed sweeps were changed but we assumed that it was not.
