### ISSUE TITLE
Allow start and end indexing stimulus set to be the same when TestPulse stimset is selected

### ISSUE THREAD

**Issue by timjarsky** [AllenInstitute/MIES#217]
When setting the `(first)` and `Indexing End set` to `TestPulse` the following error is returned:

`  (ITC1600_Dev_1) Please select a different indexing end setimset for DA channel 1 referenced by headstage 1`

**Comment by t-b** [comment]
Granted, that is a bug.

**Comment by t-b** [comment]
We want to allow that not only for `Testpulse` but for all stimsets. Add tests as well.

**Comment by t-b** [comment]
This error messages goes way back to e3d65245 (More thorough overall and headstage settings check, 2014-09-30).

@timjarsky What should be the behaviour if both stimsets are the same? Should it just do indexing for two stimsets? Or not do indexing for this channel?

**Comment by t-b** [comment]
Allow only for "TP during DAQ: channels, not for DAQ channels.

**Comment by t-b** [comment]
Completely ignore the "TP during DAQ" channels for locked/unlocked indexing.
