### ISSUE TITLE
Add procedure file for common TUFXOP tasks

### ISSUE THREAD

**Issue by MichaelHuth** [AllenInstitute/MIES#2236]
It turned out that some tasks when using the TUFXOP are rather generic.

e.g. attempting to retrieve a named storage and create it if it not exists.

We could wrap these tasks in an own procedure file and possibly later move that to the TUFXOP package as well.

**Comment by t-b** [comment]
I actually think that this is kind of already solved with the functions in MIES_ThreadsafeDataSharing.ipf or?

**Comment by MichaelHuth** [comment]
Yes, these functions solve that.
