### ISSUE TITLE
error: nwb_version "b'2.2.4'" is not a proper semantic version. See http://semver.org

### ISSUE THREAD

**Issue by nrsc** [AllenInstitute/MIES#2243]
Hello All, 

I've run a mass file conversion from pxp to nwbV2 using MEIS (2.7_20230809-990-ga2063f945), and eventually when trying to upload the nwb files as a dandiset I get an error during the validation.

The good folks over at dandi seem to think [issue](https://github.com/dandi/dandi-cli/issues/1485) is that the nwb version is being written as a `fixed length string` instead of a `variable length string` during the conversion, and this causes the nwb file to fail validation and file will not be uploaded to the server. 

Looks like I may have a quick fix to rewrite the `nwb_version` attribute as a variable length string, and I will follow up on that. 

Scott

**Comment by t-b** [comment]
This looks very similiar to https://github.com/NeurodataWithoutBorders/pynwb/issues/1668. I'll followup on the linked issue.

**Comment by nrsc** [comment]
Thank you @t-b. Did this as a mass convert from pxp using the [macro](https://alleninstitute.github.io/MIES/file/_m_i_e_s___mass_experiment_processing_8ipf.html) built into this version of MEIS. I have been interested though in why I am getting v2.2.4 out of the conversion given that nwb seems to be a few versions ahead of this one. Could that be part of the issue?

**Comment by t-b** [comment]
>  I have been interested though in why I am getting v2.2.4 out of the conversion given that nwb seems to be a few versions ahead of this one. Could that be part of the issue?

I don't think so as nothing in the nwb schema has changed in that regard. I'll chat with Tim about this issue here.

**Comment by t-b** [comment]
@nrsc We'll come up with a fix.

**Comment by t-b** [comment]
Note to self: `DisplayHelpTopic "HDF5 String Formats"`

**Comment by nrsc** [comment]
@t-b Thanks!
