### ISSUE TITLE
Procedure file error upon opening MEIS Version: 2.7_20230809-1062-g30ecdd8171

### ISSUE THREAD

**Issue by nrsc** [AllenInstitute/MIES#2263]
Hey @t-b. Got to update my MEIS version today in an attempt to run the mass export macro once more, and ran into a bug while opening MEIS.

Reinstalled MEIS to update to Version: 2.7_20230809-1062-g30ecdd8171. Acquired the latest executable from the [latest release](https://github.com/AllenInstitute/MIES/releases/tag/latest)
 
Some images of what happens:

![Screenshot from 2024-09-17 11-04-25](https://github.com/user-attachments/assets/17c1c016-eb18-4450-a1e9-78491a4a2653)
![Screenshot from 2024-09-17 11-07-02](https://github.com/user-attachments/assets/409d5bef-6fc6-4f2f-9963-a41319a90cfe)

Looks like a simple bug but seems like this causes the loading of the macro to fail.

Thanks,

Scott

**Comment by t-b** [comment]
Thanks for the report. Yes this looks broken. Can you try #2264 to see if that fixes the issue?

**Comment by nrsc** [comment]
Hey @t-b, just need a little guidance on getting the updated installer for use. Do I need to clone the repo [#2264](https://github.com/AllenInstitute/MIES/tree/bugfix/2264-mass-nwb-processing) and run the installer? Once cloned, which file do I run?

**Comment by t-b** [comment]
> Hey @t-b, just need a little guidance on getting the updated installer for use. Do I need to clone the repo [#2264](https://github.com/AllenInstitute/MIES/tree/bugfix/2264-mass-nwb-processing?rgh-link-date=2024-09-17T21%3A41%3A40Z) and run the installer? Once cloned, which file do I run?

You can just grab `BuildInstaller-user-assets` from https://github.com/AllenInstitute/MIES/actions/runs/10908843850?pr=2264, this zip contains the installer.

**Comment by nrsc** [comment]
Thanks @t-b. No problems running Igor this time. Running the mass export macro top check for dandi validation.

**Comment by t-b** [comment]
Glad to hear that IP compiles now.
