### ISSUE TITLE
SweepFormula: Automatic markers vs lines usage looks odd

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#2281]
>@t-b I'm seeing the data plotting style change in the middle of the plot. It seems like the method for changing the style depending on the number of points is being applied to the same plot

![image](https://github.com/user-attachments/assets/44f3e4dd-063a-48f1-bd1d-cbee132a71f5)

_Originally posted by @timjarsky in https://github.com/AllenInstitute/MIES/issues/2061#issuecomment-2364227815_

This is also the behaviour in main 818d5fcd3 (Merge pull request #2277 from AllenInstitute/bugfix/2277-make-tests-pass-with-ip10, 2024-10-14).

```
short = 1...250 * 2
long  = 1...2000

$short 

with

$long
```

gives

![grafik](https://github.com/user-attachments/assets/66fb82a8-2bca-4038-b72f-ee420d65caa0)

The reason for this is that we have a heuristic  to determine if we want to use markers or lines. We usually use markers for less than 1k points.

There is also the option to override the trace style per operation, e.g. we currently always use lines for `fit`. We could do the same for `data`

**Comment by timjarsky** [comment]
@t-b, thanks for creating the issue. I did not realize that contiguous epochs from the same sweep resulted in independent arrays/waves. What do you think about setting the trace style based on the amount of data/points from the same sweep?

**Comment by t-b** [comment]
> What do you think about setting the trace style based on the amount of data/points from the same sweep?

While technically possible, this is quite a bit off effort. Is there a case where you would like to have markers for sweep data? I think I'd always prefer line style.

**Comment by timjarsky** [comment]
Forcing line style for sweep data should have the same effect - I like it! Thanks @t-b
