### ISSUE TITLE
WAVE_LAYOUT_VERSION:1; pxp file incorrectly storing wave information

### ISSUE THREAD

**Issue by nrsc** [AllenInstitute/MIES#2283]
Recently updated MEIS to run mass covert macro of pxp to nwb files. Somewhere along the way, the format my waves are being stored as changed and epoch information is no longer written in the notes. 

![wave_layout_version_1](https://github.com/user-attachments/assets/6bd37994-51bc-4ce0-89f2-91568fc32690)

Trying to report the issue in IGOR using MEIS informs me that the NI-DAQ is not found, and returns the following in the terminal output.
```
Checking system properties:
  Igor 64bit: 9.06, 56565
  Microsoft Windows 10 Enterprise (22H2)
  ASLR: False (Nice!)
  
Checking known defines:
  DEBUGGING_ENABLED: No
  EVIL_KITTEN_EATING_MODE: No
  BACKGROUND_TASK_DEBUGGING: No
  THREADING_DISABLED: No
  
Checking base installation:
  Mies version info: Valid "Release_2.7_20230809-1063-gf79a9fa0a2..." (Nice!)
  ITC XOP: Found version 1.0.2.0 (Nice!)
  Axon Telegraph XOP: Found version 3.0.0.0 (Nice!)
  Multi Clamp Commander XOP: Found version 2.0.0.0 (Nice!)
  JSON XOP: Found version 1.0.0.1 (Nice!)
  ZeroMQ XOP: Found version 1.0.0.1 (Nice!)
  TUF XOP: Found version 1.0.0.1 (Nice!)
  MiesUtils XOP: Found version 1.0.0.1 (Nice!)
  NWBv2 compound XOP: Found version 1.0.0.1 (Nice!)
  JSON XOP: Present in the right version (version-892-g9251933) (Nice!)
  ITC2 XOP: Present in the right version (latest-174-gb9915a9) (Nice!)
  TUF XOP: Present in the right version (version-163-g686effb) (Nice!)
  Results: 10 checks, 0 number of errors
  
Checking extended installation:
  NI-DAQ MX XOP: The file NIDAQmx64.xop could not be found (Very Bad)
  Results: 1 checks, 1 number of errors
  Checking system properties:
  Igor 64bit: 9.06, 56565
  Microsoft Windows 10 Enterprise (22H2)
  ASLR: False (Nice!)
```

Thanks,

Scott

**Comment by t-b** [comment]
> epoch information is no longer written in the notes.

Yes we removed epoch information from the wave note as it was deemed to noisy. Epoch information is still present, e.g. select "Visualize Epochs" from the "Settings" tab.

All data in the wave note is also present in the labnoteobok.

**Comment by t-b** [comment]
@nrsc Does my above explanation make sense to you? And can I then close the ticket?

**Comment by nrsc** [comment]
Hi @t-b. Yes it does. Apologies I could have closed the comment. All the best.
