### ISSUE TITLE
PA plot: Speedup on fallback path with no pulse starting times

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#237]

**Comment by t-b** [comment]
Check with time aligment enabled as well.

**Comment by t-b** [comment]
Turns out the fallback path is not very slow.

**Comment by timjarsky** [comment]
> Turns out the fallback path is not very slow.

@t-b That's good, right? - Whatever speedup we implement will then be backward compatible?

**Comment by t-b** [comment]
@timjarsky Yes that is good!! We determined that the plotting is the main reason for the slowdown. So there is not much sense in tweaking the fallback path.
