### ISSUE TITLE
Allow the user to do basic analysis on sweeps

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#238]
User requirements:
- Select one x range per channel type (DA, AD, TTL) using cursor pairs
- View the results of `Wavestats` (mean, stddev, min, max), using either all properties, or selected ones, in a table where the results are displayed by channel/sweep and grouped by channel type
- Allow to plot different WaveStats properties against each other or against the sweep numbers
- We never mix data from different sweeps (for now)

Implementation:
- Add a new tab to the Databrowser/Sweepbrowser
- Use the current infrastructure for gathering trace infos -> `PA_GetTraceInfos`
- Create separate graphs for each plot, multiple graphs are already see "Export Traces"
- Table data and plots update automagically when the cursors are changed
- The created graph should have the formula shown so that the user can replicate it.
- Overlay sweeps

We serialize the GUI selections 

![grafik](https://user-images.githubusercontent.com/1185677/60838853-fc9b9b00-a1cb-11e9-92f5-cd44de60a534.png)

into formulas:

```igorpro
(Mean(Derivative((Cursors(AB), AD, "1;3")))-Mean([100ms, 200ms], AD)) vs (Max(Cursors(EF), DA) + Stddev(Cursors(GH), DA))
```

Where "1;3" is the range of sweeps, defaulting to all sweeps.
The sweep list can be also include "removed headstages". The syntax is "1[0,2];2;" which means that headstage 0 and 2 are removed from sweep 1 and all headstages are shown for sweep 2.
Sweeps 1 and 3 can have different x scaling and different number of points.

Further ideas:
- Seralize these formulas to a JSON file on disc, set the analysis type in the wavebuilder to a stimset and do the analysis automatically.

Known limitations:
- First version will only work with the databrowser as don't handle duplicated sweep numbers.

Data magnitudes:
- Up to 100 sweeps
- Up to 2e6 points per sweep
- At most 8 headstages per sweep

Related issue #38.

**Comment by ukos-git** [comment]
wave ranges in xscaling of "1;2" can have multiple different point sizes. No resampling to 2d-waves possible.

**Comment by ukos-git** [comment]
# Formula Parser

## tokenizer

- start token `(`
  * function name
  * parse parameters
    - token `,` next parameter
    - token `(` --> recurse
  * end token `)`

## parse formula to structured json

respect order of calculation: `*` > `+`

`min + max * sdev`

```json
[
  {
    "operator": "+",
    "function": "min",
    "range": [
      "-inf",
      "inf"
    ],
    "channelType": "AD",
    "sweepList": "1;2;3;"
  },
  [
    {
      "operator": "-",
      "function": "max",
      "range": [
        "-inf",
        "inf"
      ],
      "channelType": "AD",
      "sweepList": "1;2;3;"
    },
    {
      "operator": "*",
      "function": "sdev",
      "range": [
        "-inf",
        "inf"
      ],
      "channelType": "AD",
      "sweepList": "1;2;3;"
    }
  ]
]
```

## Parameters

- function name: `Mean`, `Derivative`, `Min`, `Max`
- range [start, end] (default to [-inf, inf]
- channelType (default from cursor)
- sweepList = "1;1[0,2];2;3[1]" with headstage removal in square brackets

# Formula Check

## check valid function names

define a list of valid functions like min,max, derivative

## check input wave type

3 types of input waves:

* multiple point sweep calculations (size(sweeplist), *arbitrary length* numpnts(sweep)) → WAVE of /WAVEs to account for different sweep sizes. return modified input wave
* one point functions (size(sweeplist), 1) storing the result of wavestats with size 1
* Cursor functions (2, 1)  returns [csr(N), csr(M)] for Cursor(NM)

FAIL for invalid input wave usage:

Mean(Derivative) →ok
Derivative(Mean) →fail

**Comment by t-b** [comment]
@timjarsky We've discussed how to tackle that today. We would leverage the new JSON XOP to use JSON as intermediate data structure for the parsed formula. This does require IP8 but we already agreed to switch to IP8 only IIRC.

**Comment by t-b** [comment]
@timjarsky Thx.

**Comment by ukos-git** [comment]
I consider using a variant of [json logic](http://jsonlogic.com/) for operations:

```json
{
  "+": [
    1,
    1
  ]
}
```

instead of the previous suggestion which would look more complicated:

```json
{
  "operator": "+",
  "operation": [
    1,
    1
  ]
}
```

**Comment by ukos-git** [comment]
so the syntax for a function call would be similar with the function name as group member.

```
{
  "min": {
    "function": "sdev",
    "range": [
      "-inf",
      "inf"
    ],
    "channelType": "AD",
    "sweepList": "1;2;3;"
  }
}
```

**Comment by t-b** [comment]
Don't forget the ignored headstages which probably means that sweeplist needs to be split up.

**Comment by ukos-git** [comment]
Other than json logic, I currently do not support more than 2 columns of operations:

supported:
```json
{
  "+": [
    1,
    1,
    1
  ]
}
```

That would make the parsing more complicated and I don't see the benefits, as we would need to create the equivivalent wrappers to `MatrixOp sumCols` for all other operations like columnwise multiplication etc.

You can still add formula like `1+1+1` but it will be calculated in two steps as `1+(1+1)`.

**Comment by timjarsky** [comment]
@ukos-git is it also possible to support channel number? e.g. AD2

**Comment by t-b** [comment]
@timjarsky channel numbers are not in the original proposal but we can certainly add them.

@ukos-git we have specified "ad" as all channels of type ad, now "ad2" would mean the obvious.

**Comment by ukos-git** [comment]
> Other than json logic, I currently do not support more than 2 columns of operations:

The multi-column approach is back for addition and multiplication with the current state machine code.

**Comment by ukos-git** [comment]
multi-columns now for all operations. For the inverse operations (-, /) the first element (dividend, minuend) is inverted. State Machine now fully working but uses lookaheads to determine get the order of calculation right.

**Comment by timjarsky** [comment]
@ukos-git @t-b regarding
```
operations possible on same type and mixed type input waves:

(min + max)
(min * derivative)
(derivative * derivative)
```

could we also support (in this PR or in the future) e.g.,  `max(derivative(AD))` and `max(derivative(derivative(AD))` and integral variations?

**Comment by ukos-git** [comment]
![Screenshot from 2019-09-06 01-08-23](https://user-images.githubusercontent.com/16167358/64389431-eaf73800-d042-11e9-84a0-fc2c3058899c.png)

concatenation of functions should not be a problem. I hope the formula parser is robust enough.
```
max(derivative(derivative(sweeps(cursors(A,B),channel(AD),0;1;2))))
```

There are still some issues. The most urgent is that
operations with sweeps like addition have to be reworked in another way. Calculating with 1dimensional arrays works, though, which means that you can use `min(sweeps(cursors(A,B),channel(AD),0;1;2))/2` but not `sweeps(cursors(A,B),channel(AD),0;1;2)/2`

Other minor issues are

* Add Integrate function
* allow white space in formula
* count correct bracket usages
* Automatically Add Cursors
* Add Curosr hooks
* Handle non-existing sweeps  returns (currently a null-waveref is returned which causes issues.
* Better Error Handling. Can we catch the ASSERTs somehow during parsing and execution?

JSON Logic has some additional elements that could come in useful: http://jsonlogic.com/operations.html
Please take a look and see if there is anything interesting that could help.

I would personally add an array creation operation (`…`) for an easier sweepList and sweepList should be an array then.

```
1…5 → [1,2,3,4,5]
```

I think, the [cat operation from JSON logic](http://jsonlogic.com/operations.html#cat) can come in handy from time which then would allow to use

`cat(1…5, :1) → ["1:1","2:1","3:1","4:1","5:1"]`

for convenien headstage selection or

```
cat(sweep, 1…5) → ["sweep1", "sweep2", "sweep3", "sweep4", "sweep5"]
```

for example to display `sweeps() vs cat(sweep, 1…5)`

**Comment by timjarsky** [comment]
@t-b if you have time tomorrow (Friday) could we test this together?

**Comment by t-b** [comment]
@timjarsky Yes I have time, how about 10am?

**Comment by timjarsky** [comment]
@t-b 10am will work. FYI the display button may be missing it's control action procedure.

**Comment by t-b** [comment]
@ukos-git Here is the whishlist of changes from the testing on friday.

Roughly in the order of importance:
- [ ] Error out on trying to use sweeps from different experiments (later addition perhaps)
- [ ] What happens if a specified sweep in the formula is not displayed? Do we
      error out, if not can we just add it using OVS and continue?
- [ ] One trace per channel number (i.e. if you have AD0 and AD9 shown in the
      data browser, we want to have two traces)
- [ ] one channel on one side -> plot each trace of the other side against that one channel.
      (aka All-To-One instead of the usual All-To-All).
- [ ] existing graphs are not handled properly (bug)
- [ ] explicit range (instead of cursors) with [xxx ms, yyy ms] does not work
- [ ] Convert sweep range ("1;2;3") to an array with `...` array creation
      support. Instead of `[1, 2, 3, 4]` one can write `[1...4]`.
      Allow for `[]` to mean all *displayed* sweeps, one can also use
      `[0...inf]` to mean all available sweeps.
- [ ] Reevaluate formula and update graph when new data arrives and "Display
      Next Sweep" is checked. (DB_UpdateToLastSweep is the entry point after
      acquiring and saving the sweep)
- [ ] Add rms and avg as operations
- [ ] add support for multiline formulas (notebook in GUI), formulas should
      ignore all whitespace (except EOLs for comments), `#` is the comment char
      (ignores everything until the end of the line). Use NormalizeToEOL as well to cope with all EOLs.
- [ ] Implement `area` instead of `integrate`
- [ ] Add `Butterworth` operation having (..., lowPassCutoff, highPassCutoff, order) parameters,
      see Wavebuilder and its use of FilterIIR
- [ ] Add automatic graph axis labels -> e.g. `min($unit)`, `min(a.u.)` if
      the units are not matching
- [ ] Add time operation which returns the x-values of its input

# NeedsMoreInfoTopics

- [ ] Add button to store the formula in as JSON file on disc. The idea is to
      be able to load it via the analysis browser and execute the analysis on multiple experiments.

Example:
```
  # save to JSON
  [
    "description" : "minimum",
    "formula" : "min(sweeps(cursors(A,B),channel(AD),[1...inf]))",
    "cursors" : [{A : "100ms"}, {B : "200ms"}],
    "sweeps" " [ 1, 2, 3],
    "experiment" : [ "filea.nwb", "fileb.nwb"]
  ,
    ...
  ]
```

- [ ] FindLevel

  how to pass the direction?
  how to pass failing/rising?
  findlevel(RMS(sweeps(cursors(A,B),channel(AD),3;4;5;6;7;8;9;10)), sweeps(cursors(C,D),channel(AD),3;4;5;6;7;8;9;10))

**Comment by ukos-git** [comment]
I kindly ask you to read the documentation that I added. https://github.com/AllenInstitute/MIES/pull/245/commits/61fd68aef6094b8e70e26567e45aa0b4eb2f671a

I will polish the GUI a bit more and do some fixups. I want to bring the remaining bullet points to separate issues to discuss the problems that are only solvable with more time on the associated PR.
We should first quit these remaining discussions before proceeding further and as there are 100+ issues open in MIES, 5 more should not be a problem.

I strongly recommend to finish the associated PR first. It is mainly data alignment problems that remain to get tackeled. e.g. derivative*data is not a problem but but normalizations using `data/max(data)` is currently undefined so we need some formula combinations from you @timjarsky and what should be the defined calculation result from it. Best with simple arrays using `range(0,100),range(0,200,2)` examples or so.

**Comment by ukos-git** [comment]
A few thing remain to be done in the MR:

- [ ] preserve wave scaling for all operations
- [ ] define the result of some concatenated operations to ensure that we use the right data alignment for these operations.

>  Add Curosr hooks

do we still need that?

> One trace per channel number (i.e. if you have AD0 and AD9 shown in the
data browser, we want to have two traces)

what was the problem with that again? On my end it was working since forever but maybe I need to test with the DataBrowser to see that.

>  FindLevel
> how to pass the direction?

Should I add the findlevel? - I really like `findpeak? more

> FindPeak [/B=box /I/M=minAmp /N/P/Q/R=(startX,endX )] waveName
> The FindPeak operation searches for a minimum or maximum by analyzing the smoothed first and second derivatives of the named wave. Information about the peak position, amplitude, and width are returned in the output variables.

**Comment by t-b** [comment]
min/max has already the correct alignment of data. Mean got it wrong. I'll add some parametric tests to get test it and fix it then.
