### ISSUE TITLE
Allow BrowserSettingsPanel To Update Without Closing DB/SB

### ISSUE THREAD

**Issue by ukos-git** [AllenInstitute/MIES#268]
If the BSP is in an old version, the SB/DB needs to be closed in order to get the new updated panel. This is inconvenient if the SB graph is already in use in the experiment and the source of the data would need to get reloaded from AB on SB close.

An update to the new panel version using `BSP_OpenSettingsPanel` is hard to do manually since the BSP can not get closed normally but is hidden on default.

```
	NewPanel/HOST=SweepBrowser1/EXT=1/W=(366,0,0,407)/N=BrowserSettingsPanel  as " "
	Execute "BrowserSettingsPanel()"
	BSP_DynamicStartupSettings("SweepBrowser1")
```

**Comment by t-b** [comment]
Recipe:
- Data from https://github.com/AllenInstitute/MIES/pull/245#issuecomment-532908981
- Open experiment
- BSP panel is out of date
- Closing the sweepbrowser will kill the data and it is then very difficult to recreate it properly

**Comment by ukos-git** [comment]
- Programmatically Remove Panel Hooks
- Kill old Panel
- Recreate new Panel

**Comment by t-b** [comment]
A workaround is to enable evil mode once #597 is merged.
