### ISSUE TITLE
SweepFormula:  area function

### ISSUE THREAD

**Issue by ukos-git** [AllenInstitute/MIES#269]
The `area` function should get implemented instead of the `Integrate` operation.

From my basic understanding, there is only disadvantages from implementing `area` instead of `integrate`. Both can do trapezoid integration but area is much more primitive. e.g. it can not handle dimension-based operation, does not do end-point filling and thus looses the data alignmen, shifting the x-values by one point and introduces `NaN` at the end.

I am not a fan of end point guessing either but we can also deactivate such feature for differentiate and integrate which then allows to have the above described behavior also for our functions but the user must be aware that multiplying e.g. `integrate(data))*data()` can lead to strange results.

The IP area function:

> area(waveName  [, x1, x2  ] )
> The area function returns the signed area between the named wave and the line y=0 from x=x1  to x=x2  using trapezoidal integration, accounting for the wave's X scaling. If your data are in the form of an XY pair of waves, see areaXY.

The IP Integrate Operation

> Integrate [/DIM = d  /METH=m  /P/T][typeFlags ] yWaveA  [/X = xWaveA ][/D = destWaveA ] [, yWaveB  [/X = xWaveB ][/D = destWaveB ][, ...]]
> The Integrate operation calculates the 1D numeric integral of a wave. The X scaling of each wave is taken into account. Rectangular integration is used by default.
> Integrate is multi-dimension-aware in the sense that it computes a 1D integration along the single dimension specified by the /DIM flag or along the rows dimension if you omit /DIM.

 steps to integrate area

- reduce 2d input waves to 1d waves.
- determine calculation x-ranges for all columns using `ScaleToIndex` and `DimSize` splitting
- use area in a for loop
- assemble the result to a new wave
- transfer wave scaling

#238

**Comment by timjarsky** [comment]
`area` should return the last value of the `integrate` array.  This is zeroed already.

**Comment by t-b** [comment]
Closed via #578.
