### ISSUE TITLE
SweepFormula: Allow NULL and "Inf"

### ISSUE THREAD

**Issue by ukos-git** [AllenInstitute/MIES#270]
Theere is a request #238 for an operation to allow inputs like `[]` and `[0...Inf]` for the sweep() operation in the sweep formula.

currently, [] is `[null]` which is caused by recursive expansion of a nullstring inside an array.

To support `null` that would mean a major rewrite of the recursion patter of the formula parser, as `null` was not integrated in our design specifications. A new JSON object is always a null object whch makes it hard but it is possible.

`NaN` and `Inf` were also not considered in the specification. It should be noted that they are no RFC compatible numbers but are rather treated as text. They were not supported in the initial version but that is mostly not a parsing issue, as the last element recursion works just fine for such text items. The major problem here is the expansion of mixed type arrays. If arrays contain text and numbers mixed, I added an ASSERT, as we can usually neither read it as numeric nor as text wave without errors. That is of course not the case for nan and inf but the routine has to be adapted with a try--catch statement to try to read as a numeric array and bail out on failures.

The transfer of `null` → `NaN` and `"Inf"`  →inf to `GetSweepForFormula` and handling that in the `Extract` statement should be a one-liner.

**Comment by timjarsky** [comment]
Not required.
