### ISSUE TITLE
SweepFormula: Add sweeps mentioned in formula to OVS

### ISSUE THREAD

**Issue by ukos-git** [AllenInstitute/MIES#271]
#238 asks to handle non-existing sweeps in the SweepFormula

Currently, given that sweeps 1;2;3 are displayed, a call to `data()` using `sweeps(1...5)` wants to include sweep 4 which is ignored by the extract statement in `GetSweepForFormula`.

The approach to automatically activate the sweep in the `OVS` panel is magic and should be user-controllable by a checkbox in the SweepFormula GUI. It could add unwanted behaviour. Say for example, you did deactivate sweep 4 in OVS as there was a measurement flaw, The SweepFormula would automagically update the controls each time it is executed.

In my approach of GUI design, I usually do not try to alter user input fields as I find it annoying if programs correct what I previously activated/deactivated on purpose. Adding magic is often something that doesn't make your life easier, so I would make that optional behavior.

We can also add an ASSERT for unmatched sweeps from the formula. I personally don't mind, if a sweep is not found. I like it a lot to just say sweeps(1...1e4) to get all sweeps, even if they are only `[1,2,3,4]`. Should I error out here instead?

**Comment by ukos-git** [comment]
@t-b As discussed, a solution that does not involve magic to the GUI would be the following in 
6fc20be 

```
data(
	cursors(A,B),
	channels(AD),
	sweeps()
)
```

the `sweeps()` function now gets all sweeps that were selected from the OVS panel. If OVS is off, it returns all available sweeps.

To force getting all sweeps with OVS on, you can use `allSweeps()`.

The previous `sweeps` function only converted a list to an array, so I renamed it to `listToArray()`. This means that sweeps can get entered the following way:

Always get all sweeps:

```
data(
	cursors(A,B),
	channels(AD),
	allSweeps()
)
```

as operation that returns an array

```
data(
	cursors(A,B),
	channels(AD),
	1…10
)
```

as function that returns an array

```
data(
	cursors(A,B),
	channels(AD),
	range(10)
)
```

as list


```
data(
	cursors(A,B),
	channels(AD),
	listToArray(1;2;3)
)
```

as a plain array

```
data(
	cursors(A,B),
	channels(AD),
	[1,2,5,6]
)
```

**Comment by ukos-git** [comment]
Should we rename the operation `displayed` instead of `sweeps`?

**Comment by t-b** [comment]
@ukos-git I'll check with Tim.

**Comment by timjarsky** [comment]
Does not need to be solved now in general. But we should warn the user if one of the sweeps does not exist.

**Comment by t-b** [comment]
Not doing that for now.
