### ISSUE TITLE
SweepFormula: Add graph axis labels

### ISSUE THREAD

**Issue by ukos-git** [AllenInstitute/MIES#272]
#238 asks to add graph axis labels.

My approach would be to alter the unit in the returned dataset to include the function.

`derivative(data())` would then give `d/dx()`

and

`min(derivative(data()))` would then give `min(d/dx())`

The data function can also be used then initiate the inner string. In this manner, every calculation step that was performed to the data can be stored.

The combination should also be possible e.g. min(min(data),max(data))

Instead of storing the string in the unit, we would need to store it in the WAVE`s userdata or wavenote.

The approach requires that all operations preserve wave scaling and could be an easy test for flaws if not. e.g. MatrixOP or Differentiate usually don't preserve the scaling.

**Comment by timjarsky** [comment]
Note to Thomas: Check with Matthias how much work it is.

**Comment by MichaelHuth** [comment]
Usually if we have a R x N x M wave with data in rows and then channel x sweeps, we should use for 
R = 1: SetScale d, 0, 0, "Y-units", wave
R > 1: SetScale d, 0, 0, "Y-units", wave; SetScale x, 0, 0, "X-units", wave
