### ISSUE TITLE
SweepFormula: Store/Load

### ISSUE THREAD

**Issue by ukos-git** [AllenInstitute/MIES#273]
#238 asks to store the JSON file on disk and load it again.

I would recommend to have a centralized database for formulas somewhere instead of a local folder. Maybe a quick PHP or JS server that accepts API calls to store/load formulas.

I also like the approach of storing the formula result as data entry for the object. Plotting with the JSON file using Plotly on the server should not be too difficult.

The problem with loading parsed formulas is that a routine needs to get written to parse a JSON logic formatted formula back to a Text formula. So that should be avoided unless really needed.

Example:
```
  # save to JSON
  [
    "description" : "minimum",
    "formula" : "min(sweeps(cursors(A,B),channel(AD),[1...inf]))",
    "cursors" : [{A : "100ms"}, {B : "200ms"}],
    "sweeps" " [ 1, 2, 3],
    "experiment" : [ "filea.nwb", "fileb.nwb"]
  ,
    ...
  ]
```

**Comment by timjarsky** [comment]
@t-b Would you update this issue to reflect our most recent chat (let me know if I can help). I'm going to move it to current tasks.

**Comment by t-b** [comment]
@timjarsky 
So here is a preliminary specification for the JSON files storing the formulas. I've restricted it to one formula per file just to keep it simple. But if we want we can have an outer array as well and allow multiple formulas in a file.
It is already prepared for formulas referencing sweeps across experiments as we store the name of the experiment as well.

```json
{
  "version": 1,
  "name": "I'm showing some sweeps",
  "formula": "data(cursors(A,B),channels(AD),sweeps())",
  "graph": {
    "cursors": [
      {
        "name": "A",
        "xposition": "100",
        "trace": "trace4711"
      },
      {
        "name": "B",
        "xposition": "200",
        "trace": "trace4711"
      }
    ],
    "displayed": [
      {
        "experiment": "2019-10-29-175546.nwb",
        "sweeps": [
          1,
          3,
          80
        ]
      }
    ]
  }
}
```

Mandatory elements:
- version
- formula

Optional elements:
- graph
- cursors
- displayed

If cursors/displayed is present it must have all sub paths from the example.

It will be added to the databrowser/sweepbrowser. And could look like

![grafik](https://user-images.githubusercontent.com/1185677/67809578-39e8a900-fa99-11e9-8190-d762788d7ba9.png)

**Comment by timjarsky** [comment]
@t-b what does the JSON look like when the user provides lists for the `data` arguments? Does it contain redundant info? I find myself wondering if the saved formula should avoid cursors, sweeps, and the like and use the lists?

I'm envisioning two common saving workflows: (1)  user opens several experiments/sweep-browsers and applies the same formula to different data. The user then saves each SF to the same text file. (2) The user applies different formulas to the same experiment/sweep-browser and wants to save the analysis in a single text file.

It's easy for me to imagine what the analysis browser does for case (1) text files,  but I'm not sure what would happen in case (2). Does it open multiple sweep browsers with different subsets of the data from a single experiment?

**Comment by t-b** [comment]
@timjarsky I've updated my post to reflect our earlier discussion.

**Comment by timjarsky** [comment]
@t-b 

> my post

= https://github.com/AllenInstitute/MIES/issues/273#issuecomment-547631881 ?

For me, I think it would be helpful if there was a verbose description of how the example JSON file is created by the user and the behavior when loading the file BUT just let me know if you want to have that documented somewhere else.

**Comment by t-b** [comment]
Closing for now.
