### ISSUE TITLE
SweepFormua: Object evaluation for Strings

### ISSUE THREAD

**Issue by ukos-git** [AllenInstitute/MIES#274]
In #238 suggested to add [concatenate operation](http://jsonlogic.com/operations.html#cat) from jsonlogic.

```
cat(1…5, :1) → ["1:1","2:1","3:1","4:1","5:1"]
cat(sweep, 1…5) → ["sweep1", "sweep2", "sweep3", "sweep4", "sweep5"]
```

This would need the String array to get get object evaluation and mixed array support.

I tried with a simple `str()` operation to convert a numeric array to strings but that is not enough. There will need to be a major rewrite of the object evalutaion section of the `FormulaExecutor`. As the operation is not crucial, I decided against it.

**Comment by timjarsky** [comment]
Note to self: Chat with Matthias about this.

**Comment by t-b** [comment]
Postponing for now.
