### ISSUE TITLE
SweepFormula: Error Handling

### ISSUE THREAD

**Issue by ukos-git** [AllenInstitute/MIES#275]
Currently, Aborts are used to quickly bail out of the parser on error. This is a better approach than asserts for the parser, as it is not technically a program failure at that point if the user e.g. forgot to add a closing bracket.

At the point of the Parser we do not have Variables space to write to but I would really also like to add line number/position of the parsing error and highlight that in the formula window.

Adding `AbortOnValue` here would be great but It requires that the Abort is catched, which it was not in my tests.

First thing to do:
- Don't use `ASSERT`
- Don't use dialogs like in bracket mismatch
- Better error messagrs for bracket mismatch

**Comment by ukos-git** [comment]
see error handling in https://github.com/AllenInstitute/MIES/pull/245 ae78b0b5dd196da491acffaf54d7afc1f135fbe9

**Comment by MichaelHuth** [comment]
```
try
	string stackInfo = GetRTStackInfo(3); AbortOnValue 1, str2num(StringFromList(0, StringFromList(ItemsInList(stackInfo, ",") - 1, stackInfo, ",")))
catch
	variable err = GetRTError(1)
	print "Abort in line:", V_AbortCode
endtry
End
```

Works fine here.

**Comment by ukos-git** [comment]
probably like that for me:

```igorpro

Function parser()
	AbortOnValue (1 == 2), 1
	AbortOnValue (1 != 2), 2
End

Function handler()
	try
		parser(); AbortOnRTE
		print "error executing try"
	catch
		variable err = GetRTError(1)
		print "AbortCode:", V_AbortCode
	endtry
End
```

**Comment by ukos-git** [comment]
I probably misinterpreted the term *abort condition* and thought it was vice versa.

**Comment by t-b** [comment]
@timjarsky The issue here is about how we do the error handling. For not stopping ongoing DAQ you need https://github.com/AllenInstitute/MIES/pull/324 (and a turned off debugger).
