### ISSUE TITLE
SweepFormula: add data as variables

### ISSUE THREAD

**Issue by ukos-git** [AllenInstitute/MIES#276]
Similar to JSON logic, the data should get separated from the operations. This ensures that we do not call the getter two times if for example, calculating with it.

`derivative(data(cursors(a,b), channels(AD), sweeps())) * data(cursors(a,b), channels(AD), sweeps())`

will then reduce to

`derivative(var0)*var0`

with the data object

`var0=data(cursors(a,b), channels(AD), sweeps());`

 It can also mean that the functions are a lot easier to read. and you can name the data.

To get to that point, string values need to get checked if a variable is registered for them. Probably related to #274 

I don't see significant problems implementing that.

**Comment by ukos-git** [comment]
http://jsonlogic.com/

**Comment by t-b** [comment]
- data will be defined in separate notebook
- will make it faster

**Comment by ukos-git** [comment]
From the json logic documentation about the `var` operation:

logic:

```json
{ "and" : [
  {"<" : [ { "var" : "temp" }, 110 ]},
  {"==" : [ { "var" : "pie.filling" }, "apple" ] }
] };
```
data:
```json
{ "temp" : 100, "pie" : { "filling" : "apple" } }
```

should return `true` aka `1`

**Comment by t-b** [comment]
Example:
```
currSel = select(channels(AD9), [31,33,34], all)
myrange = [2000,4000]
kernel = epspKernel(myrange, currSel)

epsp(kernel, 0.6, 3, (-6)), 0.04, 550, 0)

and

epspStats(myrange, currSel, tau, accept, hist)
```

Questions:
- Do we need to mark named entities? With `$`?
- Needs to be known across all `with` and `and` parts
- No partial expression support
