### ISSUE TITLE
SweepFormula: Support minus as sign in the parser (and therefore don't require parantheses)

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#278]
```igorpro
•print FormulaExecutor(FormulaParser("-min([0, 1])"))[0]
  -1
•print FormulaExecutor(FormulaParser("+min([0, -1])"))[0]
  0
```

that is not what you expect. Using `58f24b8a (UTF_SweepFormula: Use module definition and make the functions static, 2019-09-21)`.

**Comment by ukos-git** [comment]
Do you check for dimsize(wv, cols)== 1 or ==0. 

I could explain in more detail, bit I think, the array expansion will give a column wave. You could also redimension directly after the expansion.

**Comment by ukos-git** [comment]
I don‘t consider it a bug if you want to have column evaluation.

**Comment by ukos-git** [comment]
Remember that -1 is not numeric but an object

**Comment by ukos-git** [comment]
Why don‘t you just use (-1)*min(0,1)

**Comment by ukos-git** [comment]
the actual problem that you describe is simpler than your example.

`min(0,-1)` currently gives

```json
{
  "min": [
    0,
    1
  ]
}
```

**Comment by ukos-git** [comment]
what do you suggest for solving the `-1` problems?

**Comment by ukos-git** [comment]
Personally, I recommend to always encapsulate `-1` in brackets.

**Comment by ukos-git** [comment]
currently failing evaluations:

`1+-1`
```
{
  "+": [
    1,
    1
  ]
}
```

`-1*2`

```
{
  "-": [
    {
      "*": [
        1,
        2
      ]
    }
  ]
}
```

`2+-1*3`

```json
{
  "+": [
    2,
    {
      "*": [
        1,
        3
      ]
    }
  ]
}
```

non-first array elements:

`[1, 0, -1]`

```
[
  1,
  0,
  1
]
```

`-1 - 1`

```
{
  "-": [
    1,
    1
  ]
}
```

**Comment by t-b** [comment]
- [ ] Add Tests which check that the wave scaling is preserved

**Comment by ukos-git** [comment]
That is a bug in the parser. I don‘t have time to fix parser issues this month. Can you open an issue? It should be of no particular relevance to our use scenario but definitively needs a fix.

**Comment by ukos-git** [comment]
I think, such checks for invalid syntax should go to the preparser. But we could probanly also catch it in the parser.

**Comment by t-b** [comment]
@ukos-git Collecting them here sounds good!
