### ISSUE TITLE
SweepFormula: Allow multiplication of 1D with 2D data

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#282]

**Comment by t-b** [comment]
Both

```
[[0, 1, 2, 3]]
```

and

```
[0, 1, 2, 3]
```

give a 1D wave with 4 rows.

```
[[0, 1, 2, 3], 4]
```
gives a 2D wave with 2 rows and 4 columns.

Discuss that as it is different compared to what is done in IP. 

```igorpro
Make/o data = {{0, 1, 2, 3}, {4, 5, 6, 7}}
```

gives 4 rows and 2 columns.

**Comment by t-b** [comment]
Mixing 1D and 2D data:

```
[1,2,3,4,5,6,7,8,9,10]

*

data([1000,2200],
channels(AD0),
range(128,137,1))
```

currently fails.

**Comment by ukos-git** [comment]
> ```
> [[0, 1, 2, 3]]
> ```

not implemented

**Comment by t-b** [comment]
Solution:
- Implement `applyOnColumns` for `*` and `/`. Think about its name again.
- Add syntactic sugar for a shorter way to write it. Maybe `x` for `applyOnColumns(..., *, ...)`.

**Comment by t-b** [comment]
Closing for now.
