### ISSUE TITLE
SweepFormula: Code cleanup

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#294]
- [x] Use `SF` prefix, add file level doxygen comment
- [x] Add `AutomatedTesting` define testing magic
- [x] Avoid globals for controls
- [x] Make functions static
- [x] Add function comments
- [x] Prefer `IsEmpty` over `cmpstr($A, "")`
- [x] Don't create waves in cdf, use wave getters as well

- [ ] ~~Externalize help notebook into file on disc for easier editing. Place that into `Packages/MIES` so that we don't have to touch the installer. Maybe worth fixing https://github.com/AllenInstitute/MIES/issues/299 with that as well.~~ Externalizing the help notebook is not possible.

**Comment by ukos-git** [comment]
test failure is fixed in the PR.
