### ISSUE TITLE
SweepFormula: Investigate setscale issues and add tests

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#295]
Documentation had this one here

```
.. note::

   It can currently not be used reliably due to an unfixed Igor Bug. As soon as
   this fuction is fixed, it should be secured with unit tests.
```

**Comment by ukos-git** [comment]
should be fixed. @MichaelHuth advised to add the `/P` flag.

You can not scale dimensions of size `0`, though. Which is unconvenient behavior of the `SetScale` function
