### ISSUE TITLE
Add support for time alignment in pulse average graphs

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#30]

**Comment by timjarsky** [comment]
@t-b Let's raise the priority of this issue now that https://github.com/AllenInstitute/MIES/issues/26 is complete.

**Comment by t-b** [comment]
See function `TimeAlignmentIfReq`.

**Comment by ukos-git** [comment]
should this also work with DataBrowser?

**Comment by t-b** [comment]
@ukos-git Compare to only the sweepbrowser? It should work with both sweep and databrowser.
