### ISSUE TITLE
SweepFormula: Allow analysis on data from multiple experiments

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#310]
- The user wants to do analysis not only on data from a sweep browser but also from data available from the analysis browser only.
- She wants to redo analysis from one set of data, on another set of data.

Proposal:
- Have a separate panel for the SweepFormula which is independent from the SweepBrowser
- Add a way to specify the experiment name

If we add the possibility to specify data in a separate notebook, see https://github.com/AllenInstitute/MIES/issues/276, we could allow for defining something like

data notebook:
```
range_a = [500, 770]
data_list = function([[range_a, channels(AD), [mypath:myfile_b.pxp, 0..10]],
             [range_a, channels(AD), [mypath:myfile_a.pxp, 3..10]]])
```

formula notebook:
```
min(data_list)
```

**Comment by timjarsky** [comment]
@t-b feel free to think about / implement a method to make it easy for the user to provide/get the file path information from the experiment they are working in. I'd like to avoid, where possible, manual entry of the file path.

**Comment by timjarsky** [comment]
This will also allow us to define a range from a findlevel result

```
lvl = findlevel(...)
range_a = range(lvl - 100, lvl+100, 0.1)
```

**Comment by t-b** [comment]
Duplicate of https://github.com/AllenInstitute/MIES/issues/273.
