### ISSUE TITLE
SweepFormula: Don't use standard assertions

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#325]
I think the assertion print[1] is still too much; especially considering the default entry in the SF  window is the cause.

[1]
  ################################
  !!! Assertion FAILED !!!
  Message: "Undefined argument"
  Please provide the following information if you contact the MIES developers:
  ################################
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Stacktrace:
DQM_FIFOMonitor(...)#L104 [MIES_DataAcquisition_Multi.ipf]
DQM_StopDataAcq(...)#L358 [MIES_DataAcquisition_Multi.ipf]
SWS_SaveAcquiredData(...)#L57 [MIES_SweepSaving.ipf]
SWS_AfterSweepDataSaveHook(...)#L85 [MIES_SweepSaving.ipf]
DB_UpdateToLastSweep(...)#L587 [MIES_DataBrowser.ipf]
PGC_SetAndActivateControl(...)#L227 [MIES_ProgrammaticGUIControl.ipf]
SF_button_sweepFormula_display(...)#L1090 [MIES_SweepFormula.ipf]
SF_FormulaPlotter(...)#L787 [MIES_SweepFormula.ipf]
SF_FormulaExecutor(...)#L697 [MIES_SweepFormula.ipf]
SF_FormulaExecutor(...)#L672 [MIES_SweepFormula.ipf]
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Time: 2019-10-17T12:13:52-07:00
  Locked device: [ITC1600_Dev_1]
  Current sweep: [3]
  DAQ: [DAQ_BG_MULTI_DEVICE]
  Testpulse: [TEST_PULSE_NOT_RUNNING]
  Experiment: 2019_10_17_121222.pxp
  Igor Pro version: 8.0.4.2 (34528)
  MIES version:
  Release_2.0_20190602-355-g8929fce5
Date and time of last commit: 2019-10-17T20:14:35+02:00
Submodule status: 
160000 550cea2cd1e7e77cb7b7396bb9a536f805f6a889 0	Packages/IPNWB
160000 7b6d2115733523463bb9d0250cee38a41a88d8b3 0	Packages/ITCXOP2
160000 aa1858d915ee28ebf5974f59f0bc19a421e5c28e 0	Packages/ZeroMQ
160000 da79879e19e6467daa58fb075f8428ae15df2061 0	Packages/doc/doxygen-filter-ipf
160000 a097151fbc9a8a8f2e504c9e46adcb327a19c8f3 0	Packages/unit-testing
  ################################

_Originally posted by @timjarsky in https://github.com/AllenInstitute/MIES/pull/324#issuecomment-543321382_

**Comment by t-b** [comment]
@timjarsky How about we add an optional parameter `quiet` to ASSERT which would keep the command history untainted? In that way we can use our default ASSERT commands but the user is not annoyed. We can even have a wrapper like `ASSERT_QUIET`.

**Comment by timjarsky** [comment]
> @timjarsky How about we add an optional parameter `quiet` to ASSERT which would keep the command history untainted? In that way we can use our default ASSERT commands but the user is not annoyed. We can even have a wrapper like `ASSERT_QUIET`.

@t-b if the debugger is on, would the assertion still be quiet? My preference would be that with the debugger on, the history would have a record of the assertion. My preference isn't very strong.

**Comment by t-b** [comment]
@timjarsky I'll think about it.

**Comment by ukos-git** [comment]
These `ASSERT`s are not really program bugs in this case. I tried to use `DebugPrint()` for most of the messages but that is probably only active for devs. Although I don't like popups at all, I would recommend a `DoAlert 0, "message"` based exception to notify the user that something went wrong on his end which needs attention.

Another more solid way would be to write a log file to a specific object saving the stack trace. This object can then be queried to get the latest status messages of the currently called function.

```
AppendLog(message)
RetrieveLog(function, message, limit = 1)
```

The log can be stored e.g. as text wave in `root:MIES:logfile` and could get different log levels to indicate if it is a warning, or an error.

**Comment by t-b** [comment]
Closing in favour of #275.
