### ISSUE TITLE
SweepFormula Plotting

### ISSUE THREAD

**Issue by ukos-git** [AllenInstitute/MIES#328]
Plotting of yFormula vs xFormula for different channel selections leads to misbehavior:

if AD contains AD0 and AD9 and DA contains DA4, AD has double the points than DA.

Plotting should continue until all data points from AD are plotted so that AD0 vs DA4 and AD9 vs DA4 are visible.

> An example file is on the FTP "potentially_mixed_AD_chan_in_SF.pxp". The user wants to have separate traces for the channels. Also, "channels(AD)" looks strange compared to "AD0" or "AD9".

_Originally posted by @t-b in https://github.com/AllenInstitute/MIES/issues/286#issuecomment-535152733_

The debug error should be better visible if DA and AD are not a multiple of their points. I.e., 49 points cannot be plotted against 51 points in the second (data) dimension.

**Comment by ukos-git** [comment]
To wrap this problem up in a mwe:

you want to plot

```
range(10) vs range(5)
```

and this should give (10/2) == 2 traces. Previously such missaligned data was not handled.

**Comment by ukos-git** [comment]
The solution in #341 is what you need.

A proper solution to this problem would have been to define min/max/avg for data waves with channel information, take care that the dimensionality is preserved and also preserve channel information for inputs like `channels(AD)` which should lead to the same output as `channels(AD1,AD9)` at channel evaluation level.

Such an extension to handling 3d waves, however, requires the definition of data operations by the user and will be a lot of work. I am not sure, however, if the user will see the difference as we currently do not have any functionality that requires preserving channel information.

**Comment by t-b** [comment]
@ukos-git Thanks, I'll look into it.

**Comment by t-b** [comment]
Closed via #341.
