### ISSUE TITLE
SweepFormula: Think about syntax to operate on rows not columns

### ISSUE THREAD

**Issue by timjarsky** [AllenInstitute/MIES#329]
allow the user to average multiple waves together in the sweep formula plot.
```
e.g., average(data([0,1000], channels(AD0), [5,6])
```
average(data(0,inf), channels(AD), sweeps()) would look the same as the result of the average feature built into the DB

**Comment by t-b** [comment]
@timjarsky Does our `avg/mean` currently not do what you need? See https://alleninstitute.github.io/MIES/SweepFormula.html#avg-and-mean?

**Comment by timjarsky** [comment]
@t-b the current avg/mean returns a single value. The new feature I'm requesting would return a wave, that is the average of several, user defined, waves.

**Comment by t-b** [comment]
@timjarsky Got it

**Comment by t-b** [comment]
User sometimes want to average sweeps like we do with the purple curve. We need to think about a good syntax to distinguish between operating over columns (not mixing different sweeps) and rows (mixing different sweeps). Currently avg and friends all operate on columns.

**Comment by t-b** [comment]
Reopening as that came up again while testing #1372.
