### ISSUE TITLE
SweepFormula MoveToTrash behavior

### ISSUE THREAD

**Issue by ukos-git** [AllenInstitute/MIES#351]
I want to discuss the behavior introduced in ee3f8d46070f7306f1c915be4e5564487bc5bcb7

Previously, the `Duplicate` would have overwritten the `sweepFormulaY` and `sweepFormulaX` waves which was convenient when having them opened in a "Edit" window.

ee3f8d46070f7306f1c915be4e5564487bc5bcb7 changes this and uses the `KillOrMovetoTrash` behavior which leads to the problem that an open "Edit" window does not show the current outputs of a new sweep formula.

@t-b Was it intended to move the waves to trash before rebuilding the new formula or is this an accident?

![sweepformula](https://user-images.githubusercontent.com/16167358/68144301-a9e0ae80-ff33-11e9-9b97-8532c0246a87.gif)

**Comment by ukos-git** [comment]
suggestion: use `Duplicate` here instead of `MoveWaveWithOverwrite(wvX, wv)`

**Comment by t-b** [comment]
@ukos-git We can use `Duplicate` for now as well.
