### ISSUE TITLE
SweepFormula: Mixed Text/Numeric Array possibility to allow

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#385]
For things like `findlevel` or `apfrequency` it would be nice to be able to mix numeric and string arguments.

Currently if I do

```
[1, test]
```

I get

```
  !!! Assertion FAILED !!!
  Message: "Object evaluation For Mixed Text/Numeric Arrays Is Not Allowed"
  Please provide the following information if you contact the MIES developers:
  ################################
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Stacktrace:
SF_button_sweepFormula_display(...)#L1194 [MIES_SweepFormula.ipf]
SF_FormulaPlotter(...)#L863 [MIES_SweepFormula.ipf]
SF_FormulaExecutor(...)#L380 [MIES_SweepFormula.ipf]
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Time: 2019-11-24T01:14:43+01:00
  Locked device: [- none -]
  Current sweep: [- none -]
  DAQ: [- none -]
  Testpulse: [- none -]
  Experiment: apfrequency.pxp
  Igor Pro version: 8.0.4.2 (34722)
  MIES version:
  ################################
```

**Comment by ukos-git** [comment]
You need to prevent automatic array evaluation

https://github.com/AllenInstitute/MIES/blob/47a4a131d31f54281e27e92f4267bce2f82ed4e0/Packages/MIES/MIES_SweepFormula.ipf#L444-L445

and need to specify the type for each argument individually

https://github.com/AllenInstitute/MIES/blob/47a4a131d31f54281e27e92f4267bce2f82ed4e0/Packages/MIES/MIES_SweepFormula.ipf#L758-L759

but you cannot create a mixed text/numeric wave as return value.

**Comment by t-b** [comment]
@ukos-git Could you provide an example for the operation `mytest(1, SOME_PARAM)`?

**Comment by ukos-git** [comment]
there are plenty of examples already in the code.

```
 case "findlevel": 
 case "mytest": 
 	break 

```

```
 			WAVE param1 = SF_FormulaExecutor(jsonID, jsonPath = jsonPath + "/0") 
 			WAVE/T param2 = SF_FormulaExecutor(jsonID, jsonPath = jsonPath + "/1") 
```
