### ISSUE TITLE
Configuration: Support multiple JSON config files which are applied to the same panel

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#396]
`XXX.json`  is the master file and `XXX_rig.json` is the per rig (aka user) file. Abort on duplicated entries.

Sample rig file:

```
{
    "Common configuration data": {
        "Headstage Association": {
            "0": {
                "Amplifier Serial": 0,
                "Amplifier Title": "0,1"
            },
            "1": {
                "Amplifier Serial": 0,
                "Amplifier Title": "0,1"
            }
        }
    }
}
```

Unfortunately the following does not work

```
Function DoStuff()
	variable jsonID1 = JSON_Parse("{ \"abcd\" : { \"a\" : 1 }}")
	variable jsonID2 = JSON_Parse("{ \"abcdefgh\" : { \"b\" : 1 }}")

	JSONXOP_AddValue/O/JOIN=(jsonID2) jsonID1, ""
	print/LEN=1000 JSON_Dump(jsonID1, indent=2)
End
```

as it gives

```
•dostuff()
  {
  "abcdefgh": {
    "b": 1
  }
}
```

We need a minimal solution.

**Comment by MichaelHuth** [comment]
@t-b We miss a feature in our JSON_XOP that would be very useful for syncing two jsons.

lets have this source:
```
{
"array" : [1 , 2, [11, 12], "3"]
}
```
Let's assume array does not exist in the target and I am at "/array/2". I want to add an empty array at "/array/2" in my target. We don't have a function for that.

We need the JSON_AddValue/OBJ also for arrays.

**Comment by MichaelHuth** [comment]
The only workaround would be to use JSON_Parse to parse some array template that contains in every cell empty arrays that are later replaced (except where actualy a sub array exists). The string for parsing need to be build recursively for each array root. The parsed json could then be joined in.

Considering this, it is much easier to patch in an /ARR parameter for JSON_AddValue that works the same as /OBJ just adding arrays.

**Comment by t-b** [comment]
We found a work around for the missing JSON XOP feature.

**Comment by MichaelHuth** [comment]
@t-b should the saved file name in the panels userdata the same as the main json file or main and rig file separated by pipe? (like "main.json|main_rig.json)
