### ISSUE TITLE
Doxygen Group For SweepFormula Operations

### ISSUE THREAD

**Issue by ukos-git** [AllenInstitute/MIES#407]
https://github.com/AllenInstitute/MIES/blob/2c76dcfd3dbfa43b05a55dd072dc81bf62f0fcb2/Packages/MIES/MIES_SweepFormula.ipf#L450

```igorpro
	/// @name SweepFormulaOperations
	/// @{
	strswitch(LowerStr(operations[0]))
		case "-":
```
```igorpro
		default:
			ASSERT(0, "Undefined Operation")
	endswitch
	/// @}
```

This group currently gives an error while building the documentation:

```
/opt/mies/Packages/doc/group/group___sweep_formula_operation.rst:25: WARNING: Duplicate explicit target name: "group sweepformulaoperation".
/opt/mies/Packages/doc/group/group___sweep_formula_operation.rst:30: WARNING: doxygengroup: Cannot find namespace "SweepFormulaOperation" in doxygen xml output for project "MIES" from directory: xml
```

Is it possible to reference all sweepforumula operations with doxygen or are we better off deleting the doxygen group here?

**Comment by t-b** [comment]
@ukos-git I would delete the doxygen group here. doxygen does not extract comments inside functions AFAIK.

**Comment by t-b** [comment]
Closing as the code should be split up.

**Comment by ukos-git** [comment]
could you elaborate on what "code splitting" means in this context?

**Comment by t-b** [comment]
@ukos-git The function `SF_FormulaExecutor` is too long IMHO. It could be split up in the long switch statement.

**Comment by ukos-git** [comment]
Even after splitting it up, the documentation problem will not be solved. We currently keep two versions of the documentation up to date. I think it would be ideal to write an awk script to pass to doxygen for automatic discovery of available functions and usage description right near the code.
