### ISSUE TITLE
Config breaks when MCC is in IC mode

### ISSUE THREAD

**Issue by timjarsky** [AllenInstitute/MIES#416]
Config is attempting to set a VC parameter while MCC is in IC. The MCC must be set to the mode that matches the parameter prior to setting or getting the param. e.g. MCC_SetRsCompCorrection only works if the amp channel is VC (not IC).

- [ ] Have config set MCC channel mode to match param mode (IC or VC).

![image](https://user-images.githubusercontent.com/5693697/72177162-f661c380-3394-11ea-872d-48b6a6c0373e.png)

**Comment by MichaelHuth** [comment]
@timjarsky I had the same issue due to this bug https://github.com/AllenInstitute/MIES/pull/420 where for each amplifier channel a MCC with the same serial was opened. When setting the parameters MIES targeted the wrong MCC.

Does the PR fixes this issue as well?

**Comment by t-b** [comment]
@timjarsky This error here is due to the headstage slider being restored. This is fixed in #421.
