### ISSUE TITLE
Installer: Should apply ASLR patch and make ITC hardware work out of the box

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#428]
- https://github.com/AllenInstitute/ITCXOP2#windows-10
- https://github.com/AllenInstitute/MIES/blob/6a127c5cdc8b23b81769c901dd6e8ca798677f8b/Packages/MIES/MIES_DAC-Hardware.ipf#L722

**Comment by t-b** [comment]
[ITC-Registry-files.zip](https://github.com/AllenInstitute/MIES/files/4183486/ITC-Registry-files.zip)

**Comment by ms-ai** [comment]
The 64-bit version is bad. Error is
Exception calling "AddAccessRule" with "1" argument(s): "This access control list is not in canonical form and therefore cannot be modified."

I let Windows fix the error in the registry, and re-exported the 64-bit file. Attached is the new zip:
[itc_registry_files.zip](https://github.com/AllenInstitute/MIES/files/4215238/itc_registry_files.zip)

**Comment by ms-ai** [comment]
Apparently, the new exported version that I sent also has the wrong canonical form. How can that be? I'll dig more.

**Comment by ms-ai** [comment]
There was nothing wrong with your files - they don't specify the ACL themselves. The problem and solution are described here:
https://answers.microsoft.com/en-us/office/forum/office_2016-office_install/registry-keys-in-hklmsoftwarewow6432node-are/c15da441-cf0c-4bb7-b193-e6cae4adcd50

Cheers!

**Comment by MichaelHuth** [comment]
The ITC XOP documentation states that ASLR needs to be disabled for Igor 32 Bit, but the script disables it for 64 and 32 bit Igor Pro. Is it also required for 64 bit Igor Pro?

**Comment by t-b** [comment]
@MichaelHuth Let's disable it for both just to be sure.
