### ISSUE TITLE
Installer: Should be signed

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#457]
If you are first time installing MIES on a windows 10 box you get a scary "This is unsafe" warning. This can be prevented by signing the installer.

Discussion:
- http://forums.winamp.com/showthread.php?t=395644
- http://forums.winamp.com/showthread.php?t=455491
- https://docs.microsoft.com/en-us/windows/msix/package/sign-app-package-using-signtool

We need a certificate for that (either the AI buys one or I buy one). It costs around 500 $USD per year. See also https://www.digicert.com/code-signing/.

**Comment by MichaelHuth** [comment]
One requires a **code signing** certificate that supports **Windows 10**. (Basically all authorities issue for that)

Comodo offers code signing certificates cheaper:
https://comodosslstore.com/code-signing/comodo-individual-code-signing-certificate

The main benefits of EV are:
- timestamp support, that the signed application still verifies valid after the original certificate expires.
- so called extended smartscreen reputation, that windows smartscreen does not pop up.

Signing:
- Open VS 2019 Developer command prompt
- `signtool sign /a code.exe` This chooses the certificate automatically, which works if only one is available. With an EV certificate from e.g. digicert the USB stick token is _probably?_ required at this step.
- More complex signing with timestamp: https://knowledge.digicert.com/solution/SO17631.html
- Signing using powershell, specifically example 3: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/set-authenticodesignature?view=powershell-7

- Works these file types(*): .CAB, PE formats (.EXE, .DLL, etc) , .CAT, .MSI, .JAR,.OCX, .PS1, .PSM1, .PSD1, .PS1XML, .PSC1

(*) The supported list depends on the installed and registered authenticode capable libraries.

Additional notes:
In case the certificate should be used for Java then a certain java version is required that brings the root cert from the CA. 
e.g. for Comodo: https://support.comodo.com/index.php?/comodo/Knowledgebase/Article/View/296/17/
