### ISSUE TITLE
Function TS_ThreadGroupPutDFR might crash Igor Pro.

### ISSUE THREAD

**Issue by MichaelHuth** [AllenInstitute/MIES#483]
The function has the problems:
- it does have no protection against dangling references to objects in the given dfr.
- dfr itself is a reference to the datafolder pushed to the thread
- The function exits with the current datafolder set that was just pushed.

We solved that in ASYNC_putDF by duplicating and setting the data folder through $name and setting it back afterwards.

**Comment by t-b** [comment]
@MichaelHuth Can you make a PR? Thanks.
