### ISSUE TITLE
Always run the testpulse during DAQ

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#49]
The new mode is called "TP during DAQ" for the headstages which have that activated. Similiar to the name "TP during ITI" (inter trial interval).

- A special stimset named "Testpulse" can be selected
- This stimset will be generated on the fly from the testpulse settings using the existing TP MD code for ITC hardware
- DAQ itself is done as usual
- Display is different for channels with "TestPulse" stimset. On these channels we have a display like TP.
  Think about adding two different groups in the oscilloscope window. One for TP data with its own x-axis and one for DAQ data.
- TP_Delta will be called on every one of these pulses from the "Testpulse" stimsets. LBN entries only for the last one as we do for TP itself.
- PressureControl should still work with "TP during DAQ", (calling P_PressureControl should be enough)
- Ignore "TP during DAQ" headstages for dDAQ/oodDAQ. (dDAQ = "distributed DAQ", oodDAQ = "optimized overlapped distributed DAQ")

**Comment by t-b** [comment]
https://www.wavemetrics.com/forum/general/daqmxwaveformgendaqmxscan-running-multiple-same-time

**Comment by t-b** [comment]
@timjarsky Well if we only want to use two x-axis we have to move the plots around or?

**Comment by timjarsky** [comment]
@t-b if possible, display only two time-axes (three if you count the relative axes). The other axes can be hidden. I'm also open to hiding the TP time axis as it can easily be inferred from the TP param and the transients. I may preffer the latter option as it would help keep the look cleaner.

**Comment by t-b** [comment]
Steps:
1. Allow selection of testpulse stimset in DA tab
  - Write channelType column in config wave. Also for normal DAQ and TP.
  - Ignore testpulse channels for dDAQ/oodDAQ
  - SW_SweepSaving should ignore "TP during DAQ" channels
2. Create Testpulse data via adapted version of `DC_UpdateTestPulseWaveMD` for both NI and ITC
3. Visualize the latest Testpulse in the oscilloscope data window

**Comment by t-b** [comment]
@MichaelHuth Regarding `SW_SweepSaving should ignore "TP during DAQ" channels` do you think it makes sense to implement 1D wave saving first (which this moved out of the NIDAQ support MR)?

**Comment by t-b** [comment]
Opened PR.
