### ISSUE TITLE
Move configuration to a user writeable folder for ALLUSER installs

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#492]
From @aleonlein:

>One of the requests that his come up amongst our system engineers is to move the configuration files from C:\Program Files\MIES\Packages\Settings to the C:\ProgramData directory. We are trying to lock down the program files directory so that only users with write access can adjust files under this folder. The users of ephys like to change the configs based on how they like to run their experiments. Would this be possible?

@timjarsky What do you think?

**Comment by t-b** [comment]
@aleonlein

I've chatted with Tim about that and here what we came up with.

As far as I understand it, this only concerns auto configuration (`CONF_AutoLoader`) right?

- We look into `C:\Program Files\MIES\Packages\Settings`
- If there are json settings files present we autoload them and are done
- If not we look into `C:\Users\Public\Documents\MIES\Settings`, and load the json settings files if present.

This means:
- We don't mix json settings files from different folders
- Global (`C:\Program Files\MIES\Packages\Settings`) override local (`C:\Users\Public\Documents\MIES\Settings`) ones
- The local folder is read/writable for all users and not hidden by default (compared to `C:\Program Data`)

What do you think?

**Comment by aleonlein** [comment]
@t-b Apologies for the delayed response - this corona virus has turned my schedule upside down. I think this sounds reasonable however, I want to pass it by our project lead and see how he wants to proceed. I will contact you by end of day.

**Comment by aleonlein** [comment]
@t-b It sounds like Colin would like the configuration files under C:/ProgramData/AllenInstitute/MIES/Settings

This will unify where all configurations built by MPE and AllenInstitute software are stored
