### ISSUE TITLE
New analysis function chirp for IVSCC

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#496]
- Read input resistance value from lab notebook (or other stimulus)
     - This could involve a quick ‘search’-type stimulus set
- Scale sine wave stimulus to that value (analysis parameter)
- Use DAScale for scaling the stimset
- Monitor min, max peak to through voltage deflections caused by sine wave stimulus (mid sweep), stop sweep and adapt scalar if outside desired range (four analysis parameter with lower_min, lower_max and upper_min, upper_max bounds)
- Adjust scalar and re-run
- Pre and post stimulus QC functions identical to existing stim
- three part stimset: pre, XXX, post
- 3 failures -> Set QC failure
- 3 passing with the same DAScale
- Enforce at least 3 sweeps in the stimset

**Comment by t-b** [comment]
Questions:
- What are the pre/post pulse baseline lengths? Existing ones are 500ms/1000ms (PSQ_DAScale), 500ms/500ms (PSQ_Rheobase), 500ms/1000ms (PSQ_Rheobase).
- What labnotebook entry is the `input resistance`?

**Comment by timjarsky** [comment]
@t-b https://twitter.com/timjarsky/status/1083778985111109632

**Comment by t-b** [comment]
New analysis function is run after the ramp.
