### ISSUE TITLE
TS_ThreadGroupPutDFR: Recent changes trigger IP bug

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#500]
From my testing this is due to the changes in 4b4a965b (fix possible crash in TS_ThreadGroupPutDFR, 2020-03-17).

The top root node is missing after running the TP.

![grafik](https://user-images.githubusercontent.com/1185677/77206300-e5e96a00-6af6-11ea-9c39-ac720d9e357d.png)

**Comment by t-b** [comment]
@MichaelHuth Can you have a look?

**Comment by MichaelHuth** [comment]
@t-b 
I tested a bit and using
`print GetDataFolder(1), SetDataFolder and DataFolderDir(-1)`
the state and tree of the folders looks ok.

The problem seems to be with the Data Browser which shows a wrong tree view and after reopening just empty and no other objects.
