### ISSUE TITLE
TimeAlignment with PAPlot is unbearable slow

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#555]
PA time alignment not the general time alignment.

**Comment by t-b** [comment]
@timjarsky I'm assuming you want the following to work:
OVS/time alignment/PA enabled and measuring  sweep after sweep?

**Comment by timjarsky** [comment]
> @timjarsky I'm assuming you want the following to work:
> OVS/time alignment/PA enabled and measuring sweep after sweep?

@t-b yes, please.

**Comment by t-b** [comment]
https://ai-mies.slack.com/archives/D1P2AN29F/p1593015872064600?thread_ts=1592954473.064200&cid=D1P2AN29F

**Comment by t-b** [comment]
@timjarsky Please reopen if TA with PA is still to slow.
