### ISSUE TITLE
PA plot scale bars

### ISSUE THREAD

**Issue by timjarsky** [AllenInstitute/MIES#568]
Add scale bars to PA plot

- [x] Each cell, except diagonal, has a Y scale bar that is the same amplitude (e.g., 5 mV; user configurable).
- [x] One x scale bar for each column/region of the PA plot - aligned with the end of the trace. Growing to the left.
- [x] vertical is aligned with y=0 and goes up or down depending on the average wave
- [x] add bar length with units (lower right for X, lower left for Y)

**Comment by t-b** [comment]
Closed via #593 and #596.
