### ISSUE TITLE
JSON configuration: How to inform users about outdated configuration files

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#620]
Consider the DAEphys panel.

When we add a new control to the panel, users with existing configuration files don't have that control in their config. The question is how can we tell the user what is missing from the configuration file? Creating two json files and just presenting the diff output is probably too complicated.

**Comment by t-b** [comment]
Another issue is when we rename or remove controls. We inform the user that the control does not exist anymore, but from then on she is left on her own.

Ideas:
- Create a new JSON config file which has the now non-existing controls removed
- Or we create a new JSON config file from the GUI and the merge the old JSON config file into that overriding the values from the GUI. And use that as new file.

**Comment by t-b** [comment]
This came up again recently.

The question was how to incorporate new JSON entries defined via `CONF_DefaultSettings` without having to manually edit the JSON file.

When you load a DAEPhys JSON config and then after loading save it again this is what you get in the new config:
- All non-existing-anymore controls, which were still referenced in the original config, are not present anymore
- All new controls are present
- The experiment configuration block defined in `CONF_DefaultSettings` is written with the default values and not the used ones. New entries are added.
- Any idea of the rig file (if used) is forgotten

**Comment by timjarsky** [comment]
Add a menu option(s) to update config files for a standard configuration and window configuration (the user specifies the file path in the case). Overwrite the old files.

**Comment by MichaelHuth** [comment]
My idea would be that we extend our SyncJSON function.

Then we sync the current config in the old config such that the current config JSON is traversed and
* if it exists in both then the entries stay in the old config (needs JSON_Exists)
* if it exists only in the current config, then the entries are added to the old config (needs JSON_GetJson / JSON_AddJson)
* if it exists in the old but not in the current config, then it is removed from the old config (needs JSON_Remove)

For that it would be very convenient to read and write JSON objects from jsonPaths. While we have a function JSON_AddJson / JSON_SetJson we don't have JSON_GetJson (or JSON_Dump with a given path).
