### ISSUE TITLE
Documentation Appears to be broken

### ISSUE THREAD

**Issue by smestern** [AllenInstitute/MIES#627]
Hello,

The links in the readme to the documentation currently lead to an error 404. This is possibly an issue with the repo containing the [https://alleninstitute.github.io/](https://alleninstitute.github.io/) website

Thanks!

**Comment by t-b** [comment]
@smestern Thanks for the report. This is due to some recent CI work, I'll fix it ASAP.

**Comment by t-b** [comment]
Fixed via c12eb94c (Merge branch 'feature/rework-ci' into main, 2020-09-04), thanks for the report.

It is now again present at https://alleninstitute.github.io/MIES.
