### ISSUE TITLE
Add new analysis function for failed pulse usage

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#633]
- [ ] Flowchart
- [ ] Discuss that with Tim
- [ ] Code
- [ ] Tests

PRE_SET:

- Open Databrowser (if not yet open), enable PA plot image, and failed pulse search

POST_SWEEP:

- Read failed pulses from `properties` wave
- Store in LBN
- redo last sweep with failed pulses using skip sweeps with an adapted DAScale (clarify with Tim how)
- store pass/failure in LBN

**Comment by timjarsky** [comment]
@t-b PRE_SET items should not open duplicates.
