### ISSUE TITLE
Break in button in MIES not working

### ISSUE THREAD

**Issue by aleonlein** [AllenInstitute/MIES#637]
The break in button to automate cell puncture is not working for users in the MIES UI panel. After hitting the button, nothing happens.

**Comment by t-b** [comment]
Same question regarding version info from #638.

- Are you hitting the button via zeromq or directly with the mouse and attached human?
- Can you post the output from the command window

**Comment by aleonlein** [comment]
The users are hitting it via the UI. There is no output in the terminal after the button is hit. Also, users wanted me to mention that the "Seal" button is not accessible via the UI meaning it is greyed out. They can access through hardware on ACQ4, just not through the da-ephys panel

**Comment by timjarsky** [comment]
> The users are hitting it via the UI. There is no output in the terminal after the button is hit. Also, users wanted me to mention that the "Seal" button is not accessible via the UI meaning it is greyed out. They can access through hardware on ACQ4, just not through the da-ephys panel

@aleonlein if buttons are greyed out in MIES pressure controls, it suggests that pressure settings are not configured. This would also explain the other issues. You may run `P_ValidatePressureSetHeadstage(panelTitle, headStageNo)` with debugging enabled to determine which settings are incorrect.

**Comment by aleonlein** [comment]
@timjarsky Okay. I am passing this along to Cliff, the new lead systems engineer on the project. I will pass on what he finds

**Comment by aleonlein** [comment]
@t-b @timjarsky It sounds like Rusty is working with Tim to get the rig configured so these buttons work. I am OK if you want to close the issue

**Comment by t-b** [comment]
Okay, closing. Feel free to reopen.
