### ISSUE TITLE
Igor Freezes When Saving Data

### ISSUE THREAD

**Issue by aleonlein** [AllenInstitute/MIES#638]
After calling IVS_SaveExperiment and IVS_ExportAllData, Igor becomes unresponsive. Sometimes, it takes 5 minutes for it to become responsive again. It is saving the data however, it cannot be used until it is done.

**Comment by t-b** [comment]
@aleonlein Thanks for the report.

- Which version of MIES are you using [1]?
- Is it reproducible? Or does it happen only once in a while?
- Are you saving to a local disc or network?
- Are the files big when it fails?
- Does it happen with other commands as well?
- Are you using REQ/REP zeromq sockets or something more fancy?
- You can turn on zeromq XOP debug messages with `zeromq_set(ZeroMQ_SET_FLAGS_DEBUG | ZeroMQ_SET_FLAGS_DEFAULT)` inside Igor pro. I would be very interested in these when you can replicate the error.

Sorry for all the questions :)

I've tried it here and could not reproduce the error with the following snippet

```python3
#!/usr/bin/env python

import json
import zmq

context = zmq.Context()
socket = context.socket(zmq.REQ)
socket.connect("tcp://localhost:5670")

command = {"version": 1,
           "CallFunction":
                {"name": "IVS_SaveExperiment",
                 "params": ["abcd"]}
          }
command_str = json.dumps(command)
socket.send_string(command_str)
reply = socket.recv()
print(json.dumps(json.loads(reply), indent=2))
```

Saving a 5.7GB file here to a SSD blocks Igor for around 5s. Saving to NWB takes around 15-20s. That it blocks during saving is expected, as the user should not change stuff during save.

[1]: Mies->About MIES answers that. It has has a convenient link which create a github issue and has all the relevant info.

**Comment by aleonlein** [comment]
In response to your questions:

* MIES version MIES 2.1_20200723-14-gec2d6c03
* It happens every time they go to save their final dataset (at the end of acquisition)
* We are saving locally
* pxp is about 1GB and nwb can be between 30-50MB
* REQ/REP is being used
* I will use the zeromq debug messages to snoop around and see what is happening

Regarding the last bullet point: I will do some digging to see what I can find and I will report back to you at the beginning of next week.

**Comment by aleonlein** [comment]
I spoke to Rusty and I think we found the issue (and it was on our end). Through the workflow, I was asking Igor to start a new experiment too closely after I had asked it to export the pxp and nwb file. I ended up moving the export call to an earlier place in the workflow. I think we can close this issue.

**Comment by t-b** [comment]
Glad to hear that.
