### ISSUE TITLE
Use new work load class feature in ASYNC framework to make PA plots faster

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#666]
On the FTP the file PA-TimeAlignment-Playing-around.pxp has good sample data.

Relevant Functions: PA_PreProcessPulses, PA_CalculateAllAverages

Either push a wave reference wave into the ASYNC framework or a datafolder reference wave
 a ala

```igorpro
DFREF freeDFR = NewFreeDataFolder()

MoveWave source, freeDFR

Make/DF threadWave = {freeDFR}
ASYNC_PrepareDF(...)
```

**Comment by MichaelHuth** [comment]
AppendToGraph Grouping Quickbench:

```
Function testSpeed()

	variable i
	variable n = 10000
	
	Make/O/WAVE/N=(n) wGraphData
	for(i = 0; i < n; i += 1)
		Make/O/N=(2500) $("data" + num2str(i))/Wave=data
		data = enoise(1)
		wGraphData[i] = data
	endfor
	

	Display
	
	variable s = stopmstimer(-2)
	for(i = 0; i < n / 10; i += 10)
		AppendToGraph/Q wGraphData[i], wGraphData[i + 1], wGraphData[i + 2], wGraphData[i + 3], wGraphData[i + 4], wGraphData[i + 5], wGraphData[i + 6], wGraphData[i + 7], wGraphData[i + 8], wGraphData[i + 9] 
	endfor
	print/D "grouped: ", (stopmstimer(-2) - s) / 1E6
	
	
	Display
	
	s = stopmstimer(-2)
	for(i = 0; i < n; i += 1)
		AppendToGraph/Q wGraphData[i]
	endfor
	print/D "Ungrouped: ", (stopmstimer(-2) - s) / 1E6
End
```

**Comment by MichaelHuth** [comment]
My execution times (Recovery 50Hz) in [s]:
In PA: Enable Image Output / Enable Trace Plot / enable:
  PA_CalculateAllAverages:  0.031281299987793
  PA_PreProcessPulses:  8.12544630001831
  PA_ShowPulses/AppendToGraph Loop:   15.7254476999817
  PA_ShowPulses:   16.2824618999939
  PA_ShowImage  0.890228699981689
  PA_Update:   25.3026484000244

In OVS check sweep 131 and then uncheck sweep 131:
  PA_CalculateAllAverages:  0.025637200012207
  PA_PreProcessPulses:  2.6413328999939
  PA_ShowPulses/AppendToGraph Loop:   24.4885661000061
  PA_ShowPulses:   25.0382530999756
  PA_ShowImage  0.720613
  PA_Update:   28.4045835

**Comment by t-b** [comment]
@MichaelHuth I'm getting

IP9:
```
•testspeed()
  grouped:   1.01879190000153
  Ungrouped:   1.2510191000061
```

IP8:
```
•testspeed()
  grouped:   3.44549359999847
  Ungrouped:   6.77222590000153
```

@MichaelHuth What are your numbers?

**Comment by MichaelHuth** [comment]
IP8:
grouped:   7.33687429998779
Ungrouped:   20.0589250999756

IP9:
grouped:   0.349074700012207
Ungrouped:   0.422753

**Comment by timjarsky** [comment]
@t-b do you know why is IP9 so much faster?

**Comment by timjarsky** [comment]
IP8:

**Comment by timjarsky** [comment]
@t-b @MichaelHuth  The speed enhancement discovery described here is a great find! Thank you!!  Since we will likely be with IP8 for some time, I favor implementing the speedup asap.

**Comment by MichaelHuth** [comment]
I added two more commits in https://github.com/AllenInstitute/MIES/pull/665
that implement the trace grouping for one loop.
I got the AppendToGraph loop down from 15.7 s to 10.7s here.

**Comment by t-b** [comment]
This is obsolete with the new incremental averaging support.
