### ISSUE TITLE
PA plot: failed pulses does not update always

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#684]
Experiment: PA-TimeAlignment-Playing-around.pxp

- Display sweep 130
- PA tab: Enable search failed pulses with level 0
- Enable PA plot
![grafik](https://user-images.githubusercontent.com/1185677/96468196-0fed4100-122c-11eb-8dcd-16149b2f49eb.png)
- Change level to -53
- Still the same graph
- Disable and then reenable search failed pulses
![grafik](https://user-images.githubusercontent.com/1185677/96468303-38753b00-122c-11eb-8d95-de2389457266.png)

So something is broken.

**Comment by timjarsky** [comment]
@t-b 

In the top image, all of col 3 fails because the spikes don't reach zero. In the bottom image, one pulse fails because it doesn't reach -53. That seems right, no?

**Comment by t-b** [comment]
@timjarsky My problem is that the graph does not change when I change the level from 0 to -53. But it does change if I disabled and reenable search failed pulses.
