### ISSUE TITLE
missing lines in PA image plot

### ISSUE THREAD

**Issue by timjarsky** [AllenInstitute/MIES#690]
@t-b during incremental updates (with overlay sweeps on), the PA image plot can have bands of missing data (see image).

![image](https://user-images.githubusercontent.com/5693697/96538733-142a5600-124e-11eb-9399-19a14ecde91d.png)

**Comment by t-b** [comment]
@timjarsky Can you provide the data? And with what MIES version?

**Comment by timjarsky** [comment]
> @timjarsky Can you provide the data? And with what MIES version?

@t-b it is the same data I believe I uploaded to the FTP. It occurs in all branches I tested but, just now I tried to confirm in the main branch and found a new bug with incremental updates that prevented confirmation.
