### ISSUE TITLE
Investigate zero pulses issue with test data

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#705]
@MichaelHuth provided test data in #704

_Originally posted by @MichaelHuth in https://github.com/AllenInstitute/MIES/pull/704#issuecomment-721425207_

**Comment by MichaelHuth** [comment]
Since the pulse data is equidistant and has no NaNs. how about a simpler way by:
```
offset = sum(wv) / DimSize(wv, ROWS)
wv -= offset

```
It also does not have the side effect of Differentiate dropping points.

**Comment by t-b** [comment]
@timjarsky What do you think about changing `ZeroWave` as @MichaelHuth pointed out? This would also be much faster.

**Comment by timjarsky** [comment]
@t-b Is that method more sensitive to errors/variability in the value of the first point?

**Comment by t-b** [comment]
@timjarsky From a theoretical point no. But of course numerical differentiation and integration work a bit different than math.

```igorpro
Function/WAVE GetData()

	Make/FREE wv = {100, -100, 1000, -1000}
	
	return wv
End

Function ZeroOld(WAVE wv)

	Differentiate/DIM=0/EP=1 wv
	Integrate/DIM=0 wv
End

Function ZeroNew(WAVE wv)

	variable offset = wv[0]
	wv[] = wv[p] - offset
End

Function Dostuff()

	WAVE wv = GetData()
	ZeroOld(wv)
	print wv

	WAVE wv = GetData()

	ZeroNew(wv)
	print wv
End
```

gives

```
•dostuff()
  '_free_'[0]= {450,0}
  '_free_'[0]= {0,-200,900,-1100}
```

First line is the existing algo, second just subtracting the first value. So even the new algo does not do any averaging or similiar it is not way wrong compared to the old method.

**Comment by t-b** [comment]
Switch to new method.
