### ISSUE TITLE
DataBrowser asserts when AD<->HS association changes in overlayed sweeps

### ISSUE THREAD

**Issue by MichaelHuth** [AllenInstitute/MIES#714]
Experiment file DataBrowserIssue.zip on the FTP.

To reproduce:

Open DataBrowser, enable OVS, enable Sweep 6.

**Comment by t-b** [comment]
The assertion is 

```
  Stacktrace:
OVS_MainListBoxProc(...)#L840 [MIES_OverlaySweeps.ipf]
PostPlotTransformations(...)#L3577 [MIES_MiesUtilities.ipf]
LayoutGraph(...)#L2268 [MIES_MiesUtilities.ipf]
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Time: 2020-11-06T14:50:15+01:00
  Locked device: [- none -]
  Current sweep: [- none -]
  DAQ: [- none -]
  Testpulse: [- none -]
  Experiment: PA_Tests (Packed)
  Igor Pro version: 9.0.0.3 (36607)
  MIES version:
  
  ################################
  !!! Assertion FAILED !!!
  Message: "Left over space"
```

If I remove the assertion the databrowser looks like

![bandicam 2020-11-06 14-54-24-133](https://user-images.githubusercontent.com/1185677/98373738-fb88b100-203f-11eb-983e-443f9653bb19.png)

which is not correct. The issue stems from the fact that HS3 is attached to AD3 on sweep 0, but AD1 on sweep 6. And that confuses the layout mechanism as we have among others the y axis "row0_col0_AD_0_HS_3" and "row0_col0_AD_3_HS_3".

@timjarsky How many vertical axes do you expect in this case?

**Comment by timjarsky** [comment]
@t-b @MichaelHuth What are the potential causes of the change in headstage to channel associations? Did it change in the same experiment or is data from different experiments being loaded into the analysis browser?

I think we have to assume that the user isn't changing the hardware configuration during an experiment and asserting might be a reasonable approach.

I need to think harder about how we handle data from different experiments but this is an edgy case, I think?

**Comment by MichaelHuth** [comment]
@timjarsky In this case I was generating some test data for the PA tests. What I did was acquiring a sweep with a specific HS - AD/DA channel configuration. Then I was changing the setup to different HS but reusing the same AD/DA channel and acquire a second sweep.

A simple example to reproduce is: 
Use two HS e.g. 0, 1 with HS0 using DA0 AD0 and HS1 using DA1 AD1. Acquire a sweep.
Use HS 0, 1 again but swap the channels such that HS0 uses DA1/AD1 and HS1 uses DA0 AD0. Acquire a second sweep in the same experiment.

**Comment by timjarsky** [comment]
@MichaelHuth Changes in headstage associations in the same experiment aren't expected. I recommend asserting out.

**Comment by t-b** [comment]
We will ignore data from sweeps which has a different HS-AD association.

**Comment by MichaelHuth** [comment]
@t-b This is not resolved.

**Comment by timjarsky** [comment]
Not a real-world issue.
