### ISSUE TITLE
Stimulus set 32bit precision might limit future hardware

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#720]
We are currently using 32bit floats for storing the stimulus sets. This is fine with our current hardware (ITC, NI) as the hardware has a DA/AD resolution of max. 16 bit. But if we would support other hardware, or amplifiers, with a higher resolution this would need to be revisited.

**Comment by timjarsky** [comment]
Adding new hardware will likely open up several issues. Closing and will add hardware-specific issues when adding new hardware.
