### ISSUE TITLE
PulseAveraging: In PA_ShowImage the WaveMinimum/WaveMaximum in the note do not correspond to the image data

### ISSUE THREAD

**Issue by MichaelHuth** [AllenInstitute/MIES#738]
In PA_ShowImage the WaveMinimum/WaveMaximum wave note value is determined from the original pulse data.
Though, the image itself is created by indexing with linear interpolation with img[][] = pulseData(x).
This results that the actual Min/Max values in the image data do not match the ones from the own wave note.

**Comment by t-b** [comment]
I'd say we can live with that discrepancy.
