### ISSUE TITLE
DA_Ephys Panel: Previous HS association prevents new data acquisition, when old HS stays unused.

### ISSUE THREAD

**Issue by MichaelHuth** [AllenInstitute/MIES#740]
When re-opening a DA_Ephys panel it sets the previous HS association in the hardware tab.

Set the case I had HS 0 associated to DA 0, AD 0 and other HS associated to their respective channels as well (e.g. HS 1 and 3) in a previous acquisition. Then I close the DA_Ephys panel and re-open it. The previous HS associations are restored.

After device lock I clear the association of HS 0. In the Data Acquisition tab I enable HS 1 and 3 only, setup remaining stuff and try to start an acquisition. It will assert with "Invalid column".

The problem is: The channelClampMode wave has HS 0, 1, 3 setup from the first time panel. The "Clear Association" button does not update the channelClampMode wave. Only checking/unchecking the HS in the DataAcquisition tab updates the wave.
On panel reopening the all HS are unchecked there, when I check 1 and 3, then 1 and 3 is added to the channelClampMode wave, which is OK, but the information for HS 0 is still there and never removed.
It would be removed if I would have unchecked HS 0, but it is already unchecked.

Current workaround:
After reopening the DA_Ephys panel:
For all HS where the association is cleared in the hardware tab check and then uncheck the HS in the Data Acquisition tab. This removes the data from the channelClampMode wave.

**Comment by t-b** [comment]
That is quite difficult to fix. In most cases the user wants to keep the settings when closing and reopening the DAEphys panel.
