### ISSUE TITLE
Consider wrapper for GetDataFolder function.

### ISSUE THREAD

**Issue by MichaelHuth** [AllenInstitute/MIES#745]
In IP8 GetDataFolder(1, dfr) returns an empty string if dfr is null, even with pragma rtFunctionErrors = 1.
In IP9 this returns a runtime error (with rtFunctionErrors =1).

We should consider to add a wrapper for this function for IP8 that asserts if dfr is null.

**Comment by t-b** [comment]
We will be adding some CI testing with IP9 later this year, that should catch these errors. I deem also the IP9 behaviour the correct one.
