### ISSUE TITLE
IVSCC export issues

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#747]
- subject_id was not written
- dandi validate did not pass

PRs:
- https://github.com/AllenInstitute/IPNWB/pull/22
- https://github.com/AllenInstitute/MIES/pull/748

Issues:
- https://github.com/hdmf-dev/hdmf/issues/470
- https://github.com/NeurodataWithoutBorders/pynwb/issues/1321
- https://github.com/dandi/dandi-cli/issues/282

Initial slack question:
- https://dandiarchive.slack.com/archives/C011LRNU2F7/p1605888652011300?thread_ts=1605798117.007200&cid=C011LRNU2F7

**Comment by t-b** [comment]
Analysis:

dandi validation outputs here the following:
```
  VectorIndex/description (general/intracellular_ephys/sweep_table/series_index): argument missing
  VectorIndex (general/intracellular_ephys/sweep_table/series_index): incorrect type - expected 'uint8', got 'int32'
  VectorIndex/description (general/intracellular_ephys/sweep_table/series_index): argument missing
  VectorIndex (general/intracellular_ephys/sweep_table/series_index): incorrect type - expected 'uint8', got 'int32'
  Failed to read metadata: Could not construct IntracellularElectrode object due to: IntracellularElectrode.__init__: incorrect type for 'description' (got 'bytes', expected 'str')
```

1. The lines `VectorIndex` complains are due to the fact that dandi does not validate against the cached specification.

2. Missing subject_id is fixed by the linked PR

3. The last line "Failed to read metadata..." can not be reproduced with NWBv2 files created by MIES. This looks like it was post-processed with a different pynwb version.

**Comment by timjarsky** [comment]
Closing for now. Nothing on our side can be done.
