### ISSUE TITLE
DataBrowser: uncaught RT in TweakAxes with non existing axis.

### ISSUE THREAD

**Issue by MichaelHuth** [AllenInstitute/MIES#768]
TweakAxes is called at the end of LayoutGraph, where it iterates over the axes of allHorizontalAxes, allVerticalAxes.
These text waves are determined at the beginning of LayoutGraphs with GetUniqueEntries. However if allVerticalAxesNonUnique contains empty elements at the end then allVerticalAxes has also one empty element at the end. This is taken as axisname and generates an RT in TweakAxes.

![image](https://user-images.githubusercontent.com/29093275/101194358-304b5080-365e-11eb-9197-d61b0a115358.png)

**Comment by t-b** [comment]
Proposed fix: We should have a function which removes empty rows from text waves. And use that after we get the wave from GetUniqueEntries.

**Comment by t-b** [comment]
IMHO this is fixed already.
