### ISSUE TITLE
IVSCC throwing "Non-existing control or window" when selecting setup

### ISSUE THREAD

**Issue by smestern** [AllenInstitute/MIES#775]
Hello, 
I have been working with MIES for a bit now and have been really enjoying the really robust wave builder. I was hoping to use some of the automatic QC functions/analysis. When going to use the IVSCC control panel, most of the buttons throw an error at the function:  ```PGC_SetAndActivateControl```. For example when I press "setup DAEephys panel", With the full text of the error being:
```
  !!! Assertion FAILED !!!
  Message: "Non-existing control or window"
  Please provide the following information if you contact the MIES developers:
  ################################
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Stacktrace:
IVS_ButtonProc_Setup(...)#L487 [MIES_IVSCC.ipf]
IVS_Setup(...)#L24 [MIES_IVSCC.ipf]
PGC_SetAndActivateControl(...)#L206 [MIES_ProgrammaticGUIControl.ipf]
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Time: 2020-12-15T19:49:07-05:00
  Locked device: [- none -]
  Current sweep: [- none -]
  DAQ: [- none -]
  Testpulse: [- none -]
  Experiment: Untitled.pxp
  Igor Pro version: 8.0.5.1 (35712)
  MIES version:
  Release_2.1_20200723-40-g03c94d2a
Date and time of last commit: 2020-11-20T19:19:04+01:00
Submodule status:
 1819408b021250b608c4e5291aebead57654625a Packages/IPNWB (v0.19-44-g1819408)
 3979557f487c3e7d54b515ea0e0c384322034892 Packages/ITCXOP2 (heads/master)
 aa1858d915ee28ebf5974f59f0bc19a421e5c28e Packages/ZeroMQ (latest)
 9fa72d3741553ec644753f8495efdd5d75e52b59 Packages/doc/doxygen-filter-ipf (9fa72d3)
 a097151fbc9a8a8f2e504c9e46adcb327a19c8f3 Packages/unit-testing (UnitTestingFramework-v1.08-88-ga097151)
  ################################
```
Specifically, it seems to fail with the variables ``` win = DA_Ephys ``` and ``` control = popup_moreSettings_DeviceNo ```
Note for this test I didn't have my DAQ/device activated however, I find it throws the same error even with a device connected.

On the hardware end I am using:
-Multiclamp 700B
-NI-DAQ-PCIe-6343
-NI-BNC-2110
I do not currently have any pressure devices hooked up!

It is totally possible I have missed some setup steps prior to running the QC.

**Comment by t-b** [comment]
The device name is currently hardcoded in MIES_IVSCC.ipf.

To change it, do the following:
- Open the DAEphys panel from `Mies Panels -> Acquire data (DAEphys)`
- Check which devices are in the popup menu present named "Devices" (see screenshot)

![grafik](https://user-images.githubusercontent.com/1185677/102510594-15c69d80-4088-11eb-9797-c32285963850.png)

Use that device name in 
https://github.com/AllenInstitute/MIES/blob/6cb4b7e59d3f8c404eb8ac713bc9edaef88c1bfd/Packages/MIES/MIES_IVSCC.ipf#L14

instead of the hardcoded "ITC18USB_Dev_0". My NI device here is named "Dev3".

**Comment by t-b** [comment]
@smestern Did you solve that issue?

**Comment by smestern** [comment]
The fix seemed to work somewhat. I changed `static StrConstant IVS_DEFAULT_PANELTITLE = "Dev1"` for my device. 
Unfortunately it seems to hang up further along now. Similar error text: 
`  The JSON XOP is developed by www.byte-physics.de.
  !!! Assertion FAILED !!!
  Message: "Non-existing control or window"
  Please provide the following information if you contact the MIES developers:
  ################################
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Stacktrace:
IVS_ButtonProc_Setup(...)#L487 [MIES_IVSCC.ipf]
IVS_Setup(...)#L24 [MIES_IVSCC.ipf]
PGC_SetAndActivateControl(...)#L206 [MIES_ProgrammaticGUIControl.ipf]
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  Time: 2021-01-22T08:06:02-05:00
  Locked device: [- none -]
  Current sweep: [- none -]
  DAQ: [- none -]
  Testpulse: [- none -]
  Experiment: Untitled.pxp
  Igor Pro version: 8.0.5.1 (35712)
  MIES version:
  ################################`
I tried pre-locking in my device with no luck 
![image](https://user-images.githubusercontent.com/52610944/105503016-11e3f780-5c94-11eb-9586-53dd98221760.png)

Here is a screencap of the debugger variables on error:

![image](https://user-images.githubusercontent.com/52610944/105503197-4d7ec180-5c94-11eb-99d7-cbcc75fc6eda.png)

**Comment by t-b** [comment]
@smestern Okay so looks like this forgotten to be ported to the new device controls in 66fca8ab (DAEphys: Rework device selection logic, 2019-10-08). But we also remove IVS_Setup later on in 86877dc9 (IVS_Setup: Remove it, 2020-08-19) as 

You don't actually need the IVS_Setup panel to use the patchseq QC functions.

@timjarsky Do we have some documentation on how to run these?

**Comment by t-b** [comment]
Closing as IVS_Setup is gone.
