### ISSUE TITLE
0 electrode QC check during IVS_runBaselineCheckQC

### ISSUE THREAD

**Issue by ru57y34nn** [AllenInstitute/MIES#828]
The MIES_IVSCC function IVS_runBaselineCheckQC currently zeros the amp with the pipette offset function call while monitoring the baseline steady state average and then runs the EXPTINBATH wave, but sometimes the electrode current can drift significantly before the EXPTINBATH actually runs. We would like to have a QC check when the IVS_runBaselineCheckQC is run, which will check the baseline steady state average and will only run the EXPTINBATH sweep if the the baseline is within 0 +/- 5 pA. 

The IVS_runBaselinCheckQC function currently calls a function called IVS_FinishBaselineQCCheck which appears to get the baseline steady state average calculated from 5 cycles of the test pulse and then checks that absolute value to make sure that it is < 100 before running the DataAcquireButton so this may just be a matter of tightening that tolerance.

**Comment by t-b** [comment]
@ru57y34nn Thanks for the issue. So basically instead of https://github.com/AllenInstitute/MIES/blob/452dbbba3fac61ced9a9ad5435b41daf77b9b23d/Packages/MIES/MIES_IVSCC.ipf#L225 you want to have `if (abs(baselineAverage) < 5)`?

**Comment by ru57y34nn** [comment]
Yes, 100 is too high of a tolerance for IVSCC QC criteria, 5 will be much better. Thank you
