### ISSUE TITLE
Callbacks for select MIES_IVSCC functions

### ISSUE THREAD

**Issue by ru57y34nn** [AllenInstitute/MIES#835]
The new IVSCC workflow sequencing engine currently makes calls to the "IVS_SaveExperiment", "IVS_ExportAllData", and the "NewExperiment" MIES_IVSCC functions and we are currently using a timer to wait about 40 seconds each time one of these functions are called to ensure that the workflow sequencing engine does not proceed to the next state until the function procedure is finished. We would like to see if callback functions can be implemented which will return a message that the workflow sequencing engine can listen for that will indicate when the procedure has finished so that the workflow sequencing engine can know when the procedure is done and move to the next state as soon as possible.

**Comment by t-b** [comment]
You can already listen to the repsonse message which is sent after the called function finishes.

Example:

Define the following function in Igor Pro

```igor
Function DoWait()

	Sleep/S 10
End
```

which just waits for 10s.

When I call that with

```python
import json
import zmq

context = zmq.Context()
socket = context.socket(zmq.REQ)
socket.connect("tcp://127.0.0.1:5670")
func_name = "DoWait"
func_params = []

command = {"version": 1,
           "CallFunction":
                {"name": func_name,
                 "params": func_params}
          }
command_str = json.dumps(command)
socket.send_string(command_str)

print(socket.recv())
```

the `socket.recv()` blocks until `DoWait` returns.

An implementation detail is that `DoWait` is not called immediately when you send the mssage, but at the next "good" moment for Igor. But as soon as we call `DoWait` everything happens synchronously.

**Comment by ru57y34nn** [comment]
Thank you, I have passed this information along to our lead developer and she is going to work on implementing this.

**Comment by t-b** [comment]
Thanks. I'm closing this now. Feel free to reopen if necessary.
