### ISSUE TITLE
NI and patchSeq ramp analysis function

### ISSUE THREAD

**Issue by timjarsky** [AllenInstitute/MIES#85]
Update patchSeq ramp analysis function for NI support

**Comment by MichaelHuth** [comment]
@t-b Changing the DA wave on the fly seems to have no influence on the DA output. What works is
an approach like this:

```
			fdaqmx_waveformstop("Dev1")
			DAQmx_AO_SetOutputs/Dev="Dev1" "0,0;"

```

To be able to have this for each channel independently, there must be a waveformgen task per channel setup.

**Comment by t-b** [comment]
@MichaelHuth This sounds promising.

The code in question only uses one headstage. And will not use TP during DAQ. And will only have one DA channel, no unassociated channels. Does that simplify things?

See PSQ_Ramp line 2110 following for the ITC solution.

**Comment by MichaelHuth** [comment]
@t-b The Igor NiDAQ XOP does not support multiple WaveFormGen tasks at the same time. An indicator is that the Stop works only globally on the device. So the simplified model seems to be a requirement.

I currently don't see how that could be accomplished with the NiDAQ XOP on a per channel basis.

**Comment by t-b** [comment]
It is okay to assume that the second channel in the hardware data wave is the DA.

**Comment by MichaelHuth** [comment]
@t-b Is it ok to not handle RTEs by operation such as DAQmx_AO_SetOutputs as they are caught by the caller?

Another general design question: Currently the hardware module has only a running and stopped state which is not split between AD / DA and TTL. So if PSQ_Ramp stops WaveFormGen early then NI_StopAcq handles the second stopping of DA as error.

Can we change the HW running state to at least a bit pattern that keeps track of AD / DA / TTL separately?

**Comment by t-b** [comment]
@MichaelHuth 
> Is it ok to not handle RTEs by operation such as DAQmx_AO_SetOutputs as they are caught by the caller?

The general pattern is that we have a wrapper function and this accepts a flag argument, one of HardwareInteractionFlags. These flags allow the caller to determine how an error is handled. And one of the flags is also suppress error message. We don't want to unconditionally catch RTEs in MIES_DAC-Hardware.ipf.

> Another general design question: Currently the hardware module has only a running and stopped state which is not split between AD / DA and TTL. So if PSQ_Ramp stops WaveFormGen early then NI_StopAcq handles the second stopping of DA as error.

> Can we change the HW running state to at least a bit pattern that keeps track of AD / DA / TTL separately?

I'm not a fan of introducing another state variable for this special case. How about handling the error suppression flag in HW_NI_StopAcq and setting that? Or can we use `HW_NI_IsRunning` to check if a waveform is really running before stopping it?

Btw. I've seen the `zeroDAC` logic in `HW_NI_StopAcq`. You can pull that code out and reuse it for PSQ_Ramp.

**Comment by t-b** [comment]
Tracked now via upstream PR #1101.
