### ISSUE TITLE
Add epoch info for TTL stimsets into LBN

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#855]
And look into the epochs for the other channels if they are correct.

Test:

```igorpro
// UTF_TD_GENERATOR DeviceNameGeneratorMD1
Function DAEpochFail([str])
	string str

	STRUCT DAQSettings s
	InitDAQSettingsFromString(s, "MD1_RA0_I0_L0_BKG1_RES1")
	
	InitDAQSettingsFromString(s, "MD1_RA1_I0_L0_BKG1_ITP0"             + \
	                             "__HS0_DA0_AD0_CM:IC:_ST:Short_DA_0:" + \
	                             "__TTL0_ST:StimulusSetA_TTL_0:")
	AcquireData_NG(s, str)
End
```

Requires 50ms stimset Short_DA_0 from pxp.

Gives ![grafik](https://github.com/AllenInstitute/MIES/assets/1185677/eb88a1be-9d0f-42fa-bcc4-471d183025e9)

[ShortDAWithLongTTLBug.zip](https://github.com/AllenInstitute/MIES/files/11636101/ShortDAWithLongTTLBug.zip)

**Comment by MichaelHuth** [comment]
DA Epoch is correct with 50 ms length, but Stimset epoch must be 1000 ms due to TTL stimset length and B0_TR should be 0 then and not exist.
