### ISSUE TITLE
Stimulus sets occasionally missing in DataBrowser Dashboard

### ISSUE THREAD

**Issue by ru57y34nn** [AllenInstitute/MIES#883]
The Dashboard in the DataBrowser will occasionally not display some stimsets or their status in the dashboard after they have been collected. I will upload a few example experiments (H21.06.352.11.52.01.01.pxp, H21.06.352.11.52.01.02.pxp, and H21.06.352.11.52.01.03) that demonstrate this issue to the byte-physics ftp server for reference. H21.06.352.11.52.01.01 is missing the X1PS_SubThresh stimlus set, H21.06.352.11.52.01.02 is missing X1PS_SubThresh, X2LP_Search, and X3LP_Rheo, while H21.06.352.11.52.01.03 is missing X1PS_SubThresh and X2LP_Search stimulus sets, even though these stimulus sets were collected in all 3 experiment files. This is an issue because rig users need to be able to verify whether these stimulus sets passed or failed the qc criteria.

**Comment by t-b** [comment]
@ru57y34nn Thx for the report. I'm looking into it.
