### ISSUE TITLE
automate TP amplitude in IC mode

### ISSUE THREAD

**Issue by timjarsky** [AllenInstitute/MIES#887]
When TP is running during ITI, measure peak voltage deflection relative to rest (we already do this).

Let user specify peak deflection target in TP settings.

Have MIES automatically adjust TP amplitude to hit target voltage.

Once we do this, we can add an additional baseline QC check to IVSCC protocols to make sure the TP is within an amplitude range.

**Comment by t-b** [comment]
- [ ] IC only
- [ ] target voltage +/- range, enable checkbox (all to LBN)
- [ ] Same interval as autobias
