### ISSUE TITLE
Return qcResult variable from IVS VC QC functions

### ISSUE THREAD

**Issue by ru57y34nn** [AllenInstitute/MIES#893]
IVS_runBaselineCheckQC, IVS_runInitAccessResisQC, and IVS_RunGigOhmSealQC all contain a variable called qcResult, or they call a background function that contains the qcResult variable, which indicates whether or not the qc parameter was passed. If  the qc parameter is passed then the qcResult will contain the value of that parameter or it will be 0 if the qc parameter failed.

Example:
IVS_runBaselineCheckQC calls the background functions IVS_FinishBaselineQCCheck which contains the variable 'qcResult'. This function will get the absolute value of the baseline average and check if it is within the acceptable range:
 - if (abs(baselineAverage) < 100.0)
and if the baselineAverage value is within range then it will run the sweep and assign the value of the baselineAverage to the qcResult variable, otherwise the qcResult will be 0. Right now, qcResult is being printed to the Igor terminal but is not being returned from the function.

We would like to have the qcResult returned from these functions so that our workflow sequencing engine can access the qcResult and use it to determine how or if the rig operator can proceed with the experiment based on whether or not the qc parameter was passed. 

Please let me know if you have any questions or need any additional information for this request

**Comment by t-b** [comment]
Will do.

**Comment by t-b** [comment]
Closed via #895.
