### ISSUE TITLE
Enhance labnotebook viewing for time evolution of entries during a single sweep

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#897]
@timjarsky Yes indeed. One needs level 3 labnotebook wizardry to understand that.

For better plotting we would need a way to visualize time development of a single entry of a single sweep.

_Originally posted by @t-b in https://github.com/AllenInstitute/MIES/issues/719#issuecomment-805051911_

**Comment by timjarsky** [comment]
The use case is specific to developers who already have a reasonable workaround. Closing.
