### ISSUE TITLE
Install without hardware does not work in IP8

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#90]
Supposed to be fixed since 6b1ec3bd (MIES installer: Added MIESUtils XOP linking when install w/o hardware, 2018-06-06) but a quick test revealed that it does not work with IP8. It works with IP7 only,

@MichaelHuth Can you take a look?

**Comment by MichaelHuth** [comment]
@t-b MIESUtils.xop (MIESUtils-64.xop) was at 6b1ec3bd only required for IP7 (WaveModCount extension).

So it is not a bug, as it was not required for IP8 at that time.

I'll change the installer, if it is now also required for IP8...

**Comment by t-b** [comment]
@MichaelHuth Good point. Yes nowadays we need it for IP8 as well. #13 is still not implemented.

**Comment by t-b** [comment]
Closed via PR 1011.
