### ISSUE TITLE
New ZeroMQ XOP version triggers cylance antivirus

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#901]
As reported by @aleonlein in [1] and also verified by me, the new MIES installer with the updated ZeroMQ XOP does trigger the antivirus "tool" cyclance on Allen Institute machines.

I've checked with virustotal, see https://www.virustotal.com/gui/file/8d5a628aa71c3d6156f4b53846769b8a8a6fa3a303349f13f263a1c771d09428/detection, but that only had one hit. And that was an obscure on.

It works on my machine as I use only Windows defender.

I think what triggers are the VC DLLs which I added to avoid having to install the vcredist packge for 2019 additionally.

But doing some reading it looks like we can just move to have the VC 2019 redist packages in the installer. See also https://docs.microsoft.com/en-us/cpp/porting/binary-compat-2015-2017?view=msvc-160#upgrade-the-microsoft-visual-c-redistributable-from-visual-studio-2015-or-2017-to-visual-studio-2019.

So I'll try that.

[1]: https://github.com/AllenInstitute/MIES/pull/895#issuecomment-812600892

**Comment by aleonlein** [comment]
@t-b I am going to work with our IT department to get MIES whitelisted. Cliff thinks this might take a long time for them to work it out but I am just going to put the request in now in case the new fix doesn't work. At least we can have the IT fix in motion.

**Comment by t-b** [comment]
@aleonlein Thx.

**Comment by t-b** [comment]
Closing as reported in https://github.com/AllenInstitute/MIES/pull/895#issuecomment-814465021.
