### ISSUE TITLE
AnalysisBrowser: Allow to resave loaded data

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#911]
Original discussion: https://u01-human-brain.slack.com/archives/CAMJ4T072/p1615802292019600

For some measurements the original PXP files were lost, but NWBv1 files are available. It would be nice if we, after loading them into the AnalysisBrowser, are able to save them in NWBv2. This should be possible as we have the raw data itself, the stimsets and all MIES metadata like labnotebook etc.

**Comment by t-b** [comment]
@timjarsky Is it enough if this works interactively via the analysis browser or do we need a fully automatable solution for many many files?

**Comment by timjarsky** [comment]
@t-b interactively is sufficient

**Comment by t-b** [comment]
@timjarsky And I guess it is also okay to not store saved TPs? We don't yet load that in the analysis browser. But of course if now is the time to do it  ;)

**Comment by timjarsky** [comment]
@t-b do we store saved TPs in MIES NWB2 files already?

**Comment by t-b** [comment]
@timjarsky Yes we always store saved TPs in NWB, both v1 and v2.
