### ISSUE TITLE
Add support for creating epochs in the NWB files

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#94]
- [ ] Add code to IPNWB to read/write DynamicTables (TimeIntervals, used by epochs, inherits from that)
- [ ] Fixup oodDAQ regions, see #382 and DC_AddEpochsFromOodDAQRegions.

Epochs allow to tag time slices in the TimeSeries with user defined labels. They can e.g. be used to identify the inserted TP, or the user onset/termination delays. Using them avoids having the NWB consumer use heuristics to figure that out.

See also https://pynwb.readthedocs.io/en/latest/tutorials/general/file.html?highlight=Epochs#epochs.

**Comment by t-b** [comment]
Generic support for writing epoch information into the NWBv2 files. Will
support all types of MIES generated stimsets and all DAQ modes (TP during DAQ,
oodDAQ, dDAQ, inserted TP, user delays).

**Comment by t-b** [comment]
Schematic drawing what needs to be extracted:
- [NWB-Epochs-in-MIES.pdf](https://github.com/AllenInstitute/MIES/files/3128189/NWB-Epochs-in-MIES.pdf)

**Comment by t-b** [comment]
pynwb code to create epochs (for inspecting the NWB file):

```python
from pynwb import NWBHDF5IO
from datetime import datetime
from dateutil.tz import tzlocal
from pynwb import NWBFile
import numpy as np
from pynwb.icephys import CurrentClampStimulusSeries
from pynwb.icephys import VoltageClampSeries
from pynwb.epoch import TimeIntervals

nwbfile = NWBFile('my first synthetic recording', 'EXAMPLE_ID', datetime.now(tzlocal()),
                  experimenter='Dr. Bilbo Baggins',
                  lab='Bag End Laboratory',
                  institution='University of Middle Earth at the Shire',
                  experiment_description='I went on an adventure with thirteen dwarves to reclaim vast treasures.',
                  session_id='LONELYMTN')

device = nwbfile.create_device(name='Heka ITC-1600')
elec = nwbfile.create_ic_electrode(name="elec0",
                                   description='a mock intracellular electrode',
                                   device=device)

ccss = CurrentClampStimulusSeries(
    name="ccss", data=[1, 2, 3, 4, 5], unit='A',
    starting_time=123.6, rate=10e3, electrode=elec, gain=0.02, sweep_number=15)

nwbfile.add_stimulus(ccss)

vcs = VoltageClampSeries(
    name='vcs', data=[0.1, 0.2, 0.3, 0.4, 0.5],
    unit='A', conversion=1e-12, resolution=np.nan, starting_time=123.6, rate=20e3,
    electrode=elec, gain=0.02, capacitance_slow=100e-12, resistance_comp_correction=70.0,
    capacitance_fast=np.nan, resistance_comp_bandwidth=np.nan, resistance_comp_prediction=np.nan,
    whole_cell_capacitance_comp=np.nan, whole_cell_series_resistance_comp=np.nan, sweep_number=15)

nwbfile.add_acquisition(vcs)

nwbfile.add_epoch_column(name='ts', description='TimeSeries')
nwbfile.add_epoch(start_time=3.0, stop_time=5.0, tags='ocean', ts=vcs)

io = NWBHDF5IO('icephys_example.nwb', 'w')
io.write(nwbfile)
io.close()
```

[icephys_example.zip](https://github.com/AllenInstitute/MIES/files/3128409/icephys_example.zip)

**Comment by t-b** [comment]
- Areas with no information should be generally labelled as baseline instead of `user onset delay` etc.

**Comment by MichaelHuth** [comment]
> * Areas with no information should be generally labelled as baseline instead of `user onset delay` etc.

Should the distributedDAQDelay also named baseline ?

**Comment by t-b** [comment]
> Should the distributedDAQDelay also named baseline ? 

@MichaelHuth Yes I guess.

**Comment by t-b** [comment]
See PR 1128.
