### ISSUE TITLE
Device is not automatically available in Hardware tab pull-down in DA_Ephys

### ISSUE THREAD

**Issue by neurosutras** [AllenInstitute/MIES#945]
Description:
- What was MIES doing at the time of the unexpected behavior?

I have 2 NI DAC devices. "Dev1" is for something else, and "Dev2" is a PCIe-6341 card connected to a MultiClamp 700B amplifier. 

When I start the DA_Ephys GUI, the only device available in the pull-down menu in the Hardware tab is "Dev1".
If I manually edit the variable root:MIES:HardwareDevices:NIDeviceList from "Dev1;" to "Dev1;Dev2;", then "Dev2" becomes available in the pull-down, I am able to Lock device selection, and I am able to acquire data and send test pulses to the Amplifier headstage. So basically everything works, except "Dev2" is not being made available automatically, and I do not know how to change the default initialization of the NIDeviceList string.

- Did user input immediately precede the unexpected behavior?

- What did you expect to happen?

Igor Pro Experiment files can be attached as zip file if needed.

The following contains installation information (keep unchanged):
```
MIES version: Release_2.2_20210503-8-g8c62a4d5
Date and time of last commit: 2021-05-04T19:00:09+02:00
Submodule status:
 3ca8f77c798c04e432907c95e7a177bc2905bec3 Packages/IPNWB (heads/main)
 5ffbdab2c5d42b54f86054c9bcd0cea6e5f07829 Packages/doc/doxygen-filter-ipf (heads/main)
 42276ed677273c02bc7b457324081dd463bb0d6b Packages/unit-testing (heads/main)
```

```
Igor Pro version: OS:Windows 10 Pro for Workstations;OSVERSION:6.3.19042;LOCALE:US;IGORFILEVERSION:8.0.5.1;
```

```
Installation self-test results:
Igor 64bit: 8.05, 37395
Windows 10: True
ASLR: True (Very Bad)

Checking base installation:
Mies version info: Valid "Release_2.2_20210503-8-g8c62a4d5..." (Nice!)
ITC XOP: Found version 1.0.2.0 (Nice!)
JSON XOP: Found version 1.0.0.1 (Nice!)
VDT2 XOP: Found version 2.2.1.0 (Nice!)
HDF5 XOP: Found version 2.0.2.0 (Nice!)
Axon Telegraph XOP: Found version 3.0.0.0 (Nice!)
Multi Clamp Commander XOP: Found version 2.0.0.0 (Nice!)
ZeroMQ XOP: Found version 1.0.0.1 (Nice!)
JSON XOP: Present in the right version (version-650-ge9b149c) (Nice!)
Results: 8 checks, 1 number of errors

Checking extended installation:
NI-DAQ MX XOP: Found version 1.1.5.0 and hash is ok (Nice!)
Results: 1 checks, 0 number of errors
```

**Comment by t-b** [comment]
Thanks for the nice bug report. It is a pleasure to read!

The likely reason for your PCIe-6341 not showing up in the hardware devices popupmenu is that it does not pass our internal checks. We currently allow only a limited set of NI devices. See https://github.com/AllenInstitute/MIES/blob/948e0e319f17cbd9acf8b0d5092238859684e599/Packages/MIES/MIES_DAEphys.ipf#L28-L31. The check itself is done in https://github.com/AllenInstitute/MIES/blob/948e0e319f17cbd9acf8b0d5092238859684e599/Packages/MIES/MIES_DAEphys.ipf#L57.

Can you send us the output of HW_NI_GetPropertyListOfDevices(devNr) where devNr is either 0 or 1 depending on which of your devices is the PCIe-6341?

From the specs at https://www.ni.com/pdf/manuals/377880a.pdf I think we could support that as well. @timjarsky What do you think?

**Comment by neurosutras** [comment]
Dear Thomas et al.,

 Great! That helped a lot!  HW_NI_GetPropertyListOfDevices returned:

AI:16;AO:2;COUNTER:4;DIOPORTS:3;LINES:8,8,8

Which shows me the one value that I got wrong - that I was putting in
LINES:32,8,8, and could not figure out from the specs what the value
corresponded to.

All working now! Thank you.

Aaron

On Fri, May 7, 2021 at 2:18 PM Thomas Braun ***@***.***>
wrote:
>
> Thanks for the nice bug report. It is a pleasure to read!
>
> The likely reason for your PCIe-6341 not showing up in the hardware
devices popupmenu is that it does not pass our internal checks. We
currently allow only a limited set of NI devices. See
https://github.com/AllenInstitute/MIES/blob/948e0e319f17cbd9acf8b0d5092238859684e599/Packages/MIES/MIES_DAEphys.ipf#L28-L31.
The check itself is done in
https://github.com/AllenInstitute/MIES/blob/948e0e319f17cbd9acf8b0d5092238859684e599/Packages/MIES/MIES_DAEphys.ipf#L57
.
>
> Can you send us the output of HW_NI_GetPropertyListOfDevices(devNr) where
devNr is either 0 or 1 depending on which of your devices is the PCIe-6341?
>
> From the specs at https://www.ni.com/pdf/manuals/377880a.pdf I think we
could support that as well. @timjarsky What do you think?

**Comment by timjarsky** [comment]
@t-b Yes, let's add Aaron's DAC to our supported device list. 

@neurosutras let me know if you'd like to do MIES walkthrough via screen share.

**Comment by t-b** [comment]
@neurosutras Thanks for the info. In #946 I have a PR which adds support for that device class.
