### ISSUE TITLE
Rethink or document labnotebook entry source type range conditions

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#953]
This was found with a buggy version of #943.

The following analysis function

```igorpro
Function Buggy(panelTitle, s)
	string panelTitle
	STRUCT AnalysisFunction_V3& s

	variable sweepNo

	if(s.eventType != POST_DAQ_EVENT)
		return 0
	endif

	WAVE numericalValues = GetLBNumericalValues(panelTitle)

	Make/FREE/D/N=(1, 1, LABNOTEBOOK_LAYER_COUNT) values = NaN
	values[][][INDEP_HEADSTAGE] = 1	

	Make/FREE/N=(3, 1)/T keys = ""

	keys[0][0] =  "blah 1"
	sweepNo = s.sweepNo - 1
	ED_AddEntriesToLabnotebook(values, keys, sweepNo, panelTitle, UNKNOWN_MODE)

	WAVE/z junk = GetLastSetting(numericalValues, sweepNo, "ADC", DATA_ACQUISITION_MODE)
	print junk

	keys[0][0] =  "blah 2"
	sweepNo = s.sweepNo - 1
	ED_AddEntriesToLabnotebook(values, keys, sweepNo, panelTitle, DATA_ACQUISITION_MODE)

	WAVE/z junk = GetLastSetting(numericalValues, sweepNo, "ADC", DATA_ACQUISITION_MODE)
	print junk

	return 0
End
```

outputs

```
  '_free_'[0]= {0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN}
  NULL wave
```

This means that the second `GetLastSetting` fails to find the "DAC" entry.

The reason for this behaviour can be found in b07dd1b5 (FindRange: Fix an edge case with sweep rollback and the entry source types, 2017-05-12) which explains that we search for a consecutive block backwards in the sweep range which has the given entry source type.

So when the LBN looks like

![grafik](https://user-images.githubusercontent.com/1185677/118001813-5d0b3e80-b347-11eb-8da4-0b0f381d5db6.png)

we can't find entries with entry source type 0 (DATA_ACQUISITION_MODE) anymore.

**Comment by t-b** [comment]
Some more explanation
---------------------

Our labnotebook stores entries per sweep. For distinguishing entries which exist for DAQ and TP we have introduced the entry source type in 1b21f99c (Bugfix: Disambiguate labnotebook entry search, 2016-10-08).

When sweep rollback is used we have to search LBN entries with entry source type only in the latest continous block, see b07dd1b5 (FindRange: Fix an edge case with sweep rollback and the entry source types, 2017-05-12).

So querying a very simplified labnotebook (all from one sweep) like

| entry        | entry source type | value |
|--------------|-------------------|-------|
| TP Baseline  | 0                 | 0.25  |
| IC Amplitude | 0                 | 10    |
| User entry   | NaN               | 3     |
| TP Baseline  | 0                 | 0.45  |
| IC Amplitude | 0                 | 20    |

with entry source type 0 being DATA_ACQUISITION_MODE.

Querying `TP Baseline` with entry source type DATA_ACQUISITION_MODE therefore returns 0.45.

Now imagine we add another user entry and one more DATA_ACQUISITION_MODE. Then we have

| entry        | entry source type | value |
|--------------|-------------------|-------|
| TP Baseline  | 0                 | 0.25  |
| IC Amplitude | 0                 | 10    |
| User entry   | NaN               | 3     |
| TP Baseline  | 0                 | 0.45  |
| IC Amplitude | 0                 | 20    |
| Other entry  | NaN               | 3     |
| Duration     | 0                 | 0.45  |

And now `TP Baseline` with entry source type DATA_ACQUISITION_MODE can not be found anymore as it is not present in the last continous block.

The entry source type NaN (UNKNOWN_MODE) is treated as if it where no entry source type. So when querying we don't check for continous ranges.

Due to these obstacles we have always:
- Written DATA_ACQUISITION_MODE entries only once in ED_createWaveNoteTags after saving the sweep
- Added additional labnotebook entries which can happen at random times (skip sweeps, daq stop reason, etc) with NaN entry source type

Using NaN as entry source type currently breaks sweep rollback. The whole point of the continous ranges was to handle sweep rollback properly after all.

So we can do the following:
- Nothing. And just add all other LBN entries with NaN as entry source type. This also accepts the limitation with sweep rollback and NaN entries.
- Remove sweep rollback, maybe replace it with wipe everyting?!, and remove the continous block reading logic for new labnotebooks. We must keep the old approach for existing labnotebooks.

**Comment by timjarsky** [comment]
Closing. Choosing to remove sweep roll back feature instead.
