### ISSUE TITLE
Add support for TP analysis via analysis functions and add `POST_TP_EVENT`

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#97]
- Add `POST_TP_EVENT` and send it out to all analysis functions with headstages which have "TP during DAQ enabled" after each testpulse is finished.
- This event has the full scaled Testpulse wave as payload in `s.scaledDacWave` (from #254)
- Is also sent out for the inserted TP
- Add and adapt tests

**Comment by timjarsky** [comment]
In some ways, the need for this is lessened because SF supports inserted TP analysis.

**Comment by timjarsky** [comment]
No use case for this feature at this time.
