### ISSUE TITLE
NWB Export with multiple devices issue

### ISSUE THREAD

**Issue by t-b** [AllenInstitute/MIES#978]
PXP and NWBv2:
[mies-igor.zip](https://github.com/AllenInstitute/MIES/files/6638994/mies-igor.zip)

The PXP has data from two devices each 1 sweep from HS0.

Looking at the data with the HDF5 Browser 

![grafik](https://user-images.githubusercontent.com/1185677/121700184-f2792a00-cacf-11eb-8125-3db3cb413f0e.png)

and the dump output

```
   SOFTLINK "electrode" {
      LINKTARGET "/general/intracellular_ephys/electrode_0"
   }

...

   SOFTLINK "electrode" {
      LINKTARGET "/general/intracellular_ephys/electrode_0"
   }
```

shows that both AD timeseries are linked to the same electrode and therefore to the same device. This is because as they use the same headstage number (electrode in NWB lingua) and we did not thought about that we need one NWB electrode for each device.

This bug is present in NWBv1 although less severe there because we also store the device name in the source attribute.

**Comment by timjarsky** [comment]
If devices are running different experiments, then create two NWB files. If yoking, then a single NWB is preferred.

**Comment by t-b** [comment]
@timjarsky The proposed solution here is always creating separate files, one per device. (See above comment). But #2127 proposes to adjust the NWB naming scheme to also allow data from multiple devices in one NWB file. And this would mean we would have to support data from multiple devices in one NWB file anyway. Is that correct?

**Comment by t-b** [comment]
Decided today: We only want to have data from one device in a NWB file.
